// ef-atlantis (dark) — bundled preset, both layers.
//
// The ef-themes are built on top of the modus-themes (since ef-themes 2.0.0):
// they use the same `modus-themes-theme` macro and palette structure. This seed
// is a faithful port so it can be edited and exported as a self-contained
// modus-themes derivative (no ef-themes dependency at load time).
//
// Transcribed verbatim from ef-atlantis-theme.el + ef-themes.el upstream:
//   - ef-atlantis-palette-partial            (named colors)
//   - ef-atlantis-palette-mappings-partial   (theme-specific mappings)
//   - ef-themes-palette-common            (shared mappings, appended)
// To refresh: re-transcribe from https://github.com/protesilaos/ef-themes
//
// A few shared entries (mode-line, tab-bar, bg-diff-context) are layer-1 colors
// in this model but defined upstream as mappings to other named colors; they are
// resolved to hex and placed in the palette block. All other mappings are kept
// symbolic, so resolve.ts follows the indirection as the modus engine does.

import { UNSPECIFIED as UNSPEC } from "./resolve.ts";
import type { Mapping, Palette, ThemeDoc } from "./types.ts";

const palette: Palette = {
  cursor: "#baa1ab",
  "bg-main": "#1a143e",
  "bg-dim": "#1a204b",
  "bg-alt": "#272a3e",
  "fg-main": "#bfcccf",
  "fg-dim": "#7f8385",
  "fg-alt": "#967e92",
  "bg-active": "#3a4661",
  "bg-inactive": "#24314f",
  border: "#454e59",
  red: "#ef656a",
  "red-warmer": "#f47360",
  "red-cooler": "#ef798f",
  "red-faint": "#c57062",
  green: "#1fa526",
  "green-warmer": "#77b22f",
  "green-cooler": "#00a962",
  "green-faint": "#81a06c",
  yellow: "#c48502",
  "yellow-warmer": "#e6832f",
  "yellow-cooler": "#b5967b",
  "yellow-faint": "#cab4a4",
  blue: "#379cf6",
  "blue-warmer": "#6a88ff",
  "blue-cooler": "#029fff",
  "blue-faint": "#7a7fff",
  magenta: "#d590af",
  "magenta-warmer": "#e580ea",
  "magenta-cooler": "#af9ef2",
  "magenta-faint": "#c5a4cf",
  cyan: "#4fb0cf",
  "cyan-warmer": "#6fafff",
  "cyan-cooler": "#5db2b7",
  "cyan-faint": "#90becf",
  "bg-red-intense": "#bd1f30",
  "bg-green-intense": "#107440",
  "bg-yellow-intense": "#846040",
  "bg-blue-intense": "#2f5f9f",
  "bg-magenta-intense": "#804fd5",
  "bg-cyan-intense": "#0280b9",
  "bg-red-subtle": "#7a2735",
  "bg-green-subtle": "#1a532f",
  "bg-yellow-subtle": "#704030",
  "bg-blue-subtle": "#1f4685",
  "bg-magenta-subtle": "#503575",
  "bg-cyan-subtle": "#114b6e",
  "bg-added": "#304a4f",
  "bg-added-faint": "#16383f",
  "bg-added-refine": "#2f6767",
  "fg-added": "#a0d0f0",
  "bg-changed": "#51512f",
  "bg-changed-faint": "#40332f",
  "bg-changed-refine": "#64651f",
  "fg-changed": "#dada90",
  "bg-removed": "#5a3142",
  "bg-removed-faint": "#4a2034",
  "bg-removed-refine": "#782a4a",
  "fg-removed": "#f0bfcf",
  "bg-mode-line-active": "#124a67",
  "fg-mode-line-active": "#aaccff",
  "bg-completion": "#2e387f",
  "bg-popup": "#102c3f",
  "bg-hover": "#5f4f7a",
  "bg-hover-secondary": "#2d3e4a",
  "bg-hl-line": "#2b265b",
  "bg-paren-match": "#603849",
  "bg-err": "#401500",
  "bg-warning": "#3e300c",
  "bg-info": "#003532",
  "bg-region": "#32446b",
  "modeline-err": "#ef656a", // ef-common mapping resolved
  "modeline-warning": "#b5967b", // ef-common mapping resolved
  "modeline-info": "#4fb0cf", // ef-common mapping resolved
  "bg-diff-context": "#1a204b", // ef-common mapping resolved
  "bg-tab-bar": "#272a3e", // ef-common mapping resolved
  "bg-tab-current": "#1a143e", // ef-common mapping resolved
  "bg-tab-other": "#3a4661", // ef-common mapping resolved
  "border-mode-line-active": "#454e59", // ef-common mapping resolved
  "bg-mode-line-inactive": "#272a3e", // ef-common mapping resolved
  "fg-mode-line-inactive": "#7f8385", // ef-common mapping resolved
  "border-mode-line-inactive": "#454e59", // ef-common mapping resolved
};

const mappings: Mapping = {
  // --- ef-atlantis-palette-mappings-partial ---
  err: "red-cooler",
  warning: "yellow-cooler",
  info: "green-cooler",
  "fg-link": "cyan-warmer",
  "fg-link-visited": "green-cooler",
  name: "blue-warmer",
  keybind: "cyan-cooler",
  identifier: "green-faint",
  "fg-prompt": "blue-warmer",
  builtin: "green-cooler",
  comment: "blue-faint",
  constant: "blue",
  fnname: "magenta-cooler",
  "fnname-call": "magenta-faint",
  keyword: "cyan-cooler",
  preprocessor: "yellow-cooler",
  docstring: "cyan-faint",
  string: "cyan-warmer",
  type: "blue-warmer",
  variable: "green-warmer",
  "variable-use": "green-faint",
  "rx-backslash": "green",
  "rx-construct": "yellow",
  "accent-0": "blue-warmer",
  "accent-1": "green-warmer",
  "accent-2": "cyan-cooler",
  "accent-3": "yellow-cooler",
  "date-common": "cyan-cooler",
  "date-deadline": "magenta-cooler",
  "date-deadline-subtle": "magenta-faint",
  "date-event": "cyan-faint",
  "date-holiday": "blue-cooler",
  "date-now": "fg-main",
  "date-range": "fg-alt",
  "date-scheduled": "blue",
  "date-scheduled-subtle": "blue-faint",
  "date-weekday": "cyan-warmer",
  "date-weekend": "yellow-faint",
  "fg-prose-code": "green-cooler",
  "prose-done": "cyan-cooler",
  "fg-prose-macro": "yellow-cooler",
  "prose-metadata": "fg-dim",
  "prose-metadata-value": "fg-alt",
  "prose-table": "fg-alt",
  "prose-table-formula": "info",
  "prose-tag": "fg-alt",
  "prose-todo": "magenta-warmer",
  "fg-prose-verbatim": "blue-cooler",
  "mail-cite-0": "cyan-warmer",
  "mail-cite-1": "green-warmer",
  "mail-cite-2": "cyan",
  "mail-cite-3": "yellow-cooler",
  "mail-part": "cyan-cooler",
  "mail-recipient": "cyan-warmer",
  "mail-subject": "green-cooler",
  "mail-other": "blue-warmer",
  "bg-search-static": "bg-warning",
  "bg-search-current": "bg-yellow-intense",
  "bg-search-lazy": "bg-blue-intense",
  "bg-search-replace": "bg-red-intense",
  "bg-search-rx-group-0": "bg-magenta-intense",
  "bg-search-rx-group-1": "bg-green-intense",
  "bg-search-rx-group-2": "bg-red-subtle",
  "bg-search-rx-group-3": "bg-cyan-subtle",
  "bg-space-err": "bg-yellow-intense",
  "rainbow-0": "cyan-warmer",
  "rainbow-1": "blue-warmer",
  "rainbow-2": "green-warmer",
  "rainbow-3": "yellow-cooler",
  "rainbow-4": "cyan",
  "rainbow-5": "magenta-cooler",
  "rainbow-6": "blue",
  "rainbow-7": "green",
  "rainbow-8": "magenta",

  // --- ef-themes-palette-common (shared across all ef-themes) ---
  fringe: UNSPEC,
  property: "variable",
  "fg-region": UNSPEC,
  "fg-link-symbolic": "fg-alt",
  "underline-link": "border",
  "underline-link-visited": "border",
  "underline-link-symbolic": "border",
  "bg-line-number-active": UNSPEC,
  "fg-line-number-active": "accent-0",
  "bg-line-number-inactive": UNSPEC,
  "bg-prominent-err": "bg-err",
  "bg-prominent-warning": "bg-warning",
  "bg-prominent-note": "bg-info",
  "fg-prominent-err": "err",
  "fg-prominent-warning": "warning",
  "fg-prominent-note": "info",
  "bg-space": UNSPEC,
  "fg-space": "border",
  "bg-active-argument": "bg-warning",
  "fg-active-argument": "warning",
  "bg-active-value": "bg-info",
  "fg-active-value": "info",
  "bg-mark-delete": "bg-err",
  "fg-mark-delete": "err",
  "bg-mark-select": "bg-info",
  "fg-mark-select": "info",
  "bg-mark-other": "bg-warning",
  "fg-mark-other": "warning",
  "fg-search-current": "fg-main",
  "fg-search-lazy": "fg-main",
  "fg-search-static": "fg-main",
  "fg-search-replace": "fg-main",
  "fg-search-rx-group-0": "fg-main",
  "fg-search-rx-group-1": "fg-main",
  "fg-search-rx-group-2": "fg-main",
  "fg-search-rx-group-3": "fg-main",
  "fg-completion-match-0": "accent-0",
  "fg-completion-match-1": "accent-1",
  "fg-completion-match-2": "accent-2",
  "fg-completion-match-3": "accent-3",
  "fg-heading-0": "rainbow-0",
  "fg-heading-1": "rainbow-1",
  "fg-heading-2": "rainbow-2",
  "fg-heading-3": "rainbow-3",
  "fg-heading-4": "rainbow-4",
  "fg-heading-5": "rainbow-5",
  "fg-heading-6": "rainbow-6",
  "fg-heading-7": "rainbow-7",
  "fg-heading-8": "rainbow-8",
};

export const efAtlantis: ThemeDoc = {
  meta: {
    name: "ef-atlantis",
    description: "Legible dark theme with aquatic colors.",
    mode: "dark",
  },
  palette,
  mappings,
};
