// ef-arcadia (light) — bundled preset, both layers.
//
// The ef-themes are built on top of the modus-themes (since ef-themes 2.0.0):
// they use the same `modus-themes-theme` macro and palette structure. This seed
// is a faithful port so it can be edited and exported as a self-contained
// modus-themes derivative (no ef-themes dependency at load time).
//
// Transcribed verbatim from ef-arcadia-theme.el + ef-themes.el upstream:
//   - ef-arcadia-palette-partial            (named colors)
//   - ef-arcadia-palette-mappings-partial   (theme-specific mappings)
//   - ef-themes-palette-common            (shared mappings, appended)
// To refresh: re-transcribe from https://github.com/protesilaos/ef-themes
//
// A few shared entries (mode-line, tab-bar, bg-diff-context) are layer-1 colors
// in this model but defined upstream as mappings to other named colors; they are
// resolved to hex and placed in the palette block. All other mappings are kept
// symbolic, so resolve.ts follows the indirection as the modus engine does.

import { UNSPECIFIED as UNSPEC } from "./resolve.ts";
import type { Mapping, Palette, ThemeDoc } from "./types.ts";

const palette: Palette = {
  cursor: "#495080",
  "bg-main": "#d6e4d3",
  "bg-dim": "#ced7c8",
  "bg-alt": "#c5c9c8",
  "fg-main": "#40314e",
  "fg-dim": "#646170",
  "fg-alt": "#3f5f5f",
  "bg-active": "#b0b7aa",
  "bg-inactive": "#bfc2b0",
  border: "#959a9f",
  red: "#882000",
  "red-warmer": "#9a1500",
  "red-cooler": "#800e38",
  "red-faint": "#702f1f",
  green: "#206020",
  "green-warmer": "#3f6d00",
  "green-cooler": "#006e50",
  "green-faint": "#125724",
  yellow: "#6b4500",
  "yellow-warmer": "#743f00",
  "yellow-cooler": "#775228",
  "yellow-faint": "#6a5937",
  blue: "#113384",
  "blue-warmer": "#3a40a0",
  "blue-cooler": "#0020b9",
  "blue-faint": "#302080",
  magenta: "#922e7f",
  "magenta-warmer": "#960f4f",
  "magenta-cooler": "#503094",
  "magenta-faint": "#72366f",
  cyan: "#125a7f",
  "cyan-warmer": "#2a5090",
  "cyan-cooler": "#005070",
  "cyan-faint": "#304650",
  "bg-red-intense": "#f08f88",
  "bg-green-intense": "#96df8f",
  "bg-yellow-intense": "#dfbf30",
  "bg-blue-intense": "#cfceff",
  "bg-magenta-intense": "#dfafff",
  "bg-cyan-intense": "#a0ddd0",
  "bg-red-subtle": "#efcabf",
  "bg-green-subtle": "#c3e6a0",
  "bg-yellow-subtle": "#efe07f",
  "bg-blue-subtle": "#c7dbe8",
  "bg-magenta-subtle": "#e3d0e7",
  "bg-cyan-subtle": "#bfe0d0",
  "bg-added": "#a0d7b0",
  "bg-added-faint": "#c0d5b2",
  "bg-added-refine": "#8bc794",
  "fg-added": "#005200",
  "bg-changed": "#e5e690",
  "bg-changed-faint": "#e5ddaf",
  "bg-changed-refine": "#edd482",
  "fg-changed": "#553d00",
  "bg-removed": "#edc5a6",
  "bg-removed-faint": "#e0c9ac",
  "bg-removed-refine": "#e4b492",
  "fg-removed": "#8f1013",
  "bg-mode-line-active": "#75b194",
  "fg-mode-line-active": "#155239",
  "bg-completion": "#b5b8c6",
  "bg-popup": "#dcdcd1",
  "bg-hover": "#afbad0",
  "bg-hover-secondary": "#a5d2af",
  "bg-hl-line": "#d0d0c0",
  "bg-paren-match": "#a09e84",
  "bg-err": "#e7c5a5",
  "bg-warning": "#e8d89a",
  "bg-info": "#a4dfb6",
  "bg-region": "#b3c5c0",
  "modeline-err": "#882000", // ef-common mapping resolved
  "modeline-warning": "#775228", // ef-common mapping resolved
  "modeline-info": "#125a7f", // ef-common mapping resolved
  "bg-diff-context": "#ced7c8", // ef-common mapping resolved
  "bg-tab-bar": "#c5c9c8", // ef-common mapping resolved
  "bg-tab-current": "#d6e4d3", // ef-common mapping resolved
  "bg-tab-other": "#b0b7aa", // ef-common mapping resolved
  "border-mode-line-active": "#959a9f", // ef-common mapping resolved
  "bg-mode-line-inactive": "#c5c9c8", // ef-common mapping resolved
  "fg-mode-line-inactive": "#646170", // ef-common mapping resolved
  "border-mode-line-inactive": "#959a9f", // ef-common mapping resolved
};

const mappings: Mapping = {
  // --- ef-arcadia-palette-mappings-partial ---
  err: "red-cooler",
  warning: "yellow-cooler",
  info: "green-cooler",
  "fg-link": "magenta-cooler",
  "fg-link-visited": "yellow-cooler",
  name: "blue",
  keybind: "cyan",
  identifier: "magenta-faint",
  "fg-prompt": "magenta-faint",
  builtin: "green-warmer",
  comment: "magenta-faint",
  constant: "magenta-cooler",
  fnname: "magenta",
  "fnname-call": "magenta-faint",
  keyword: "cyan",
  preprocessor: "blue-warmer",
  docstring: "cyan-faint",
  string: "cyan-warmer",
  type: "cyan-cooler",
  variable: "green-cooler",
  "variable-use": "green-faint",
  "rx-backslash": "yellow",
  "rx-construct": "red-warmer",
  "accent-0": "cyan",
  "accent-1": "magenta",
  "accent-2": "blue",
  "accent-3": "green",
  "date-common": "green-cooler",
  "date-deadline": "magenta",
  "date-deadline-subtle": "magenta-faint",
  "date-event": "cyan-faint",
  "date-holiday": "red-cooler",
  "date-now": "fg-main",
  "date-range": "fg-alt",
  "date-scheduled": "blue-warmer",
  "date-scheduled-subtle": "cyan-faint",
  "date-weekday": "cyan-cooler",
  "date-weekend": "magenta",
  "fg-prose-code": "green-warmer",
  "prose-done": "green-cooler",
  "fg-prose-macro": "blue-cooler",
  "prose-metadata": "fg-dim",
  "prose-metadata-value": "fg-alt",
  "prose-table": "fg-alt",
  "prose-table-formula": "info",
  "prose-tag": "fg-alt",
  "prose-todo": "magenta-warmer",
  "fg-prose-verbatim": "magenta",
  "mail-cite-0": "cyan-warmer",
  "mail-cite-1": "green-cooler",
  "mail-cite-2": "green-warmer",
  "mail-cite-3": "magenta-cooler",
  "mail-part": "cyan-cooler",
  "mail-recipient": "cyan-warmer",
  "mail-subject": "magenta",
  "mail-other": "blue-warmer",
  "bg-search-static": "bg-warning",
  "bg-search-current": "bg-yellow-intense",
  "bg-search-lazy": "bg-cyan-intense",
  "bg-search-replace": "bg-red-intense",
  "bg-search-rx-group-0": "bg-magenta-intense",
  "bg-search-rx-group-1": "bg-green-intense",
  "bg-search-rx-group-2": "bg-red-subtle",
  "bg-search-rx-group-3": "bg-cyan-subtle",
  "bg-space-err": "bg-yellow-intense",
  "rainbow-0": "green-cooler",
  "rainbow-1": "cyan-warmer",
  "rainbow-2": "green-warmer",
  "rainbow-3": "blue-warmer",
  "rainbow-4": "magenta",
  "rainbow-5": "blue",
  "rainbow-6": "cyan-cooler",
  "rainbow-7": "magenta-faint",
  "rainbow-8": "green",

  // --- ef-themes-palette-common (shared across all ef-themes) ---
  fringe: UNSPEC,
  property: "variable",
  "fg-region": UNSPEC,
  "fg-link-symbolic": "fg-alt",
  "underline-link": "border",
  "underline-link-visited": "border",
  "underline-link-symbolic": "border",
  "bg-line-number-active": UNSPEC,
  "fg-line-number-active": "accent-0",
  "bg-line-number-inactive": UNSPEC,
  "bg-prominent-err": "bg-err",
  "bg-prominent-warning": "bg-warning",
  "bg-prominent-note": "bg-info",
  "fg-prominent-err": "err",
  "fg-prominent-warning": "warning",
  "fg-prominent-note": "info",
  "bg-space": UNSPEC,
  "fg-space": "border",
  "bg-active-argument": "bg-warning",
  "fg-active-argument": "warning",
  "bg-active-value": "bg-info",
  "fg-active-value": "info",
  "bg-mark-delete": "bg-err",
  "fg-mark-delete": "err",
  "bg-mark-select": "bg-info",
  "fg-mark-select": "info",
  "bg-mark-other": "bg-warning",
  "fg-mark-other": "warning",
  "fg-search-current": "fg-main",
  "fg-search-lazy": "fg-main",
  "fg-search-static": "fg-main",
  "fg-search-replace": "fg-main",
  "fg-search-rx-group-0": "fg-main",
  "fg-search-rx-group-1": "fg-main",
  "fg-search-rx-group-2": "fg-main",
  "fg-search-rx-group-3": "fg-main",
  "fg-completion-match-0": "accent-0",
  "fg-completion-match-1": "accent-1",
  "fg-completion-match-2": "accent-2",
  "fg-completion-match-3": "accent-3",
  "fg-heading-0": "rainbow-0",
  "fg-heading-1": "rainbow-1",
  "fg-heading-2": "rainbow-2",
  "fg-heading-3": "rainbow-3",
  "fg-heading-4": "rainbow-4",
  "fg-heading-5": "rainbow-5",
  "fg-heading-6": "rainbow-6",
  "fg-heading-7": "rainbow-7",
  "fg-heading-8": "rainbow-8",
};

export const efArcadia: ThemeDoc = {
  meta: {
    name: "ef-arcadia",
    description: "Legible light theme with verdant colors.",
    mode: "light",
  },
  palette,
  mappings,
};
