// ef-arbutus (light) — bundled preset, both layers.
//
// The ef-themes are built on top of the modus-themes (since ef-themes 2.0.0):
// they use the same `modus-themes-theme` macro and palette structure. This seed
// is a faithful port so it can be edited and exported as a self-contained
// modus-themes derivative (no ef-themes dependency at load time).
//
// Transcribed verbatim from ef-arbutus-theme.el + ef-themes.el upstream:
//   - ef-arbutus-palette-partial            (named colors)
//   - ef-arbutus-palette-mappings-partial   (theme-specific mappings)
//   - ef-themes-palette-common            (shared mappings, appended)
// To refresh: re-transcribe from https://github.com/protesilaos/ef-themes
//
// A few shared entries (mode-line, tab-bar, bg-diff-context) are layer-1 colors
// in this model but defined upstream as mappings to other named colors; they are
// resolved to hex and placed in the palette block. All other mappings are kept
// symbolic, so resolve.ts follows the indirection as the modus engine does.

import { UNSPECIFIED as UNSPEC } from "./resolve.ts";
import type { Mapping, Palette, ThemeDoc } from "./types.ts";

const palette: Palette = {
  cursor: "#208f10",
  "bg-main": "#ffead8",
  "bg-dim": "#f0d8cf",
  "bg-alt": "#e7d2cb",
  "fg-main": "#393330",
  "fg-dim": "#6e678f",
  "fg-alt": "#8a5f4a",
  "bg-active": "#c7b2ab",
  "bg-inactive": "#f3daca",
  border: "#c0b4a6",
  red: "#b0000f",
  "red-warmer": "#b20f00",
  "red-cooler": "#aa184f",
  "red-faint": "#8f2f30",
  green: "#007000",
  "green-warmer": "#557000",
  "green-cooler": "#00704f",
  "green-faint": "#3f712f",
  yellow: "#906200",
  "yellow-warmer": "#b44405",
  "yellow-cooler": "#8a6340",
  "yellow-faint": "#8d6068",
  blue: "#375cc6",
  "blue-warmer": "#5f55df",
  "blue-cooler": "#265fbf",
  "blue-faint": "#4a659f",
  magenta: "#a23ea4",
  "magenta-warmer": "#bf2c90",
  "magenta-cooler": "#6448ca",
  "magenta-faint": "#845592",
  cyan: "#3f69af",
  "cyan-warmer": "#4060a0",
  "cyan-cooler": "#0f7688",
  "cyan-faint": "#546f70",
  "bg-red-intense": "#ff8f88",
  "bg-green-intense": "#96df80",
  "bg-yellow-intense": "#efbf00",
  "bg-blue-intense": "#afbeff",
  "bg-magenta-intense": "#bf9fff",
  "bg-cyan-intense": "#88d4f0",
  "bg-red-subtle": "#f9c2bf",
  "bg-green-subtle": "#c4eda0",
  "bg-yellow-subtle": "#efe76f",
  "bg-blue-subtle": "#cfdff0",
  "bg-magenta-subtle": "#f0d0f0",
  "bg-cyan-subtle": "#bfe8eb",
  "bg-added": "#d0e6b0",
  "bg-added-faint": "#e2efc0",
  "bg-added-refine": "#bbd799",
  "fg-added": "#005000",
  "bg-changed": "#f5e690",
  "bg-changed-faint": "#f5edaf",
  "bg-changed-refine": "#edd482",
  "fg-changed": "#553d00",
  "bg-removed": "#f8c6b6",
  "bg-removed-faint": "#f5d0b0",
  "bg-removed-refine": "#f0aaa9",
  "fg-removed": "#8f1313",
  "bg-mode-line-active": "#e9a0a0",
  "fg-mode-line-active": "#40231f",
  "bg-completion": "#f3c4c4",
  "bg-popup": "#ffdec1",
  "bg-hover": "#afdeaf",
  "bg-hover-secondary": "#f5bfc5",
  "bg-hl-line": "#fad8bf",
  "bg-paren-match": "#efafbf",
  "bg-err": "#ffd4b5",
  "bg-warning": "#efe48f",
  "bg-info": "#d0f0bc",
  "bg-region": "#dbe0c0",
  "bg-diff-context": "#f0d8cf", // ef-common mapping resolved
  "bg-tab-bar": "#e7d2cb", // ef-common mapping resolved
  "bg-tab-current": "#ffead8", // ef-common mapping resolved
  "bg-tab-other": "#c7b2ab", // ef-common mapping resolved
  "border-mode-line-active": "#c0b4a6", // ef-common mapping resolved
  "bg-mode-line-inactive": "#e7d2cb", // ef-common mapping resolved
  "fg-mode-line-inactive": "#6e678f", // ef-common mapping resolved
  "border-mode-line-inactive": "#c0b4a6", // ef-common mapping resolved
};

const mappings: Mapping = {
  // --- ef-arbutus-palette-mappings-partial ---
  err: "red-warmer",
  warning: "yellow",
  info: "green",
  "fg-link": "green-cooler",
  "fg-link-visited": "magenta-cooler",
  name: "red-cooler",
  keybind: "red",
  identifier: "magenta-faint",
  "fg-prompt": "red-faint",
  builtin: "green-cooler",
  comment: "fg-dim",
  constant: "magenta",
  fnname: "green",
  "fnname-call": "green-faint",
  keyword: "red-faint",
  preprocessor: "cyan-cooler",
  docstring: "yellow-faint",
  string: "green-warmer",
  type: "red",
  variable: "red-cooler",
  "variable-use": "red-faint",
  "rx-backslash": "yellow-warmer",
  "rx-construct": "cyan-cooler",
  "accent-0": "green",
  "accent-1": "red",
  "accent-2": "cyan",
  "accent-3": "yellow-warmer",
  "date-common": "green-faint",
  "date-deadline": "red-cooler",
  "date-deadline-subtle": "red-faint",
  "date-event": "fg-alt",
  "date-holiday": "yellow-warmer",
  "date-now": "fg-main",
  "date-range": "fg-alt",
  "date-scheduled": "yellow",
  "date-scheduled-subtle": "yellow-faint",
  "date-weekday": "green-cooler",
  "date-weekend": "red",
  "fg-prose-code": "magenta-warmer",
  "prose-done": "green",
  "fg-prose-macro": "yellow-warmer",
  "prose-metadata": "fg-dim",
  "prose-metadata-value": "fg-alt",
  "prose-table": "fg-alt",
  "prose-table-formula": "info",
  "prose-tag": "cyan-faint",
  "prose-todo": "yellow-warmer",
  "fg-prose-verbatim": "blue-cooler",
  "mail-cite-0": "green-cooler",
  "mail-cite-1": "green-warmer",
  "mail-cite-2": "red-cooler",
  "mail-cite-3": "yellow",
  "mail-part": "green",
  "mail-recipient": "red-faint",
  "mail-subject": "red",
  "mail-other": "red-warmer",
  "bg-search-static": "bg-warning",
  "bg-search-current": "bg-yellow-intense",
  "bg-search-lazy": "bg-blue-intense",
  "bg-search-replace": "bg-red-intense",
  "bg-search-rx-group-0": "bg-magenta-intense",
  "bg-search-rx-group-1": "bg-green-intense",
  "bg-search-rx-group-2": "bg-red-subtle",
  "bg-search-rx-group-3": "bg-cyan-subtle",
  "bg-space-err": "bg-yellow-intense",
  "rainbow-0": "green",
  "rainbow-1": "red-faint",
  "rainbow-2": "green-cooler",
  "rainbow-3": "yellow",
  "rainbow-4": "green-warmer",
  "rainbow-5": "cyan-cooler",
  "rainbow-6": "yellow-cooler",
  "rainbow-7": "red-cooler",
  "rainbow-8": "cyan",

  // --- ef-themes-palette-common (shared across all ef-themes) ---
  fringe: UNSPEC,
  property: "variable",
  "fg-region": UNSPEC,
  "fg-link-symbolic": "fg-alt",
  "underline-link": "border",
  "underline-link-visited": "border",
  "underline-link-symbolic": "border",
  "bg-line-number-active": UNSPEC,
  "fg-line-number-active": "accent-0",
  "bg-line-number-inactive": UNSPEC,
  "bg-prominent-err": "bg-err",
  "bg-prominent-warning": "bg-warning",
  "bg-prominent-note": "bg-info",
  "fg-prominent-err": "err",
  "fg-prominent-warning": "warning",
  "fg-prominent-note": "info",
  "bg-space": UNSPEC,
  "fg-space": "border",
  "bg-active-argument": "bg-warning",
  "fg-active-argument": "warning",
  "bg-active-value": "bg-info",
  "fg-active-value": "info",
  "bg-mark-delete": "bg-err",
  "fg-mark-delete": "err",
  "bg-mark-select": "bg-info",
  "fg-mark-select": "info",
  "bg-mark-other": "bg-warning",
  "fg-mark-other": "warning",
  "fg-search-current": "fg-main",
  "fg-search-lazy": "fg-main",
  "fg-search-static": "fg-main",
  "fg-search-replace": "fg-main",
  "fg-search-rx-group-0": "fg-main",
  "fg-search-rx-group-1": "fg-main",
  "fg-search-rx-group-2": "fg-main",
  "fg-search-rx-group-3": "fg-main",
  "fg-completion-match-0": "accent-0",
  "fg-completion-match-1": "accent-1",
  "fg-completion-match-2": "accent-2",
  "fg-completion-match-3": "accent-3",
  "fg-heading-0": "rainbow-0",
  "fg-heading-1": "rainbow-1",
  "fg-heading-2": "rainbow-2",
  "fg-heading-3": "rainbow-3",
  "fg-heading-4": "rainbow-4",
  "fg-heading-5": "rainbow-5",
  "fg-heading-6": "rainbow-6",
  "fg-heading-7": "rainbow-7",
  "fg-heading-8": "rainbow-8",
};

export const efArbutus: ThemeDoc = {
  meta: {
    name: "ef-arbutus",
    description: "Legible light pink theme with red and green colors.",
    mode: "light",
  },
  palette,
  mappings,
};
