// ef-bio (dark) — bundled preset, both layers.
//
// The ef-themes are built on top of the modus-themes (since ef-themes 2.0.0):
// they use the same `modus-themes-theme` macro and palette structure. This seed
// is a faithful port so it can be edited and exported as a self-contained
// modus-themes derivative (no ef-themes dependency at load time).
//
// Transcribed verbatim from ef-bio-theme.el + ef-themes.el upstream:
//   - ef-bio-palette-partial            (named colors)
//   - ef-bio-palette-mappings-partial   (theme-specific mappings)
//   - ef-themes-palette-common            (shared mappings, appended)
// To refresh: re-transcribe from https://github.com/protesilaos/ef-themes
//
// A few shared entries (mode-line, tab-bar, bg-diff-context) are layer-1 colors
// in this model but defined upstream as mappings to other named colors; they are
// resolved to hex and placed in the palette block. All other mappings are kept
// symbolic, so resolve.ts follows the indirection as the modus engine does.

import { UNSPECIFIED as UNSPEC } from "./resolve.ts";
import type { Mapping, Palette, ThemeDoc } from "./types.ts";

const palette: Palette = {
  cursor: "#35f038",
  "bg-main": "#111111",
  "bg-dim": "#222522",
  "bg-alt": "#303230",
  "fg-main": "#cfdfd5",
  "fg-dim": "#808f80",
  "fg-alt": "#8fcfaf",
  "bg-active": "#505250",
  "bg-inactive": "#262926",
  border: "#525959",
  red: "#ef6560",
  "red-warmer": "#f47360",
  "red-cooler": "#ff778f",
  "red-faint": "#d56f72",
  green: "#3fb83f",
  "green-warmer": "#7fc500",
  "green-cooler": "#00c089",
  "green-faint": "#7fc07f",
  yellow: "#d4aa02",
  "yellow-warmer": "#e09a0f",
  "yellow-cooler": "#cfc04f",
  "yellow-faint": "#b7a07f",
  blue: "#37aff6",
  "blue-warmer": "#78afff",
  "blue-cooler": "#32cfef",
  "blue-faint": "#6ab4cf",
  magenta: "#d38faf",
  "magenta-warmer": "#e490df",
  "magenta-cooler": "#af9fff",
  "magenta-faint": "#caa5bf",
  cyan: "#6fc5ef",
  "cyan-warmer": "#7fcfdf",
  "cyan-cooler": "#5dc0aa",
  "cyan-faint": "#7fb4cf",
  "bg-red-intense": "#b02930",
  "bg-green-intense": "#407430",
  "bg-yellow-intense": "#8f5040",
  "bg-blue-intense": "#4648d0",
  "bg-magenta-intense": "#a04fc5",
  "bg-cyan-intense": "#2270be",
  "bg-red-subtle": "#65201a",
  "bg-green-subtle": "#0a4425",
  "bg-yellow-subtle": "#523324",
  "bg-blue-subtle": "#1a3863",
  "bg-magenta-subtle": "#572853",
  "bg-cyan-subtle": "#113e57",
  "bg-added": "#003b1f",
  "bg-added-faint": "#002a10",
  "bg-added-refine": "#03512f",
  "fg-added": "#a0e0a0",
  "bg-changed": "#363300",
  "bg-changed-faint": "#2a1f00",
  "bg-changed-refine": "#4a4a00",
  "fg-changed": "#efef80",
  "bg-removed": "#4e1119",
  "bg-removed-faint": "#380a0f",
  "bg-removed-refine": "#751a1f",
  "fg-removed": "#ffbfbf",
  "bg-mode-line-active": "#00552f",
  "fg-mode-line-active": "#d0ffe0",
  "bg-completion": "#0f3c2f",
  "bg-popup": "#1d1d1d",
  "bg-hover": "#4f3f9a",
  "bg-hover-secondary": "#003e5f",
  "bg-hl-line": "#00331f",
  "bg-paren-match": "#664950",
  "bg-err": "#48100f",
  "bg-warning": "#3b3400",
  "bg-info": "#1a3b0f",
  "bg-region": "#3a3027",
  "bg-diff-context": "#222522", // ef-common mapping resolved
  "bg-tab-bar": "#303230", // ef-common mapping resolved
  "bg-tab-current": "#111111", // ef-common mapping resolved
  "bg-tab-other": "#505250", // ef-common mapping resolved
  "border-mode-line-active": "#525959", // ef-common mapping resolved
  "bg-mode-line-inactive": "#303230", // ef-common mapping resolved
  "fg-mode-line-inactive": "#808f80", // ef-common mapping resolved
  "border-mode-line-inactive": "#525959", // ef-common mapping resolved
};

const mappings: Mapping = {
  // --- ef-bio-palette-mappings-partial ---
  err: "red",
  warning: "yellow-cooler",
  info: "green",
  "fg-link": "green-cooler",
  "fg-link-visited": "magenta",
  name: "green",
  keybind: "green",
  identifier: "magenta-faint",
  "fg-prompt": "cyan-cooler",
  builtin: "green",
  comment: "yellow-faint",
  constant: "blue",
  fnname: "green-warmer",
  "fnname-call": "green-faint",
  keyword: "green-cooler",
  preprocessor: "cyan-cooler",
  docstring: "green-faint",
  string: "magenta-cooler",
  type: "cyan-warmer",
  variable: "blue-warmer",
  "variable-use": "blue-faint",
  "rx-backslash": "yellow-cooler",
  "rx-construct": "green",
  "accent-0": "green-cooler",
  "accent-1": "blue-warmer",
  "accent-2": "magenta-warmer",
  "accent-3": "green-warmer",
  "date-common": "cyan-cooler",
  "date-deadline": "red-cooler",
  "date-deadline-subtle": "red-faint",
  "date-event": "fg-alt",
  "date-holiday": "magenta-warmer",
  "date-now": "fg-main",
  "date-range": "fg-alt",
  "date-scheduled": "yellow-cooler",
  "date-scheduled-subtle": "yellow-faint",
  "date-weekday": "cyan",
  "date-weekend": "red-faint",
  "fg-prose-code": "blue-warmer",
  "prose-done": "green",
  "fg-prose-macro": "magenta-warmer",
  "prose-metadata": "fg-dim",
  "prose-metadata-value": "fg-alt",
  "prose-table": "fg-alt",
  "prose-table-formula": "warning",
  "prose-tag": "yellow-faint",
  "prose-todo": "red",
  "fg-prose-verbatim": "green-cooler",
  "mail-cite-0": "green-cooler",
  "mail-cite-1": "blue-warmer",
  "mail-cite-2": "green-warmer",
  "mail-cite-3": "magenta-cooler",
  "mail-part": "green-faint",
  "mail-recipient": "green",
  "mail-subject": "blue",
  "mail-other": "green-warmer",
  "bg-search-static": "bg-warning",
  "bg-search-current": "bg-yellow-intense",
  "bg-search-lazy": "bg-blue-intense",
  "bg-search-replace": "bg-red-intense",
  "bg-search-rx-group-0": "bg-magenta-intense",
  "bg-search-rx-group-1": "bg-green-intense",
  "bg-search-rx-group-2": "bg-red-subtle",
  "bg-search-rx-group-3": "bg-cyan-subtle",
  "bg-space-err": "bg-yellow-intense",
  "rainbow-0": "green-cooler",
  "rainbow-1": "green-warmer",
  "rainbow-2": "cyan-cooler",
  "rainbow-3": "magenta-cooler",
  "rainbow-4": "cyan-warmer",
  "rainbow-5": "yellow-cooler",
  "rainbow-6": "blue",
  "rainbow-7": "cyan",
  "rainbow-8": "magenta",

  // --- ef-themes-palette-common (shared across all ef-themes) ---
  fringe: UNSPEC,
  property: "variable",
  "fg-region": UNSPEC,
  "fg-link-symbolic": "fg-alt",
  "underline-link": "border",
  "underline-link-visited": "border",
  "underline-link-symbolic": "border",
  "bg-line-number-active": UNSPEC,
  "fg-line-number-active": "accent-0",
  "bg-line-number-inactive": UNSPEC,
  "bg-prominent-err": "bg-err",
  "bg-prominent-warning": "bg-warning",
  "bg-prominent-note": "bg-info",
  "fg-prominent-err": "err",
  "fg-prominent-warning": "warning",
  "fg-prominent-note": "info",
  "bg-space": UNSPEC,
  "fg-space": "border",
  "bg-active-argument": "bg-warning",
  "fg-active-argument": "warning",
  "bg-active-value": "bg-info",
  "fg-active-value": "info",
  "bg-mark-delete": "bg-err",
  "fg-mark-delete": "err",
  "bg-mark-select": "bg-info",
  "fg-mark-select": "info",
  "bg-mark-other": "bg-warning",
  "fg-mark-other": "warning",
  "fg-search-current": "fg-main",
  "fg-search-lazy": "fg-main",
  "fg-search-static": "fg-main",
  "fg-search-replace": "fg-main",
  "fg-search-rx-group-0": "fg-main",
  "fg-search-rx-group-1": "fg-main",
  "fg-search-rx-group-2": "fg-main",
  "fg-search-rx-group-3": "fg-main",
  "fg-completion-match-0": "accent-0",
  "fg-completion-match-1": "accent-1",
  "fg-completion-match-2": "accent-2",
  "fg-completion-match-3": "accent-3",
  "fg-heading-0": "rainbow-0",
  "fg-heading-1": "rainbow-1",
  "fg-heading-2": "rainbow-2",
  "fg-heading-3": "rainbow-3",
  "fg-heading-4": "rainbow-4",
  "fg-heading-5": "rainbow-5",
  "fg-heading-6": "rainbow-6",
  "fg-heading-7": "rainbow-7",
  "fg-heading-8": "rainbow-8",
};

export const efBio: ThemeDoc = {
  meta: {
    name: "ef-bio",
    description: "Legible dark green-black theme with green, teal, blue, purple colors.",
    mode: "dark",
  },
  palette,
  mappings,
};
