// ef-cyprus (light) — bundled preset, both layers.
//
// The ef-themes are built on top of the modus-themes (since ef-themes 2.0.0):
// they use the same `modus-themes-theme` macro and palette structure. This seed
// is a faithful port so it can be edited and exported as a self-contained
// modus-themes derivative (no ef-themes dependency at load time).
//
// Transcribed verbatim from ef-cyprus-theme.el + ef-themes.el upstream:
//   - ef-cyprus-palette-partial            (named colors)
//   - ef-cyprus-palette-mappings-partial   (theme-specific mappings)
//   - ef-themes-palette-common            (shared mappings, appended)
// To refresh: re-transcribe from https://github.com/protesilaos/ef-themes
//
// A few shared entries (mode-line, tab-bar, bg-diff-context) are layer-1 colors
// in this model but defined upstream as mappings to other named colors; they are
// resolved to hex and placed in the palette block. All other mappings are kept
// symbolic, so resolve.ts follows the indirection as the modus engine does.

import { UNSPECIFIED as UNSPEC } from "./resolve.ts";
import type { Mapping, Palette, ThemeDoc } from "./types.ts";

const palette: Palette = {
  cursor: "#007f00",
  "bg-main": "#fcf7ef",
  "bg-dim": "#f0ece0",
  "bg-alt": "#e5e3d8",
  "fg-main": "#242521",
  "fg-dim": "#59786f",
  "fg-alt": "#7f475a",
  "bg-active": "#c5c3b8",
  "bg-inactive": "#eee7e0",
  border: "#c4c0b6",
  red: "#9f0d0f",
  "red-warmer": "#dd0020",
  "red-cooler": "#ca3400",
  "red-faint": "#b05350",
  green: "#006f00",
  "green-warmer": "#557400",
  "green-cooler": "#00824f",
  "green-faint": "#3a6f48",
  yellow: "#a7601f",
  "yellow-warmer": "#bf4400",
  "yellow-cooler": "#a2604f",
  "yellow-faint": "#8f6f4a",
  blue: "#375cc6",
  "blue-warmer": "#444fcf",
  "blue-cooler": "#065fbf",
  "blue-faint": "#4a659f",
  magenta: "#9a456f",
  "magenta-warmer": "#bf456a",
  "magenta-cooler": "#8448aa",
  "magenta-faint": "#804f60",
  cyan: "#1f70af",
  "cyan-warmer": "#3f6faf",
  "cyan-cooler": "#007a9f",
  "cyan-faint": "#4f677f",
  "bg-red-intense": "#ff8f88",
  "bg-green-intense": "#96df80",
  "bg-yellow-intense": "#efbf00",
  "bg-blue-intense": "#cfceff",
  "bg-magenta-intense": "#df9fff",
  "bg-cyan-intense": "#88cfd0",
  "bg-red-subtle": "#ffc6bf",
  "bg-green-subtle": "#c4f2af",
  "bg-yellow-subtle": "#f0f07f",
  "bg-blue-subtle": "#ccdfff",
  "bg-magenta-subtle": "#fad3ff",
  "bg-cyan-subtle": "#bfefff",
  "bg-added": "#c1f2d1",
  "bg-added-faint": "#d8f8e1",
  "bg-added-refine": "#b1e4c1",
  "fg-added": "#005000",
  "bg-changed": "#ffdfb9",
  "bg-changed-faint": "#ffefcb",
  "bg-changed-refine": "#ffcfa0",
  "fg-changed": "#553d00",
  "bg-removed": "#ffd3d4",
  "bg-removed-faint": "#ffe6e1",
  "bg-removed-refine": "#f6c0c9",
  "fg-removed": "#8f1313",
  "bg-mode-line-active": "#c0df6f",
  "fg-mode-line-active": "#142010",
  "bg-completion": "#e3dbba",
  "bg-popup": "#f9eddb",
  "bg-hover": "#efc26f",
  "bg-hover-secondary": "#afc0f0",
  "bg-hl-line": "#f0e0d4",
  "bg-paren-match": "#9fcfdf",
  "bg-err": "#ffd4bf",
  "bg-warning": "#f0e8ba",
  "bg-info": "#d0efbf",
  "bg-region": "#e0e7e5",
  "bg-diff-context": "#f0ece0", // ef-common mapping resolved
  "bg-tab-bar": "#e5e3d8", // ef-common mapping resolved
  "bg-tab-current": "#fcf7ef", // ef-common mapping resolved
  "bg-tab-other": "#c5c3b8", // ef-common mapping resolved
  "border-mode-line-active": "#c4c0b6", // ef-common mapping resolved
  "bg-mode-line-inactive": "#e5e3d8", // ef-common mapping resolved
  "fg-mode-line-inactive": "#59786f", // ef-common mapping resolved
  "border-mode-line-inactive": "#c4c0b6", // ef-common mapping resolved
};

const mappings: Mapping = {
  // --- ef-cyprus-palette-mappings-partial ---
  err: "red-warmer",
  warning: "yellow",
  info: "green",
  "fg-link": "yellow",
  "fg-link-visited": "cyan",
  name: "green-warmer",
  keybind: "red",
  identifier: "green-faint",
  "fg-prompt": "green",
  builtin: "green-warmer",
  comment: "yellow-faint",
  constant: "green-cooler",
  fnname: "yellow",
  "fnname-call": "yellow-faint",
  keyword: "green",
  preprocessor: "red",
  docstring: "cyan-faint",
  string: "red-cooler",
  type: "blue-warmer",
  variable: "cyan-cooler",
  "variable-use": "cyan-faint",
  "rx-backslash": "magenta-cooler",
  "rx-construct": "cyan-cooler",
  "accent-0": "green",
  "accent-1": "red-cooler",
  "accent-2": "cyan-cooler",
  "accent-3": "yellow",
  "date-common": "yellow-cooler",
  "date-deadline": "red-cooler",
  "date-deadline-subtle": "red-faint",
  "date-event": "fg-alt",
  "date-holiday": "blue-cooler",
  "date-now": "fg-main",
  "date-range": "fg-alt",
  "date-scheduled": "yellow",
  "date-scheduled-subtle": "yellow-faint",
  "date-weekday": "cyan",
  "date-weekend": "red-faint",
  "fg-prose-code": "red-cooler",
  "prose-done": "green",
  "fg-prose-macro": "cyan-cooler",
  "prose-metadata": "fg-dim",
  "prose-metadata-value": "fg-alt",
  "prose-table": "fg-alt",
  "prose-table-formula": "info",
  "prose-tag": "yellow-faint",
  "prose-todo": "red-warmer",
  "fg-prose-verbatim": "green",
  "mail-cite-0": "green-warmer",
  "mail-cite-1": "yellow-cooler",
  "mail-cite-2": "cyan",
  "mail-cite-3": "green-cooler",
  "mail-part": "blue-faint",
  "mail-recipient": "green-warmer",
  "mail-subject": "yellow-warmer",
  "mail-other": "green",
  "bg-search-static": "bg-warning",
  "bg-search-current": "bg-yellow-intense",
  "bg-search-lazy": "bg-blue-intense",
  "bg-search-replace": "bg-red-intense",
  "bg-search-rx-group-0": "bg-magenta-intense",
  "bg-search-rx-group-1": "bg-green-intense",
  "bg-search-rx-group-2": "bg-red-subtle",
  "bg-search-rx-group-3": "bg-cyan-subtle",
  "bg-space-err": "bg-yellow-intense",
  "rainbow-0": "yellow",
  "rainbow-1": "green-warmer",
  "rainbow-2": "yellow-warmer",
  "rainbow-3": "cyan-warmer",
  "rainbow-4": "green-cooler",
  "rainbow-5": "magenta",
  "rainbow-6": "yellow-cooler",
  "rainbow-7": "cyan-cooler",
  "rainbow-8": "red",

  // --- ef-themes-palette-common (shared across all ef-themes) ---
  fringe: UNSPEC,
  property: "variable",
  "fg-region": UNSPEC,
  "fg-link-symbolic": "fg-alt",
  "underline-link": "border",
  "underline-link-visited": "border",
  "underline-link-symbolic": "border",
  "bg-line-number-active": UNSPEC,
  "fg-line-number-active": "accent-0",
  "bg-line-number-inactive": UNSPEC,
  "bg-prominent-err": "bg-err",
  "bg-prominent-warning": "bg-warning",
  "bg-prominent-note": "bg-info",
  "fg-prominent-err": "err",
  "fg-prominent-warning": "warning",
  "fg-prominent-note": "info",
  "bg-space": UNSPEC,
  "fg-space": "border",
  "bg-active-argument": "bg-warning",
  "fg-active-argument": "warning",
  "bg-active-value": "bg-info",
  "fg-active-value": "info",
  "bg-mark-delete": "bg-err",
  "fg-mark-delete": "err",
  "bg-mark-select": "bg-info",
  "fg-mark-select": "info",
  "bg-mark-other": "bg-warning",
  "fg-mark-other": "warning",
  "fg-search-current": "fg-main",
  "fg-search-lazy": "fg-main",
  "fg-search-static": "fg-main",
  "fg-search-replace": "fg-main",
  "fg-search-rx-group-0": "fg-main",
  "fg-search-rx-group-1": "fg-main",
  "fg-search-rx-group-2": "fg-main",
  "fg-search-rx-group-3": "fg-main",
  "fg-completion-match-0": "accent-0",
  "fg-completion-match-1": "accent-1",
  "fg-completion-match-2": "accent-2",
  "fg-completion-match-3": "accent-3",
  "fg-heading-0": "rainbow-0",
  "fg-heading-1": "rainbow-1",
  "fg-heading-2": "rainbow-2",
  "fg-heading-3": "rainbow-3",
  "fg-heading-4": "rainbow-4",
  "fg-heading-5": "rainbow-5",
  "fg-heading-6": "rainbow-6",
  "fg-heading-7": "rainbow-7",
  "fg-heading-8": "rainbow-8",
};

export const efCyprus: ThemeDoc = {
  meta: {
    name: "ef-cyprus",
    description: "Legible light ochre theme with green, yellow, teal, red colors.",
    mode: "light",
  },
  palette,
  mappings,
};
