// ef-cherie (dark) — bundled preset, both layers.
//
// The ef-themes are built on top of the modus-themes (since ef-themes 2.0.0):
// they use the same `modus-themes-theme` macro and palette structure. This seed
// is a faithful port so it can be edited and exported as a self-contained
// modus-themes derivative (no ef-themes dependency at load time).
//
// Transcribed verbatim from ef-cherie-theme.el + ef-themes.el upstream:
//   - ef-cherie-palette-partial            (named colors)
//   - ef-cherie-palette-mappings-partial   (theme-specific mappings)
//   - ef-themes-palette-common            (shared mappings, appended)
// To refresh: re-transcribe from https://github.com/protesilaos/ef-themes
//
// A few shared entries (mode-line, tab-bar, bg-diff-context) are layer-1 colors
// in this model but defined upstream as mappings to other named colors; they are
// resolved to hex and placed in the palette block. All other mappings are kept
// symbolic, so resolve.ts follows the indirection as the modus engine does.

import { UNSPECIFIED as UNSPEC } from "./resolve.ts";
import type { Mapping, Palette, ThemeDoc } from "./types.ts";

const palette: Palette = {
  cursor: "#ff5aaf",
  "bg-main": "#190a0f",
  "bg-dim": "#291f26",
  "bg-alt": "#392a2f",
  "fg-main": "#d3cfcf",
  "fg-dim": "#808898",
  "fg-alt": "#bf9cdf",
  "bg-active": "#594a4f",
  "bg-inactive": "#2e2226",
  border: "#695960",
  red: "#ff7359",
  "red-warmer": "#ff656f",
  "red-cooler": "#ff78aa",
  "red-faint": "#e47f72",
  green: "#60b444",
  "green-warmer": "#80b25f",
  "green-cooler": "#60bf88",
  "green-faint": "#61a06c",
  yellow: "#e5b76f",
  "yellow-warmer": "#ea9955",
  "yellow-cooler": "#f59280",
  "yellow-faint": "#bf9f8f",
  blue: "#8fa5f6",
  "blue-warmer": "#a897ef",
  "blue-cooler": "#7fa5ff",
  "blue-faint": "#7f9ab4",
  magenta: "#ef80bf",
  "magenta-warmer": "#f470df",
  "magenta-cooler": "#df7fff",
  "magenta-faint": "#cc9bcf",
  cyan: "#8fbaef",
  "cyan-warmer": "#9ac0e4",
  "cyan-cooler": "#8fcfdf",
  "cyan-faint": "#aac0cf",
  "bg-red-intense": "#b02930",
  "bg-green-intense": "#2a7140",
  "bg-yellow-intense": "#8f5040",
  "bg-blue-intense": "#4648d0",
  "bg-magenta-intense": "#804fd5",
  "bg-cyan-intense": "#2270cf",
  "bg-red-subtle": "#65102a",
  "bg-green-subtle": "#0a422f",
  "bg-yellow-subtle": "#523324",
  "bg-blue-subtle": "#2a3463",
  "bg-magenta-subtle": "#562654",
  "bg-cyan-subtle": "#133d58",
  "bg-added": "#00351f",
  "bg-added-faint": "#002410",
  "bg-added-refine": "#034d2f",
  "fg-added": "#a0e0a0",
  "bg-changed": "#363300",
  "bg-changed-faint": "#2a1f00",
  "bg-changed-refine": "#4a4a00",
  "fg-changed": "#efef80",
  "bg-removed": "#510c28",
  "bg-removed-faint": "#340a14",
  "bg-removed-refine": "#701a35",
  "fg-removed": "#ffbfbf",
  "bg-mode-line-active": "#771a4f",
  "fg-mode-line-active": "#ffcfdf",
  "bg-completion": "#4a1937",
  "bg-popup": "#2a1019",
  "bg-hover": "#303f6f",
  "bg-hover-secondary": "#66364f",
  "bg-hl-line": "#401f33",
  "bg-paren-match": "#3f5f75",
  "bg-err": "#461017",
  "bg-warning": "#3a3004",
  "bg-info": "#00352a",
  "bg-region": "#232f3f",
  "bg-diff-context": "#291f26", // ef-common mapping resolved
  "bg-tab-bar": "#392a2f", // ef-common mapping resolved
  "bg-tab-current": "#190a0f", // ef-common mapping resolved
  "bg-tab-other": "#594a4f", // ef-common mapping resolved
  "border-mode-line-active": "#695960", // ef-common mapping resolved
  "bg-mode-line-inactive": "#392a2f", // ef-common mapping resolved
  "fg-mode-line-inactive": "#808898", // ef-common mapping resolved
  "border-mode-line-inactive": "#695960", // ef-common mapping resolved
};

const mappings: Mapping = {
  // --- ef-cherie-palette-mappings-partial ---
  err: "red-warmer",
  warning: "yellow-warmer",
  info: "green",
  "fg-link": "magenta-cooler",
  "fg-link-visited": "yellow",
  name: "yellow-cooler",
  keybind: "yellow-warmer",
  identifier: "magenta-faint",
  "fg-prompt": "magenta-warmer",
  builtin: "blue-warmer",
  comment: "yellow-faint",
  constant: "red-cooler",
  fnname: "yellow-cooler",
  "fnname-call": "yellow-faint",
  keyword: "magenta",
  preprocessor: "cyan",
  docstring: "magenta-faint",
  string: "yellow",
  type: "magenta-warmer",
  variable: "magenta-cooler",
  "variable-use": "magenta-faint",
  "rx-backslash": "cyan-warmer",
  "rx-construct": "red",
  "accent-0": "magenta-warmer",
  "accent-1": "yellow",
  "accent-2": "blue-warmer",
  "accent-3": "red",
  "date-common": "magenta",
  "date-deadline": "red-warmer",
  "date-deadline-subtle": "red-faint",
  "date-event": "fg-alt",
  "date-holiday": "blue-warmer",
  "date-now": "fg-main",
  "date-range": "fg-alt",
  "date-scheduled": "yellow-warmer",
  "date-scheduled-subtle": "yellow-faint",
  "date-weekday": "cyan",
  "date-weekend": "red-faint",
  "fg-prose-code": "yellow",
  "prose-done": "green",
  "fg-prose-macro": "blue-warmer",
  "prose-metadata": "fg-dim",
  "prose-metadata-value": "fg-alt",
  "prose-table": "fg-alt",
  "prose-table-formula": "warning",
  "prose-tag": "yellow-faint",
  "prose-todo": "red-warmer",
  "fg-prose-verbatim": "magenta-warmer",
  "mail-cite-0": "magenta",
  "mail-cite-1": "yellow",
  "mail-cite-2": "blue-warmer",
  "mail-cite-3": "magenta-warmer",
  "mail-part": "magenta-cooler",
  "mail-recipient": "yellow-cooler",
  "mail-subject": "red",
  "mail-other": "yellow-warmer",
  "bg-search-static": "bg-warning",
  "bg-search-current": "bg-yellow-intense",
  "bg-search-lazy": "bg-blue-intense",
  "bg-search-replace": "bg-red-intense",
  "bg-search-rx-group-0": "bg-magenta-intense",
  "bg-search-rx-group-1": "bg-green-intense",
  "bg-search-rx-group-2": "bg-red-subtle",
  "bg-search-rx-group-3": "bg-cyan-subtle",
  "bg-space-err": "bg-yellow-intense",
  "rainbow-0": "magenta-warmer",
  "rainbow-1": "yellow",
  "rainbow-2": "magenta",
  "rainbow-3": "cyan",
  "rainbow-4": "yellow-cooler",
  "rainbow-5": "blue-warmer",
  "rainbow-6": "red-cooler",
  "rainbow-7": "cyan-warmer",
  "rainbow-8": "magenta-cooler",

  // --- ef-themes-palette-common (shared across all ef-themes) ---
  fringe: UNSPEC,
  property: "variable",
  "fg-region": UNSPEC,
  "fg-link-symbolic": "fg-alt",
  "underline-link": "border",
  "underline-link-visited": "border",
  "underline-link-symbolic": "border",
  "bg-line-number-active": UNSPEC,
  "fg-line-number-active": "accent-0",
  "bg-line-number-inactive": UNSPEC,
  "bg-prominent-err": "bg-err",
  "bg-prominent-warning": "bg-warning",
  "bg-prominent-note": "bg-info",
  "fg-prominent-err": "err",
  "fg-prominent-warning": "warning",
  "fg-prominent-note": "info",
  "bg-space": UNSPEC,
  "fg-space": "border",
  "bg-active-argument": "bg-warning",
  "fg-active-argument": "warning",
  "bg-active-value": "bg-info",
  "fg-active-value": "info",
  "bg-mark-delete": "bg-err",
  "fg-mark-delete": "err",
  "bg-mark-select": "bg-info",
  "fg-mark-select": "info",
  "bg-mark-other": "bg-warning",
  "fg-mark-other": "warning",
  "fg-search-current": "fg-main",
  "fg-search-lazy": "fg-main",
  "fg-search-static": "fg-main",
  "fg-search-replace": "fg-main",
  "fg-search-rx-group-0": "fg-main",
  "fg-search-rx-group-1": "fg-main",
  "fg-search-rx-group-2": "fg-main",
  "fg-search-rx-group-3": "fg-main",
  "fg-completion-match-0": "accent-0",
  "fg-completion-match-1": "accent-1",
  "fg-completion-match-2": "accent-2",
  "fg-completion-match-3": "accent-3",
  "fg-heading-0": "rainbow-0",
  "fg-heading-1": "rainbow-1",
  "fg-heading-2": "rainbow-2",
  "fg-heading-3": "rainbow-3",
  "fg-heading-4": "rainbow-4",
  "fg-heading-5": "rainbow-5",
  "fg-heading-6": "rainbow-6",
  "fg-heading-7": "rainbow-7",
  "fg-heading-8": "rainbow-8",
};

export const efCherie: ThemeDoc = {
  meta: {
    name: "ef-cherie",
    description: "Legible dark purple-black theme with warm colors (mostly pink, magenta, gold).",
    mode: "dark",
  },
  palette,
  mappings,
};
