// ef-duo-dark (dark) — bundled preset, both layers.
//
// The ef-themes are built on top of the modus-themes (since ef-themes 2.0.0):
// they use the same `modus-themes-theme` macro and palette structure. This seed
// is a faithful port so it can be edited and exported as a self-contained
// modus-themes derivative (no ef-themes dependency at load time).
//
// Transcribed verbatim from ef-duo-dark-theme.el + ef-themes.el upstream:
//   - ef-duo-dark-palette-partial            (named colors)
//   - ef-duo-dark-palette-mappings-partial   (theme-specific mappings)
//   - ef-themes-palette-common            (shared mappings, appended)
// To refresh: re-transcribe from https://github.com/protesilaos/ef-themes
//
// A few shared entries (mode-line, tab-bar, bg-diff-context) are layer-1 colors
// in this model but defined upstream as mappings to other named colors; they are
// resolved to hex and placed in the palette block. All other mappings are kept
// symbolic, so resolve.ts follows the indirection as the modus engine does.

import { UNSPECIFIED as UNSPEC } from "./resolve.ts";
import type { Mapping, Palette, ThemeDoc } from "./types.ts";

const palette: Palette = {
  cursor: "#ef6f11",
  "bg-main": "#070019",
  "bg-dim": "#1d1a26",
  "bg-alt": "#2a2739",
  "fg-main": "#d0d0d0",
  "fg-dim": "#857f8f",
  "fg-alt": "#89afef",
  "bg-active": "#4a4759",
  "bg-inactive": "#23202f",
  border: "#545f6f",
  red: "#ef656a",
  "red-warmer": "#f47360",
  "red-cooler": "#ef798f",
  "red-faint": "#d08f72",
  green: "#1fa526",
  "green-warmer": "#50a22f",
  "green-cooler": "#00b982",
  "green-faint": "#61a06c",
  yellow: "#c48702",
  "yellow-warmer": "#d0730f",
  "yellow-cooler": "#df805f",
  "yellow-faint": "#9f8f6a",
  blue: "#379cf6",
  "blue-warmer": "#6f80ff",
  "blue-cooler": "#029fff",
  "blue-faint": "#8a9fdf",
  magenta: "#d369af",
  "magenta-warmer": "#e580ea",
  "magenta-cooler": "#af85ff",
  "magenta-faint": "#c57faf",
  cyan: "#5faaef",
  "cyan-warmer": "#7fafff",
  "cyan-cooler": "#0dafdf",
  "cyan-faint": "#8aa0df",
  "bg-red-intense": "#cd2f30",
  "bg-green-intense": "#407720",
  "bg-yellow-intense": "#8f5040",
  "bg-blue-intense": "#4648d0",
  "bg-magenta-intense": "#b04fcf",
  "bg-cyan-intense": "#2270be",
  "bg-red-subtle": "#72002a",
  "bg-green-subtle": "#00422a",
  "bg-yellow-subtle": "#603000",
  "bg-blue-subtle": "#242679",
  "bg-magenta-subtle": "#501f72",
  "bg-cyan-subtle": "#004065",
  "bg-added": "#002d1f",
  "bg-added-faint": "#001f18",
  "bg-added-refine": "#003b2f",
  "fg-added": "#a0e0a0",
  "bg-changed": "#323200",
  "bg-changed-faint": "#2a2000",
  "bg-changed-refine": "#444000",
  "fg-changed": "#efef80",
  "bg-removed": "#3d091f",
  "bg-removed-faint": "#27040f",
  "bg-removed-refine": "#5b0f26",
  "fg-removed": "#ffbfbf",
  "bg-mode-line-active": "#352487",
  "fg-mode-line-active": "#dedeff",
  "bg-completion": "#2f2469",
  "bg-popup": "#0d0031",
  "bg-hover": "#664f4a",
  "bg-hover-secondary": "#264f4a",
  "bg-hl-line": "#301a4f",
  "bg-paren-match": "#2f608e",
  "bg-err": "#461210",
  "bg-warning": "#3a3004",
  "bg-info": "#10350a",
  "bg-region": "#042a50",
  "bg-diff-context": "#1d1a26", // ef-common mapping resolved
  "bg-tab-bar": "#2a2739", // ef-common mapping resolved
  "bg-tab-current": "#070019", // ef-common mapping resolved
  "bg-tab-other": "#4a4759", // ef-common mapping resolved
  "border-mode-line-active": "#545f6f", // ef-common mapping resolved
  "bg-mode-line-inactive": "#2a2739", // ef-common mapping resolved
  "fg-mode-line-inactive": "#857f8f", // ef-common mapping resolved
  "border-mode-line-inactive": "#545f6f", // ef-common mapping resolved
};

const mappings: Mapping = {
  // --- ef-duo-dark-palette-mappings-partial ---
  err: "red",
  warning: "yellow",
  info: "green",
  "fg-link": "cyan-warmer",
  "fg-link-visited": "green-cooler",
  name: "blue",
  keybind: "blue-cooler",
  identifier: "red-faint",
  "fg-prompt": "yellow",
  builtin: "cyan",
  comment: "red-faint",
  constant: "blue",
  fnname: "cyan-cooler",
  "fnname-call": "cyan-faint",
  keyword: "blue-warmer",
  preprocessor: "cyan-warmer",
  docstring: "blue-faint",
  string: "yellow-cooler",
  type: "blue-cooler",
  variable: "magenta-cooler",
  "variable-use": "magenta-faint",
  "rx-backslash": "magenta-cooler",
  "rx-construct": "blue",
  "accent-0": "blue-warmer",
  "accent-1": "yellow-warmer",
  "accent-2": "green-cooler",
  "accent-3": "red",
  "date-common": "cyan-cooler",
  "date-deadline": "red",
  "date-deadline-subtle": "red-faint",
  "date-event": "fg-alt",
  "date-holiday": "magenta-warmer",
  "date-now": "fg-main",
  "date-range": "fg-alt",
  "date-scheduled": "yellow",
  "date-scheduled-subtle": "yellow-faint",
  "date-weekday": "cyan",
  "date-weekend": "red-faint",
  "fg-prose-code": "yellow-warmer",
  "prose-done": "green",
  "fg-prose-macro": "green-cooler",
  "prose-metadata": "fg-dim",
  "prose-metadata-value": "fg-alt",
  "prose-table": "fg-alt",
  "prose-table-formula": "warning",
  "prose-tag": "yellow-faint",
  "prose-todo": "red",
  "fg-prose-verbatim": "blue-warmer",
  "mail-cite-0": "cyan",
  "mail-cite-1": "yellow-cooler",
  "mail-cite-2": "blue-warmer",
  "mail-cite-3": "yellow",
  "mail-part": "blue-faint",
  "mail-recipient": "blue",
  "mail-subject": "yellow-warmer",
  "mail-other": "cyan-warmer",
  "bg-search-static": "bg-warning",
  "bg-search-current": "bg-yellow-intense",
  "bg-search-lazy": "bg-blue-intense",
  "bg-search-replace": "bg-red-intense",
  "bg-search-rx-group-0": "bg-magenta-intense",
  "bg-search-rx-group-1": "bg-green-intense",
  "bg-search-rx-group-2": "bg-red-subtle",
  "bg-search-rx-group-3": "bg-cyan-subtle",
  "bg-space-err": "bg-yellow-intense",
  "rainbow-0": "blue",
  "rainbow-1": "yellow-warmer",
  "rainbow-2": "blue-warmer",
  "rainbow-3": "yellow-cooler",
  "rainbow-4": "cyan-cooler",
  "rainbow-5": "yellow",
  "rainbow-6": "blue-cooler",
  "rainbow-7": "red-cooler",
  "rainbow-8": "green-cooler",

  // --- ef-themes-palette-common (shared across all ef-themes) ---
  fringe: UNSPEC,
  property: "variable",
  "fg-region": UNSPEC,
  "fg-link-symbolic": "fg-alt",
  "underline-link": "border",
  "underline-link-visited": "border",
  "underline-link-symbolic": "border",
  "bg-line-number-active": UNSPEC,
  "fg-line-number-active": "accent-0",
  "bg-line-number-inactive": UNSPEC,
  "bg-prominent-err": "bg-err",
  "bg-prominent-warning": "bg-warning",
  "bg-prominent-note": "bg-info",
  "fg-prominent-err": "err",
  "fg-prominent-warning": "warning",
  "fg-prominent-note": "info",
  "bg-space": UNSPEC,
  "fg-space": "border",
  "bg-active-argument": "bg-warning",
  "fg-active-argument": "warning",
  "bg-active-value": "bg-info",
  "fg-active-value": "info",
  "bg-mark-delete": "bg-err",
  "fg-mark-delete": "err",
  "bg-mark-select": "bg-info",
  "fg-mark-select": "info",
  "bg-mark-other": "bg-warning",
  "fg-mark-other": "warning",
  "fg-search-current": "fg-main",
  "fg-search-lazy": "fg-main",
  "fg-search-static": "fg-main",
  "fg-search-replace": "fg-main",
  "fg-search-rx-group-0": "fg-main",
  "fg-search-rx-group-1": "fg-main",
  "fg-search-rx-group-2": "fg-main",
  "fg-search-rx-group-3": "fg-main",
  "fg-completion-match-0": "accent-0",
  "fg-completion-match-1": "accent-1",
  "fg-completion-match-2": "accent-2",
  "fg-completion-match-3": "accent-3",
  "fg-heading-0": "rainbow-0",
  "fg-heading-1": "rainbow-1",
  "fg-heading-2": "rainbow-2",
  "fg-heading-3": "rainbow-3",
  "fg-heading-4": "rainbow-4",
  "fg-heading-5": "rainbow-5",
  "fg-heading-6": "rainbow-6",
  "fg-heading-7": "rainbow-7",
  "fg-heading-8": "rainbow-8",
};

export const efDuoDark: ThemeDoc = {
  meta: {
    name: "ef-duo-dark",
    description: "Legible dark theme with mostly blue and orange colors.",
    mode: "dark",
  },
  palette,
  mappings,
};
