// ef-deuteranopia-light (light) — bundled preset, both layers.
//
// The ef-themes are built on top of the modus-themes (since ef-themes 2.0.0):
// they use the same `modus-themes-theme` macro and palette structure. This seed
// is a faithful port so it can be edited and exported as a self-contained
// modus-themes derivative (no ef-themes dependency at load time).
//
// Transcribed verbatim from ef-deuteranopia-light-theme.el + ef-themes.el upstream:
//   - ef-deuteranopia-light-palette-partial            (named colors)
//   - ef-deuteranopia-light-palette-mappings-partial   (theme-specific mappings)
//   - ef-themes-palette-common            (shared mappings, appended)
// To refresh: re-transcribe from https://github.com/protesilaos/ef-themes
//
// A few shared entries (mode-line, tab-bar, bg-diff-context) are layer-1 colors
// in this model but defined upstream as mappings to other named colors; they are
// resolved to hex and placed in the palette block. All other mappings are kept
// symbolic, so resolve.ts follows the indirection as the modus engine does.

import { UNSPECIFIED as UNSPEC } from "./resolve.ts";
import type { Mapping, Palette, ThemeDoc } from "./types.ts";

const palette: Palette = {
  cursor: "#0000bb",
  "bg-main": "#f5f5ff",
  "bg-dim": "#e8e8ea",
  "bg-alt": "#d3d3e0",
  "fg-main": "#1a1a2f",
  "fg-dim": "#70627f",
  "fg-alt": "#196f70",
  "bg-active": "#b3b3c0",
  "bg-inactive": "#e4e4f0",
  border: "#bcbcd0",
  red: "#d3303a",
  "red-warmer": "#e00033",
  "red-cooler": "#d50f7f",
  "red-faint": "#a04852",
  green: "#217a3c",
  "green-warmer": "#4a7d00",
  "green-cooler": "#008058",
  "green-faint": "#61756c",
  yellow: "#805d00",
  "yellow-warmer": "#965000",
  "yellow-cooler": "#765040",
  "yellow-faint": "#77604a",
  blue: "#375cd8",
  "blue-warmer": "#4250ef",
  "blue-cooler": "#065fff",
  "blue-faint": "#6060d0",
  magenta: "#ba35af",
  "magenta-warmer": "#cf25aa",
  "magenta-cooler": "#6052cf",
  "magenta-faint": "#9f5080",
  cyan: "#1f6fbf",
  "cyan-warmer": "#3f6faf",
  "cyan-cooler": "#1477b2",
  "cyan-faint": "#506fa0",
  "bg-red-intense": "#cac200",
  "bg-green-intense": "#9aaf80",
  "bg-yellow-intense": "#fac200",
  "bg-blue-intense": "#cbcfff",
  "bg-magenta-intense": "#3fbfff",
  "bg-cyan-intense": "#98e8ff",
  "bg-red-subtle": "#ead270",
  "bg-green-subtle": "#bae0a0",
  "bg-yellow-subtle": "#e6f270",
  "bg-blue-subtle": "#c0dfff",
  "bg-magenta-subtle": "#ccc8ff",
  "bg-cyan-subtle": "#afecf0",
  "bg-added": "#dbdbff",
  "bg-added-faint": "#e4e4ff",
  "bg-added-refine": "#c0c0ef",
  "fg-added": "#333399",
  "bg-changed": "#eecfdf",
  "bg-changed-faint": "#f0dde5",
  "bg-changed-refine": "#e0b0d0",
  "fg-changed": "#6f1343",
  "bg-removed": "#fff0af",
  "bg-removed-faint": "#efefcb",
  "bg-removed-refine": "#f0da88",
  "fg-removed": "#553d00",
  "bg-mode-line-active": "#99c7ff",
  "fg-mode-line-active": "#0a0a1f",
  "bg-completion": "#f0dacf",
  "bg-popup": "#ececf0",
  "bg-hover": "#eebb20",
  "bg-hover-secondary": "#afafef",
  "bg-hl-line": "#f3e0d5",
  "bg-paren-match": "#8fc0cf",
  "bg-err": "#f0e0a0",
  "bg-warning": "#e3ea9a",
  "bg-info": "#d0dfff",
  "bg-region": "#dadadf",
  "bg-diff-context": "#e8e8ea", // ef-common mapping resolved
  "bg-tab-bar": "#d3d3e0", // ef-common mapping resolved
  "bg-tab-current": "#f5f5ff", // ef-common mapping resolved
  "bg-tab-other": "#b3b3c0", // ef-common mapping resolved
  "border-mode-line-active": "#bcbcd0", // ef-common mapping resolved
  "bg-mode-line-inactive": "#d3d3e0", // ef-common mapping resolved
  "fg-mode-line-inactive": "#70627f", // ef-common mapping resolved
  "border-mode-line-inactive": "#bcbcd0", // ef-common mapping resolved
};

const mappings: Mapping = {
  // --- ef-deuteranopia-light-palette-mappings-partial ---
  err: "yellow-warmer",
  warning: "yellow-cooler",
  info: "blue-cooler",
  "fg-link": "blue",
  "fg-link-visited": "yellow-cooler",
  name: "blue-warmer",
  keybind: "yellow-warmer",
  identifier: "cyan-faint",
  "fg-prompt": "blue",
  builtin: "cyan",
  comment: "yellow-faint",
  constant: "yellow-cooler",
  fnname: "blue-cooler",
  "fnname-call": "blue-faint",
  keyword: "blue-warmer",
  preprocessor: "magenta-cooler",
  docstring: "cyan-faint",
  string: "yellow-warmer",
  type: "yellow",
  variable: "cyan-cooler",
  "variable-use": "cyan-faint",
  "rx-backslash": "cyan-faint",
  "rx-construct": "blue-warmer",
  "accent-0": "blue-cooler",
  "accent-1": "yellow-warmer",
  "accent-2": "cyan",
  "accent-3": "yellow-cooler",
  "date-common": "yellow-cooler",
  "date-deadline": "yellow-warmer",
  "date-deadline-subtle": "red-faint",
  "date-event": "fg-alt",
  "date-holiday": "cyan",
  "date-now": "fg-main",
  "date-range": "fg-alt",
  "date-scheduled": "yellow-cooler",
  "date-scheduled-subtle": "yellow-faint",
  "date-weekday": "cyan",
  "date-weekend": "magenta-faint",
  "fg-prose-code": "yellow-warmer",
  "prose-done": "blue-cooler",
  "fg-prose-macro": "cyan",
  "prose-metadata": "fg-dim",
  "prose-metadata-value": "fg-alt",
  "prose-table": "fg-alt",
  "prose-table-formula": "err",
  "prose-tag": "green-faint",
  "prose-todo": "yellow-warmer",
  "fg-prose-verbatim": "blue-cooler",
  "mail-cite-0": "blue-warmer",
  "mail-cite-1": "yellow-cooler",
  "mail-cite-2": "cyan-cooler",
  "mail-cite-3": "yellow",
  "mail-part": "blue-faint",
  "mail-recipient": "blue-warmer",
  "mail-subject": "blue-cooler",
  "mail-other": "cyan",
  "bg-space-err": "bg-yellow-intense",
  "bg-search-static": "bg-warning",
  "bg-search-current": "bg-yellow-intense",
  "bg-search-lazy": "bg-blue-intense",
  "bg-search-replace": "bg-magenta-intense",
  "bg-search-rx-group-0": "bg-cyan-intense",
  "bg-search-rx-group-1": "bg-magenta-intense",
  "bg-search-rx-group-2": "bg-blue-subtle",
  "bg-search-rx-group-3": "bg-yellow-subtle",
  "rainbow-0": "blue",
  "rainbow-1": "yellow",
  "rainbow-2": "blue-warmer",
  "rainbow-3": "yellow-cooler",
  "rainbow-4": "blue-cooler",
  "rainbow-5": "yellow-warmer",
  "rainbow-6": "blue-faint",
  "rainbow-7": "yellow-faint",
  "rainbow-8": "cyan",

  // --- ef-themes-palette-common (shared across all ef-themes) ---
  fringe: UNSPEC,
  property: "variable",
  "fg-region": UNSPEC,
  "fg-link-symbolic": "fg-alt",
  "underline-link": "border",
  "underline-link-visited": "border",
  "underline-link-symbolic": "border",
  "bg-line-number-active": UNSPEC,
  "fg-line-number-active": "accent-0",
  "bg-line-number-inactive": UNSPEC,
  "bg-prominent-err": "bg-err",
  "bg-prominent-warning": "bg-warning",
  "bg-prominent-note": "bg-info",
  "fg-prominent-err": "err",
  "fg-prominent-warning": "warning",
  "fg-prominent-note": "info",
  "bg-space": UNSPEC,
  "fg-space": "border",
  "bg-active-argument": "bg-warning",
  "fg-active-argument": "warning",
  "bg-active-value": "bg-info",
  "fg-active-value": "info",
  "bg-mark-delete": "bg-err",
  "fg-mark-delete": "err",
  "bg-mark-select": "bg-info",
  "fg-mark-select": "info",
  "bg-mark-other": "bg-warning",
  "fg-mark-other": "warning",
  "fg-search-current": "fg-main",
  "fg-search-lazy": "fg-main",
  "fg-search-static": "fg-main",
  "fg-search-replace": "fg-main",
  "fg-search-rx-group-0": "fg-main",
  "fg-search-rx-group-1": "fg-main",
  "fg-search-rx-group-2": "fg-main",
  "fg-search-rx-group-3": "fg-main",
  "fg-completion-match-0": "accent-0",
  "fg-completion-match-1": "accent-1",
  "fg-completion-match-2": "accent-2",
  "fg-completion-match-3": "accent-3",
  "fg-heading-0": "rainbow-0",
  "fg-heading-1": "rainbow-1",
  "fg-heading-2": "rainbow-2",
  "fg-heading-3": "rainbow-3",
  "fg-heading-4": "rainbow-4",
  "fg-heading-5": "rainbow-5",
  "fg-heading-6": "rainbow-6",
  "fg-heading-7": "rainbow-7",
  "fg-heading-8": "rainbow-8",
};

export const efDeuteranopiaLight: ThemeDoc = {
  meta: {
    name: "ef-deuteranopia-light",
    description: "Legible light theme, optimized for red-green color deficiency.",
    mode: "light",
  },
  palette,
  mappings,
};
