// ef-day (light) — bundled preset, both layers.
//
// The ef-themes are built on top of the modus-themes (since ef-themes 2.0.0):
// they use the same `modus-themes-theme` macro and palette structure. This seed
// is a faithful port so it can be edited and exported as a self-contained
// modus-themes derivative (no ef-themes dependency at load time).
//
// Transcribed verbatim from ef-day-theme.el + ef-themes.el upstream:
//   - ef-day-palette-partial            (named colors)
//   - ef-day-palette-mappings-partial   (theme-specific mappings)
//   - ef-themes-palette-common            (shared mappings, appended)
// To refresh: re-transcribe from https://github.com/protesilaos/ef-themes
//
// A few shared entries (mode-line, tab-bar, bg-diff-context) are layer-1 colors
// in this model but defined upstream as mappings to other named colors; they are
// resolved to hex and placed in the palette block. All other mappings are kept
// symbolic, so resolve.ts follows the indirection as the modus engine does.

import { UNSPECIFIED as UNSPEC } from "./resolve.ts";
import type { Mapping, Palette, ThemeDoc } from "./types.ts";

const palette: Palette = {
  cursor: "#cf1f00",
  "bg-main": "#fff5ea",
  "bg-dim": "#f2e9db",
  "bg-alt": "#e9e0d8",
  "fg-main": "#584141",
  "fg-dim": "#63728f",
  "fg-alt": "#8f5f4a",
  "bg-active": "#c9c0b8",
  "bg-inactive": "#f0e6db",
  border: "#c8bdb6",
  red: "#ba2d2f",
  "red-warmer": "#ce3f00",
  "red-cooler": "#cf2f4f",
  "red-faint": "#b05350",
  green: "#007a0a",
  "green-warmer": "#5f7200",
  "green-cooler": "#0f7f5f",
  "green-faint": "#527545",
  yellow: "#a45a22",
  "yellow-warmer": "#b75515",
  "yellow-cooler": "#aa4f30",
  "yellow-faint": "#9a625a",
  blue: "#375cc6",
  "blue-warmer": "#5f5fdf",
  "blue-cooler": "#265fbf",
  "blue-faint": "#4a659f",
  magenta: "#ca3e54",
  "magenta-warmer": "#cb2f80",
  "magenta-cooler": "#8448aa",
  "magenta-faint": "#a04450",
  cyan: "#3f60af",
  "cyan-warmer": "#3f6faf",
  "cyan-cooler": "#0f7b8f",
  "cyan-faint": "#4f6f8f",
  "bg-red-intense": "#ff8f88",
  "bg-green-intense": "#96df80",
  "bg-yellow-intense": "#efbf00",
  "bg-blue-intense": "#cfceff",
  "bg-magenta-intense": "#df9fff",
  "bg-cyan-intense": "#88cfd0",
  "bg-red-subtle": "#ffc6bf",
  "bg-green-subtle": "#c4f2af",
  "bg-yellow-subtle": "#f0f07f",
  "bg-blue-subtle": "#ccdfff",
  "bg-magenta-subtle": "#fad3ff",
  "bg-cyan-subtle": "#bfefff",
  "bg-added": "#ccefcf",
  "bg-added-faint": "#e0f3e0",
  "bg-added-refine": "#bae0c0",
  "fg-added": "#005000",
  "bg-changed": "#ffe5b9",
  "bg-changed-faint": "#ffefc5",
  "bg-changed-refine": "#ffd09f",
  "fg-changed": "#553d00",
  "bg-removed": "#ffd4d8",
  "bg-removed-faint": "#ffe3e3",
  "bg-removed-refine": "#ffc0ca",
  "fg-removed": "#8f1313",
  "bg-mode-line-active": "#ffaf72",
  "fg-mode-line-active": "#542f38",
  "bg-completion": "#f2d3d0",
  "bg-popup": "#ffead2",
  "bg-hover": "#b0e0df",
  "bg-hover-secondary": "#febccf",
  "bg-hl-line": "#f9e2b2",
  "bg-paren-match": "#8fcfdf",
  "bg-err": "#ffdde5",
  "bg-warning": "#ffe0aa",
  "bg-info": "#ddf5cc",
  "bg-region": "#f0d2df",
  "bg-diff-context": "#f2e9db", // ef-common mapping resolved
  "bg-tab-bar": "#e9e0d8", // ef-common mapping resolved
  "bg-tab-current": "#fff5ea", // ef-common mapping resolved
  "bg-tab-other": "#c9c0b8", // ef-common mapping resolved
  "border-mode-line-active": "#c8bdb6", // ef-common mapping resolved
  "bg-mode-line-inactive": "#e9e0d8", // ef-common mapping resolved
  "fg-mode-line-inactive": "#63728f", // ef-common mapping resolved
  "border-mode-line-inactive": "#c8bdb6", // ef-common mapping resolved
};

const mappings: Mapping = {
  // --- ef-day-palette-mappings-partial ---
  err: "red-warmer",
  warning: "yellow",
  info: "green",
  "fg-link": "cyan-warmer",
  "fg-link-visited": "green-warmer",
  name: "yellow",
  keybind: "red-warmer",
  identifier: "magenta-faint",
  "fg-prompt": "yellow",
  builtin: "red-cooler",
  comment: "green-faint",
  constant: "red-warmer",
  fnname: "magenta",
  "fnname-call": "magenta-faint",
  keyword: "yellow",
  preprocessor: "cyan-warmer",
  docstring: "yellow-faint",
  string: "green-warmer",
  type: "green-cooler",
  variable: "magenta-cooler",
  "variable-use": "magenta-faint",
  "rx-backslash": "blue",
  "rx-construct": "magenta-warmer",
  "accent-0": "red",
  "accent-1": "green-cooler",
  "accent-2": "yellow",
  "accent-3": "magenta-warmer",
  "date-common": "cyan-cooler",
  "date-deadline": "red",
  "date-deadline-subtle": "red-faint",
  "date-event": "fg-alt",
  "date-holiday": "red-warmer",
  "date-now": "fg-main",
  "date-range": "fg-alt",
  "date-scheduled": "yellow",
  "date-scheduled-subtle": "yellow-faint",
  "date-weekday": "cyan",
  "date-weekend": "red-faint",
  "fg-prose-code": "green-cooler",
  "prose-done": "green",
  "fg-prose-macro": "yellow",
  "prose-metadata": "fg-dim",
  "prose-metadata-value": "fg-alt",
  "prose-table": "fg-alt",
  "prose-table-formula": "info",
  "prose-tag": "yellow-faint",
  "prose-todo": "red-warmer",
  "fg-prose-verbatim": "red",
  "mail-cite-0": "red",
  "mail-cite-1": "green-cooler",
  "mail-cite-2": "yellow",
  "mail-cite-3": "cyan-warmer",
  "mail-part": "red-faint",
  "mail-recipient": "yellow",
  "mail-subject": "red-warmer",
  "mail-other": "green-warmer",
  "bg-search-static": "bg-warning",
  "bg-search-current": "bg-yellow-intense",
  "bg-search-lazy": "bg-blue-intense",
  "bg-search-replace": "bg-red-intense",
  "bg-search-rx-group-0": "bg-magenta-intense",
  "bg-search-rx-group-1": "bg-green-intense",
  "bg-search-rx-group-2": "bg-red-subtle",
  "bg-search-rx-group-3": "bg-cyan-subtle",
  "bg-space-err": "bg-yellow-intense",
  "rainbow-0": "yellow",
  "rainbow-1": "red",
  "rainbow-2": "green-warmer",
  "rainbow-3": "magenta-warmer",
  "rainbow-4": "cyan",
  "rainbow-5": "yellow-cooler",
  "rainbow-6": "magenta-cooler",
  "rainbow-7": "red-cooler",
  "rainbow-8": "green-cooler",

  // --- ef-themes-palette-common (shared across all ef-themes) ---
  fringe: UNSPEC,
  property: "variable",
  "fg-region": UNSPEC,
  "fg-link-symbolic": "fg-alt",
  "underline-link": "border",
  "underline-link-visited": "border",
  "underline-link-symbolic": "border",
  "bg-line-number-active": UNSPEC,
  "fg-line-number-active": "accent-0",
  "bg-line-number-inactive": UNSPEC,
  "bg-prominent-err": "bg-err",
  "bg-prominent-warning": "bg-warning",
  "bg-prominent-note": "bg-info",
  "fg-prominent-err": "err",
  "fg-prominent-warning": "warning",
  "fg-prominent-note": "info",
  "bg-space": UNSPEC,
  "fg-space": "border",
  "bg-active-argument": "bg-warning",
  "fg-active-argument": "warning",
  "bg-active-value": "bg-info",
  "fg-active-value": "info",
  "bg-mark-delete": "bg-err",
  "fg-mark-delete": "err",
  "bg-mark-select": "bg-info",
  "fg-mark-select": "info",
  "bg-mark-other": "bg-warning",
  "fg-mark-other": "warning",
  "fg-search-current": "fg-main",
  "fg-search-lazy": "fg-main",
  "fg-search-static": "fg-main",
  "fg-search-replace": "fg-main",
  "fg-search-rx-group-0": "fg-main",
  "fg-search-rx-group-1": "fg-main",
  "fg-search-rx-group-2": "fg-main",
  "fg-search-rx-group-3": "fg-main",
  "fg-completion-match-0": "accent-0",
  "fg-completion-match-1": "accent-1",
  "fg-completion-match-2": "accent-2",
  "fg-completion-match-3": "accent-3",
  "fg-heading-0": "rainbow-0",
  "fg-heading-1": "rainbow-1",
  "fg-heading-2": "rainbow-2",
  "fg-heading-3": "rainbow-3",
  "fg-heading-4": "rainbow-4",
  "fg-heading-5": "rainbow-5",
  "fg-heading-6": "rainbow-6",
  "fg-heading-7": "rainbow-7",
  "fg-heading-8": "rainbow-8",
};

export const efDay: ThemeDoc = {
  meta: {
    name: "ef-day",
    description: "Legible light sandy theme with warm, varied colors (yellow, red, green, purple).",
    mode: "light",
  },
  palette,
  mappings,
};
