// ef-dream (dark) — bundled preset, both layers.
//
// The ef-themes are built on top of the modus-themes (since ef-themes 2.0.0):
// they use the same `modus-themes-theme` macro and palette structure. This seed
// is a faithful port so it can be edited and exported as a self-contained
// modus-themes derivative (no ef-themes dependency at load time).
//
// Transcribed verbatim from ef-dream-theme.el + ef-themes.el upstream:
//   - ef-dream-palette-partial            (named colors)
//   - ef-dream-palette-mappings-partial   (theme-specific mappings)
//   - ef-themes-palette-common            (shared mappings, appended)
// To refresh: re-transcribe from https://github.com/protesilaos/ef-themes
//
// A few shared entries (mode-line, tab-bar, bg-diff-context) are layer-1 colors
// in this model but defined upstream as mappings to other named colors; they are
// resolved to hex and placed in the palette block. All other mappings are kept
// symbolic, so resolve.ts follows the indirection as the modus engine does.

import { UNSPECIFIED as UNSPEC } from "./resolve.ts";
import type { Mapping, Palette, ThemeDoc } from "./types.ts";

const palette: Palette = {
  cursor: "#f3c09a",
  "bg-main": "#232025",
  "bg-dim": "#322f34",
  "bg-alt": "#3b393e",
  "fg-main": "#efd5c5",
  "fg-dim": "#8f8886",
  "fg-alt": "#b0a0cf",
  "bg-active": "#5b595e",
  "bg-inactive": "#3a373c",
  border: "#635850",
  red: "#ff6f6f",
  "red-warmer": "#ff7a5f",
  "red-cooler": "#e47980",
  "red-faint": "#f3a0a0",
  green: "#51b04f",
  "green-warmer": "#7fce5f",
  "green-cooler": "#3fc489",
  "green-faint": "#a9c99f",
  yellow: "#c0b24f",
  "yellow-warmer": "#d09950",
  "yellow-cooler": "#deb07a",
  "yellow-faint": "#caa89f",
  blue: "#57b0ff",
  "blue-warmer": "#80aadf",
  "blue-cooler": "#12b4ff",
  "blue-faint": "#a0a0cf",
  magenta: "#ffaacf",
  "magenta-warmer": "#f498c0",
  "magenta-cooler": "#d0b0ff",
  "magenta-faint": "#e3b0c0",
  cyan: "#6fb3c0",
  "cyan-warmer": "#8fcfd0",
  "cyan-cooler": "#65c5a8",
  "cyan-faint": "#99bfcf",
  "bg-red-intense": "#a02f50",
  "bg-green-intense": "#30682f",
  "bg-yellow-intense": "#8f665f",
  "bg-blue-intense": "#4f509f",
  "bg-magenta-intense": "#885997",
  "bg-cyan-intense": "#0280b9",
  "bg-red-subtle": "#6f202a",
  "bg-green-subtle": "#2a532f",
  "bg-yellow-subtle": "#62432a",
  "bg-blue-subtle": "#3a3e73",
  "bg-magenta-subtle": "#66345a",
  "bg-cyan-subtle": "#334d69",
  "bg-added": "#304a4f",
  "bg-added-faint": "#16383f",
  "bg-added-refine": "#2f6767",
  "fg-added": "#a0d0f0",
  "bg-changed": "#51512f",
  "bg-changed-faint": "#40332f",
  "bg-changed-refine": "#64651f",
  "fg-changed": "#dada90",
  "bg-removed": "#5a3142",
  "bg-removed-faint": "#4a2034",
  "bg-removed-refine": "#782a4a",
  "fg-removed": "#f0bfcf",
  "bg-mode-line-active": "#675072",
  "fg-mode-line-active": "#fedeff",
  "bg-completion": "#503240",
  "bg-popup": "#2e2a31",
  "bg-hover": "#795056",
  "bg-hover-secondary": "#665f7a",
  "bg-hl-line": "#412f4f",
  "bg-paren-match": "#885566",
  "bg-err": "#501a2d",
  "bg-warning": "#4e3930",
  "bg-info": "#0f3f4f",
  "bg-region": "#544a50",
  "bg-diff-context": "#322f34", // ef-common mapping resolved
  "bg-tab-bar": "#3b393e", // ef-common mapping resolved
  "bg-tab-current": "#232025", // ef-common mapping resolved
  "bg-tab-other": "#5b595e", // ef-common mapping resolved
  "border-mode-line-active": "#635850", // ef-common mapping resolved
  "bg-mode-line-inactive": "#3b393e", // ef-common mapping resolved
  "fg-mode-line-inactive": "#8f8886", // ef-common mapping resolved
  "border-mode-line-inactive": "#635850", // ef-common mapping resolved
};

const mappings: Mapping = {
  // --- ef-dream-palette-mappings-partial ---
  err: "magenta-warmer",
  warning: "yellow-warmer",
  info: "cyan",
  "fg-link": "yellow-cooler",
  "fg-link-visited": "cyan-warmer",
  name: "cyan-warmer",
  keybind: "cyan",
  identifier: "yellow-cooler",
  "fg-prompt": "magenta",
  builtin: "magenta-faint",
  comment: "blue-faint",
  constant: "blue-warmer",
  fnname: "cyan-warmer",
  "fnname-call": "cyan-faint",
  keyword: "yellow-cooler",
  preprocessor: "cyan-cooler",
  docstring: "yellow-faint",
  string: "red-faint",
  type: "green-faint",
  variable: "magenta",
  "variable-use": "magenta-faint",
  "rx-backslash": "cyan-cooler",
  "rx-construct": "red-cooler",
  "accent-0": "yellow-cooler",
  "accent-1": "red-cooler",
  "accent-2": "magenta-warmer",
  "accent-3": "blue-warmer",
  "date-common": "magenta-faint",
  "date-deadline": "red-cooler",
  "date-deadline-subtle": "red-faint",
  "date-event": "fg-alt",
  "date-holiday": "red-warmer",
  "date-now": "fg-main",
  "date-range": "fg-alt",
  "date-scheduled": "yellow-cooler",
  "date-scheduled-subtle": "yellow-faint",
  "date-weekday": "magenta",
  "date-weekend": "blue-faint",
  "fg-prose-code": "blue-warmer",
  "prose-done": "cyan-warmer",
  "fg-prose-macro": "green-cooler",
  "prose-metadata": "fg-dim",
  "prose-metadata-value": "fg-alt",
  "prose-table": "fg-alt",
  "prose-table-formula": "info",
  "prose-tag": "yellow-faint",
  "prose-todo": "yellow-warmer",
  "fg-prose-verbatim": "magenta-warmer",
  "mail-cite-0": "yellow-cooler",
  "mail-cite-1": "red-cooler",
  "mail-cite-2": "cyan-faint",
  "mail-cite-3": "green-faint",
  "mail-part": "red-faint",
  "mail-recipient": "cyan-faint",
  "mail-subject": "magenta-warmer",
  "mail-other": "magenta-faint",
  "bg-search-static": "bg-warning",
  "bg-search-current": "bg-yellow-intense",
  "bg-search-lazy": "bg-blue-intense",
  "bg-search-replace": "bg-red-intense",
  "bg-search-rx-group-0": "bg-magenta-intense",
  "bg-search-rx-group-1": "bg-green-intense",
  "bg-search-rx-group-2": "bg-red-subtle",
  "bg-search-rx-group-3": "bg-cyan-subtle",
  "bg-space-err": "bg-yellow-intense",
  "rainbow-0": "yellow-cooler",
  "rainbow-1": "magenta",
  "rainbow-2": "blue-warmer",
  "rainbow-3": "red-cooler",
  "rainbow-4": "magenta-cooler",
  "rainbow-5": "green-cooler",
  "rainbow-6": "cyan",
  "rainbow-7": "yellow",
  "rainbow-8": "red-faint",

  // --- ef-themes-palette-common (shared across all ef-themes) ---
  fringe: UNSPEC,
  property: "variable",
  "fg-region": UNSPEC,
  "fg-link-symbolic": "fg-alt",
  "underline-link": "border",
  "underline-link-visited": "border",
  "underline-link-symbolic": "border",
  "bg-line-number-active": UNSPEC,
  "fg-line-number-active": "accent-0",
  "bg-line-number-inactive": UNSPEC,
  "bg-prominent-err": "bg-err",
  "bg-prominent-warning": "bg-warning",
  "bg-prominent-note": "bg-info",
  "fg-prominent-err": "err",
  "fg-prominent-warning": "warning",
  "fg-prominent-note": "info",
  "bg-space": UNSPEC,
  "fg-space": "border",
  "bg-active-argument": "bg-warning",
  "fg-active-argument": "warning",
  "bg-active-value": "bg-info",
  "fg-active-value": "info",
  "bg-mark-delete": "bg-err",
  "fg-mark-delete": "err",
  "bg-mark-select": "bg-info",
  "fg-mark-select": "info",
  "bg-mark-other": "bg-warning",
  "fg-mark-other": "warning",
  "fg-search-current": "fg-main",
  "fg-search-lazy": "fg-main",
  "fg-search-static": "fg-main",
  "fg-search-replace": "fg-main",
  "fg-search-rx-group-0": "fg-main",
  "fg-search-rx-group-1": "fg-main",
  "fg-search-rx-group-2": "fg-main",
  "fg-search-rx-group-3": "fg-main",
  "fg-completion-match-0": "accent-0",
  "fg-completion-match-1": "accent-1",
  "fg-completion-match-2": "accent-2",
  "fg-completion-match-3": "accent-3",
  "fg-heading-0": "rainbow-0",
  "fg-heading-1": "rainbow-1",
  "fg-heading-2": "rainbow-2",
  "fg-heading-3": "rainbow-3",
  "fg-heading-4": "rainbow-4",
  "fg-heading-5": "rainbow-5",
  "fg-heading-6": "rainbow-6",
  "fg-heading-7": "rainbow-7",
  "fg-heading-8": "rainbow-8",
};

export const efDream: ThemeDoc = {
  meta: {
    name: "ef-dream",
    description: "Legible dark purple grey theme with gold and nuanced colors.",
    mode: "dark",
  },
  palette,
  mappings,
};
