// ef-duo-light (light) — bundled preset, both layers.
//
// The ef-themes are built on top of the modus-themes (since ef-themes 2.0.0):
// they use the same `modus-themes-theme` macro and palette structure. This seed
// is a faithful port so it can be edited and exported as a self-contained
// modus-themes derivative (no ef-themes dependency at load time).
//
// Transcribed verbatim from ef-duo-light-theme.el + ef-themes.el upstream:
//   - ef-duo-light-palette-partial            (named colors)
//   - ef-duo-light-palette-mappings-partial   (theme-specific mappings)
//   - ef-themes-palette-common            (shared mappings, appended)
// To refresh: re-transcribe from https://github.com/protesilaos/ef-themes
//
// A few shared entries (mode-line, tab-bar, bg-diff-context) are layer-1 colors
// in this model but defined upstream as mappings to other named colors; they are
// resolved to hex and placed in the palette block. All other mappings are kept
// symbolic, so resolve.ts follows the indirection as the modus engine does.

import { UNSPECIFIED as UNSPEC } from "./resolve.ts";
import type { Mapping, Palette, ThemeDoc } from "./types.ts";

const palette: Palette = {
  cursor: "#1144ff",
  "bg-main": "#fff8f0",
  "bg-dim": "#f6ece8",
  "bg-alt": "#e7e0da",
  "fg-main": "#222222",
  "fg-dim": "#63728f",
  "fg-alt": "#856f4a",
  "bg-active": "#c7c0ba",
  "bg-inactive": "#f0eae7",
  border: "#baafba",
  red: "#cc3333",
  "red-warmer": "#dd1100",
  "red-cooler": "#c04440",
  "red-faint": "#a2403f",
  green: "#217a3c",
  "green-warmer": "#4a7d00",
  "green-cooler": "#008058",
  "green-faint": "#61756c",
  yellow: "#8a5d00",
  "yellow-warmer": "#9f4a00",
  "yellow-cooler": "#8f5a3a",
  "yellow-faint": "#765640",
  blue: "#375cd8",
  "blue-warmer": "#4250ef",
  "blue-cooler": "#065fff",
  "blue-faint": "#6060d0",
  magenta: "#ba35af",
  "magenta-warmer": "#cf25aa",
  "magenta-cooler": "#6052cf",
  "magenta-faint": "#af569f",
  cyan: "#1f6fbf",
  "cyan-warmer": "#3f70a0",
  "cyan-cooler": "#1f77bb",
  "cyan-faint": "#406f90",
  "bg-red-intense": "#ff8f88",
  "bg-green-intense": "#8adf80",
  "bg-yellow-intense": "#fac200",
  "bg-blue-intense": "#cbcfff",
  "bg-magenta-intense": "#df8fff",
  "bg-cyan-intense": "#88c8ff",
  "bg-red-subtle": "#ffcfbf",
  "bg-green-subtle": "#aff7c5",
  "bg-yellow-subtle": "#f9f376",
  "bg-blue-subtle": "#cfdff9",
  "bg-magenta-subtle": "#f9ddf0",
  "bg-cyan-subtle": "#bfeaf0",
  "bg-added": "#ccefcf",
  "bg-added-faint": "#e0f3e0",
  "bg-added-refine": "#bae0c0",
  "fg-added": "#005000",
  "bg-changed": "#ffe5b9",
  "bg-changed-faint": "#ffefc5",
  "bg-changed-refine": "#ffd09f",
  "fg-changed": "#553d00",
  "bg-removed": "#ffd4d8",
  "bg-removed-faint": "#ffe3e3",
  "bg-removed-refine": "#ffc0ca",
  "fg-removed": "#8f1313",
  "bg-mode-line-active": "#f8cf8f",
  "fg-mode-line-active": "#111133",
  "bg-completion": "#fadacf",
  "bg-popup": "#f8efef",
  "bg-hover": "#b4cfff",
  "bg-hover-secondary": "#aaeccf",
  "bg-hl-line": "#f9e8c0",
  "bg-paren-match": "#afbfef",
  "bg-err": "#ffdfe6",
  "bg-warning": "#ffe5ba",
  "bg-info": "#cff5d0",
  "bg-region": "#caeafa",
  "bg-diff-context": "#f6ece8", // ef-common mapping resolved
  "bg-tab-bar": "#e7e0da", // ef-common mapping resolved
  "bg-tab-current": "#fff8f0", // ef-common mapping resolved
  "bg-tab-other": "#c7c0ba", // ef-common mapping resolved
  "border-mode-line-active": "#baafba", // ef-common mapping resolved
  "bg-mode-line-inactive": "#e7e0da", // ef-common mapping resolved
  "fg-mode-line-inactive": "#63728f", // ef-common mapping resolved
  "border-mode-line-inactive": "#baafba", // ef-common mapping resolved
};

const mappings: Mapping = {
  // --- ef-duo-light-palette-mappings-partial ---
  err: "red",
  warning: "yellow",
  info: "green",
  "fg-link": "cyan",
  "fg-link-visited": "green-cooler",
  name: "blue",
  keybind: "blue-cooler",
  identifier: "red-faint",
  "fg-prompt": "blue-warmer",
  builtin: "cyan-cooler",
  comment: "red-faint",
  constant: "blue",
  fnname: "cyan",
  "fnname-call": "cyan-faint",
  keyword: "blue-warmer",
  preprocessor: "cyan-warmer",
  docstring: "cyan-faint",
  string: "yellow-warmer",
  type: "blue-cooler",
  variable: "magenta-cooler",
  "variable-use": "magenta-faint",
  "rx-backslash": "cyan",
  "rx-construct": "red-warmer",
  "accent-0": "blue-warmer",
  "accent-1": "yellow-warmer",
  "accent-2": "green-cooler",
  "accent-3": "red",
  "date-common": "cyan-cooler",
  "date-deadline": "red",
  "date-deadline-subtle": "red-faint",
  "date-event": "fg-alt",
  "date-holiday": "magenta-warmer",
  "date-now": "fg-main",
  "date-range": "fg-alt",
  "date-scheduled": "yellow",
  "date-scheduled-subtle": "yellow-faint",
  "date-weekday": "cyan",
  "date-weekend": "red-faint",
  "fg-prose-code": "yellow-warmer",
  "prose-done": "green",
  "fg-prose-macro": "green-cooler",
  "prose-metadata": "fg-dim",
  "prose-metadata-value": "fg-alt",
  "prose-table": "fg-alt",
  "prose-table-formula": "err",
  "prose-tag": "yellow-faint",
  "prose-todo": "red",
  "fg-prose-verbatim": "blue-warmer",
  "mail-cite-0": "blue",
  "mail-cite-1": "yellow-cooler",
  "mail-cite-2": "cyan-cooler",
  "mail-cite-3": "red-cooler",
  "mail-part": "blue-faint",
  "mail-recipient": "blue",
  "mail-subject": "yellow-warmer",
  "mail-other": "cyan",
  "bg-search-static": "bg-warning",
  "bg-search-current": "bg-yellow-intense",
  "bg-search-lazy": "bg-blue-intense",
  "bg-search-replace": "bg-red-intense",
  "bg-search-rx-group-0": "bg-magenta-intense",
  "bg-search-rx-group-1": "bg-green-intense",
  "bg-search-rx-group-2": "bg-red-subtle",
  "bg-search-rx-group-3": "bg-cyan-subtle",
  "bg-space-err": "bg-yellow-intense",
  "rainbow-0": "blue",
  "rainbow-1": "yellow-warmer",
  "rainbow-2": "blue-warmer",
  "rainbow-3": "yellow-cooler",
  "rainbow-4": "magenta-cooler",
  "rainbow-5": "green-warmer",
  "rainbow-6": "cyan-warmer",
  "rainbow-7": "yellow",
  "rainbow-8": "green-cooler",

  // --- ef-themes-palette-common (shared across all ef-themes) ---
  fringe: UNSPEC,
  property: "variable",
  "fg-region": UNSPEC,
  "fg-link-symbolic": "fg-alt",
  "underline-link": "border",
  "underline-link-visited": "border",
  "underline-link-symbolic": "border",
  "bg-line-number-active": UNSPEC,
  "fg-line-number-active": "accent-0",
  "bg-line-number-inactive": UNSPEC,
  "bg-prominent-err": "bg-err",
  "bg-prominent-warning": "bg-warning",
  "bg-prominent-note": "bg-info",
  "fg-prominent-err": "err",
  "fg-prominent-warning": "warning",
  "fg-prominent-note": "info",
  "bg-space": UNSPEC,
  "fg-space": "border",
  "bg-active-argument": "bg-warning",
  "fg-active-argument": "warning",
  "bg-active-value": "bg-info",
  "fg-active-value": "info",
  "bg-mark-delete": "bg-err",
  "fg-mark-delete": "err",
  "bg-mark-select": "bg-info",
  "fg-mark-select": "info",
  "bg-mark-other": "bg-warning",
  "fg-mark-other": "warning",
  "fg-search-current": "fg-main",
  "fg-search-lazy": "fg-main",
  "fg-search-static": "fg-main",
  "fg-search-replace": "fg-main",
  "fg-search-rx-group-0": "fg-main",
  "fg-search-rx-group-1": "fg-main",
  "fg-search-rx-group-2": "fg-main",
  "fg-search-rx-group-3": "fg-main",
  "fg-completion-match-0": "accent-0",
  "fg-completion-match-1": "accent-1",
  "fg-completion-match-2": "accent-2",
  "fg-completion-match-3": "accent-3",
  "fg-heading-0": "rainbow-0",
  "fg-heading-1": "rainbow-1",
  "fg-heading-2": "rainbow-2",
  "fg-heading-3": "rainbow-3",
  "fg-heading-4": "rainbow-4",
  "fg-heading-5": "rainbow-5",
  "fg-heading-6": "rainbow-6",
  "fg-heading-7": "rainbow-7",
  "fg-heading-8": "rainbow-8",
};

export const efDuoLight: ThemeDoc = {
  meta: {
    name: "ef-duo-light",
    description: "Legible light theme with mostly blue and yellow colors.",
    mode: "light",
  },
  palette,
  mappings,
};
