// ef-dark (dark) — bundled preset, both layers.
//
// The ef-themes are built on top of the modus-themes (since ef-themes 2.0.0):
// they use the same `modus-themes-theme` macro and palette structure. This seed
// is a faithful port so it can be edited and exported as a self-contained
// modus-themes derivative (no ef-themes dependency at load time).
//
// Transcribed verbatim from ef-dark-theme.el + ef-themes.el upstream:
//   - ef-dark-palette-partial            (named colors)
//   - ef-dark-palette-mappings-partial   (theme-specific mappings)
//   - ef-themes-palette-common            (shared mappings, appended)
// To refresh: re-transcribe from https://github.com/protesilaos/ef-themes
//
// A few shared entries (mode-line, tab-bar, bg-diff-context) are layer-1 colors
// in this model but defined upstream as mappings to other named colors; they are
// resolved to hex and placed in the palette block. All other mappings are kept
// symbolic, so resolve.ts follows the indirection as the modus engine does.

import { UNSPECIFIED as UNSPEC } from "./resolve.ts";
import type { Mapping, Palette, ThemeDoc } from "./types.ts";

const palette: Palette = {
  cursor: "#ff76ff",
  "bg-main": "#000000",
  "bg-dim": "#1a1a1a",
  "bg-alt": "#2b2b2b",
  "fg-main": "#d0d0d0",
  "fg-dim": "#857f8f",
  "fg-alt": "#89afef",
  "bg-active": "#4b4b4b",
  "bg-inactive": "#222222",
  border: "#4f4f5f",
  red: "#ef6560",
  "red-warmer": "#f47360",
  "red-cooler": "#ff5a7a",
  "red-faint": "#d56f72",
  green: "#0faa26",
  "green-warmer": "#6aad0f",
  "green-cooler": "#00a692",
  "green-faint": "#61a06c",
  yellow: "#bf9032",
  "yellow-warmer": "#d1843f",
  "yellow-cooler": "#df8a5a",
  "yellow-faint": "#cf9f8f",
  blue: "#3f95f6",
  "blue-warmer": "#6a9fff",
  "blue-cooler": "#029fff",
  "blue-faint": "#7a94df",
  magenta: "#d369af",
  "magenta-warmer": "#e580ea",
  "magenta-cooler": "#af85ff",
  "magenta-faint": "#c58faf",
  cyan: "#4fbaef",
  "cyan-warmer": "#6fafff",
  "cyan-cooler": "#1dbfcf",
  "cyan-faint": "#8aa0df",
  "bg-red-intense": "#b02930",
  "bg-green-intense": "#337133",
  "bg-yellow-intense": "#8f5040",
  "bg-blue-intense": "#4648d0",
  "bg-magenta-intense": "#804fdd",
  "bg-cyan-intense": "#2270cf",
  "bg-red-subtle": "#72002a",
  "bg-green-subtle": "#00422a",
  "bg-yellow-subtle": "#603000",
  "bg-blue-subtle": "#2f2f74",
  "bg-magenta-subtle": "#572060",
  "bg-cyan-subtle": "#004065",
  "bg-added": "#00381f",
  "bg-added-faint": "#002910",
  "bg-added-refine": "#034f2f",
  "fg-added": "#a0e0a0",
  "bg-changed": "#363300",
  "bg-changed-faint": "#2a1f00",
  "bg-changed-refine": "#4a4a00",
  "fg-changed": "#efef80",
  "bg-removed": "#4f1119",
  "bg-removed-faint": "#380a0f",
  "bg-removed-refine": "#781a1f",
  "fg-removed": "#ffbfbf",
  "bg-mode-line-active": "#2a2a75",
  "fg-mode-line-active": "#e0e0ff",
  "bg-completion": "#0f2d4a",
  "bg-popup": "#0c0c0c",
  "bg-hover": "#004a5f",
  "bg-hover-secondary": "#551f5a",
  "bg-hl-line": "#002435",
  "bg-paren-match": "#20577a",
  "bg-err": "#461210",
  "bg-warning": "#3a3004",
  "bg-info": "#10350a",
  "bg-region": "#2a234a",
  "bg-diff-context": "#1a1a1a", // ef-common mapping resolved
  "bg-tab-bar": "#2b2b2b", // ef-common mapping resolved
  "bg-tab-current": "#000000", // ef-common mapping resolved
  "bg-tab-other": "#4b4b4b", // ef-common mapping resolved
  "border-mode-line-active": "#4f4f5f", // ef-common mapping resolved
  "bg-mode-line-inactive": "#2b2b2b", // ef-common mapping resolved
  "fg-mode-line-inactive": "#857f8f", // ef-common mapping resolved
  "border-mode-line-inactive": "#4f4f5f", // ef-common mapping resolved
};

const mappings: Mapping = {
  // --- ef-dark-palette-mappings-partial ---
  err: "red-warmer",
  warning: "yellow",
  info: "green",
  "fg-link": "cyan",
  "fg-link-visited": "magenta",
  name: "blue-warmer",
  keybind: "blue-cooler",
  identifier: "magenta-faint",
  "fg-prompt": "green-cooler",
  builtin: "magenta",
  comment: "yellow-faint",
  constant: "blue-cooler",
  fnname: "magenta-warmer",
  "fnname-call": "magenta-faint",
  keyword: "magenta-cooler",
  preprocessor: "red",
  docstring: "cyan-faint",
  string: "blue-warmer",
  type: "green-cooler",
  variable: "cyan-cooler",
  "variable-use": "cyan-faint",
  "rx-backslash": "green-warmer",
  "rx-construct": "red",
  "accent-0": "blue",
  "accent-1": "magenta-warmer",
  "accent-2": "green-cooler",
  "accent-3": "red",
  "date-common": "green-cooler",
  "date-deadline": "red-warmer",
  "date-deadline-subtle": "red-faint",
  "date-event": "fg-alt",
  "date-holiday": "magenta",
  "date-now": "fg-main",
  "date-range": "fg-alt",
  "date-scheduled": "yellow",
  "date-scheduled-subtle": "yellow-faint",
  "date-weekday": "cyan",
  "date-weekend": "red-faint",
  "fg-prose-code": "magenta-warmer",
  "prose-done": "green",
  "fg-prose-macro": "green-cooler",
  "prose-metadata": "fg-dim",
  "prose-metadata-value": "fg-alt",
  "prose-table": "fg-alt",
  "prose-table-formula": "err",
  "prose-tag": "yellow-faint",
  "prose-todo": "red-warmer",
  "fg-prose-verbatim": "blue",
  "mail-cite-0": "blue",
  "mail-cite-1": "magenta-warmer",
  "mail-cite-2": "green-cooler",
  "mail-cite-3": "yellow-cooler",
  "mail-part": "magenta-faint",
  "mail-recipient": "blue-warmer",
  "mail-subject": "blue-cooler",
  "mail-other": "cyan",
  "bg-search-static": "bg-warning",
  "bg-search-current": "bg-yellow-intense",
  "bg-search-lazy": "bg-blue-intense",
  "bg-search-replace": "bg-red-intense",
  "bg-search-rx-group-0": "bg-magenta-intense",
  "bg-search-rx-group-1": "bg-green-intense",
  "bg-search-rx-group-2": "bg-red-subtle",
  "bg-search-rx-group-3": "bg-cyan-subtle",
  "bg-space-err": "bg-yellow-intense",
  "rainbow-0": "green-cooler",
  "rainbow-1": "blue",
  "rainbow-2": "magenta-warmer",
  "rainbow-3": "cyan-cooler",
  "rainbow-4": "yellow-cooler",
  "rainbow-5": "magenta-cooler",
  "rainbow-6": "red-cooler",
  "rainbow-7": "green-warmer",
  "rainbow-8": "yellow",

  // --- ef-themes-palette-common (shared across all ef-themes) ---
  fringe: UNSPEC,
  property: "variable",
  "fg-region": UNSPEC,
  "fg-link-symbolic": "fg-alt",
  "underline-link": "border",
  "underline-link-visited": "border",
  "underline-link-symbolic": "border",
  "bg-line-number-active": UNSPEC,
  "fg-line-number-active": "accent-0",
  "bg-line-number-inactive": UNSPEC,
  "bg-prominent-err": "bg-err",
  "bg-prominent-warning": "bg-warning",
  "bg-prominent-note": "bg-info",
  "fg-prominent-err": "err",
  "fg-prominent-warning": "warning",
  "fg-prominent-note": "info",
  "bg-space": UNSPEC,
  "fg-space": "border",
  "bg-active-argument": "bg-warning",
  "fg-active-argument": "warning",
  "bg-active-value": "bg-info",
  "fg-active-value": "info",
  "bg-mark-delete": "bg-err",
  "fg-mark-delete": "err",
  "bg-mark-select": "bg-info",
  "fg-mark-select": "info",
  "bg-mark-other": "bg-warning",
  "fg-mark-other": "warning",
  "fg-search-current": "fg-main",
  "fg-search-lazy": "fg-main",
  "fg-search-static": "fg-main",
  "fg-search-replace": "fg-main",
  "fg-search-rx-group-0": "fg-main",
  "fg-search-rx-group-1": "fg-main",
  "fg-search-rx-group-2": "fg-main",
  "fg-search-rx-group-3": "fg-main",
  "fg-completion-match-0": "accent-0",
  "fg-completion-match-1": "accent-1",
  "fg-completion-match-2": "accent-2",
  "fg-completion-match-3": "accent-3",
  "fg-heading-0": "rainbow-0",
  "fg-heading-1": "rainbow-1",
  "fg-heading-2": "rainbow-2",
  "fg-heading-3": "rainbow-3",
  "fg-heading-4": "rainbow-4",
  "fg-heading-5": "rainbow-5",
  "fg-heading-6": "rainbow-6",
  "fg-heading-7": "rainbow-7",
  "fg-heading-8": "rainbow-8",
};

export const efDark: ThemeDoc = {
  meta: {
    name: "ef-dark",
    description: "Legible dark theme with blue, magenta, cyan, purple colors.",
    mode: "dark",
  },
  palette,
  mappings,
};
