// ef-deuteranopia-dark (dark) — bundled preset, both layers.
//
// The ef-themes are built on top of the modus-themes (since ef-themes 2.0.0):
// they use the same `modus-themes-theme` macro and palette structure. This seed
// is a faithful port so it can be edited and exported as a self-contained
// modus-themes derivative (no ef-themes dependency at load time).
//
// Transcribed verbatim from ef-deuteranopia-dark-theme.el + ef-themes.el upstream:
//   - ef-deuteranopia-dark-palette-partial            (named colors)
//   - ef-deuteranopia-dark-palette-mappings-partial   (theme-specific mappings)
//   - ef-themes-palette-common            (shared mappings, appended)
// To refresh: re-transcribe from https://github.com/protesilaos/ef-themes
//
// A few shared entries (mode-line, tab-bar, bg-diff-context) are layer-1 colors
// in this model but defined upstream as mappings to other named colors; they are
// resolved to hex and placed in the palette block. All other mappings are kept
// symbolic, so resolve.ts follows the indirection as the modus engine does.

import { UNSPECIFIED as UNSPEC } from "./resolve.ts";
import type { Mapping, Palette, ThemeDoc } from "./types.ts";

const palette: Palette = {
  cursor: "#ffff00",
  "bg-main": "#000a1f",
  "bg-dim": "#121f34",
  "bg-alt": "#243145",
  "fg-main": "#ddddee",
  "fg-dim": "#7f8797",
  "fg-alt": "#90afef",
  "bg-active": "#445165",
  "bg-inactive": "#1d2439",
  border: "#555a64",
  red: "#cf8560",
  "red-warmer": "#e47360",
  "red-cooler": "#cf7a7a",
  "red-faint": "#b57f82",
  green: "#3faa26",
  "green-warmer": "#7aad0f",
  "green-cooler": "#3fa672",
  "green-faint": "#61a06c",
  yellow: "#aa9f32",
  "yellow-warmer": "#cfaf00",
  "yellow-cooler": "#bfaf7a",
  "yellow-faint": "#af9a6a",
  blue: "#3f90f0",
  "blue-warmer": "#6a9fff",
  "blue-cooler": "#009fff",
  "blue-faint": "#7a94df",
  magenta: "#b379bf",
  "magenta-warmer": "#af80ea",
  "magenta-cooler": "#9f95ff",
  "magenta-faint": "#c59fcf",
  cyan: "#5faaef",
  "cyan-warmer": "#7fafff",
  "cyan-cooler": "#0db0ff",
  "cyan-faint": "#8aa0df",
  "bg-red-intense": "#8d7f00",
  "bg-green-intense": "#afcf20",
  "bg-yellow-intense": "#5f5f00",
  "bg-blue-intense": "#266fd0",
  "bg-magenta-intense": "#6f60c0",
  "bg-cyan-intense": "#007fae",
  "bg-red-subtle": "#5d3f00",
  "bg-green-subtle": "#345f20",
  "bg-yellow-subtle": "#575700",
  "bg-blue-subtle": "#264f70",
  "bg-magenta-subtle": "#4a4670",
  "bg-cyan-subtle": "#265560",
  "bg-added": "#00234f",
  "bg-added-faint": "#00143f",
  "bg-added-refine": "#03395f",
  "fg-added": "#c4d5ff",
  "bg-changed": "#2f123f",
  "bg-changed-faint": "#1f022f",
  "bg-changed-refine": "#3f224f",
  "fg-changed": "#e3cfff",
  "bg-removed": "#323200",
  "bg-removed-faint": "#281a00",
  "bg-removed-refine": "#484800",
  "fg-removed": "#d4d48f",
  "bg-mode-line-active": "#003f8f",
  "fg-mode-line-active": "#ffffff",
  "bg-completion": "#343420",
  "bg-popup": "#001137",
  "bg-hover": "#4f4f00",
  "bg-hover-secondary": "#00405f",
  "bg-hl-line": "#2e2e1b",
  "bg-paren-match": "#0f4f9a",
  "bg-err": "#442f00",
  "bg-warning": "#3a3a1f",
  "bg-info": "#002b60",
  "bg-region": "#223848",
  "bg-diff-context": "#121f34", // ef-common mapping resolved
  "bg-tab-bar": "#243145", // ef-common mapping resolved
  "bg-tab-current": "#000a1f", // ef-common mapping resolved
  "bg-tab-other": "#445165", // ef-common mapping resolved
  "border-mode-line-active": "#555a64", // ef-common mapping resolved
  "bg-mode-line-inactive": "#243145", // ef-common mapping resolved
  "fg-mode-line-inactive": "#7f8797", // ef-common mapping resolved
  "border-mode-line-inactive": "#555a64", // ef-common mapping resolved
};

const mappings: Mapping = {
  // --- ef-deuteranopia-dark-palette-mappings-partial ---
  err: "yellow-warmer",
  warning: "yellow-cooler",
  info: "blue-cooler",
  "fg-link": "blue",
  "fg-link-visited": "yellow-cooler",
  name: "blue-warmer",
  keybind: "yellow-warmer",
  identifier: "cyan-faint",
  "fg-prompt": "blue-cooler",
  builtin: "blue-warmer",
  comment: "yellow-faint",
  constant: "blue-cooler",
  fnname: "yellow-cooler",
  "fnname-call": "yellow-faint",
  keyword: "yellow-warmer",
  preprocessor: "yellow",
  docstring: "cyan-faint",
  string: "blue",
  type: "magenta-cooler",
  variable: "cyan-cooler",
  "variable-use": "cyan-faint",
  "rx-backslash": "yellow-faint",
  "rx-construct": "yellow-warmer",
  "accent-0": "blue-cooler",
  "accent-1": "yellow-warmer",
  "accent-2": "cyan-warmer",
  "accent-3": "magenta-cooler",
  "date-common": "yellow-cooler",
  "date-deadline": "yellow-warmer",
  "date-deadline-subtle": "red-faint",
  "date-event": "fg-alt",
  "date-holiday": "cyan-warmer",
  "date-now": "fg-main",
  "date-range": "fg-alt",
  "date-scheduled": "yellow-cooler",
  "date-scheduled-subtle": "yellow-faint",
  "date-weekday": "cyan",
  "date-weekend": "magenta-faint",
  "fg-prose-code": "yellow-warmer",
  "prose-done": "blue-cooler",
  "fg-prose-macro": "cyan-warmer",
  "prose-metadata": "fg-dim",
  "prose-metadata-value": "fg-alt",
  "prose-table": "fg-alt",
  "prose-table-formula": "err",
  "prose-tag": "fg-alt",
  "prose-todo": "yellow-warmer",
  "fg-prose-verbatim": "blue-cooler",
  "mail-cite-0": "blue-warmer",
  "mail-cite-1": "yellow",
  "mail-cite-2": "blue-cooler",
  "mail-cite-3": "yellow-cooler",
  "mail-part": "cyan-faint",
  "mail-recipient": "blue-warmer",
  "mail-subject": "cyan-cooler",
  "mail-other": "cyan",
  "bg-search-static": "bg-warning",
  "bg-search-current": "bg-yellow-intense",
  "bg-search-lazy": "bg-blue-intense",
  "bg-search-replace": "bg-magenta-intense",
  "bg-search-rx-group-0": "bg-cyan-intense",
  "bg-search-rx-group-1": "bg-magenta-intense",
  "bg-search-rx-group-2": "bg-blue-subtle",
  "bg-search-rx-group-3": "bg-yellow-subtle",
  "bg-space-err": "bg-yellow-intense",
  "rainbow-0": "yellow-warmer",
  "rainbow-1": "blue",
  "rainbow-2": "yellow-cooler",
  "rainbow-3": "blue-warmer",
  "rainbow-4": "yellow",
  "rainbow-5": "cyan-warmer",
  "rainbow-6": "yellow-faint",
  "rainbow-7": "blue-faint",
  "rainbow-8": "magenta-faint",

  // --- ef-themes-palette-common (shared across all ef-themes) ---
  fringe: UNSPEC,
  property: "variable",
  "fg-region": UNSPEC,
  "fg-link-symbolic": "fg-alt",
  "underline-link": "border",
  "underline-link-visited": "border",
  "underline-link-symbolic": "border",
  "bg-line-number-active": UNSPEC,
  "fg-line-number-active": "accent-0",
  "bg-line-number-inactive": UNSPEC,
  "bg-prominent-err": "bg-err",
  "bg-prominent-warning": "bg-warning",
  "bg-prominent-note": "bg-info",
  "fg-prominent-err": "err",
  "fg-prominent-warning": "warning",
  "fg-prominent-note": "info",
  "bg-space": UNSPEC,
  "fg-space": "border",
  "bg-active-argument": "bg-warning",
  "fg-active-argument": "warning",
  "bg-active-value": "bg-info",
  "fg-active-value": "info",
  "bg-mark-delete": "bg-err",
  "fg-mark-delete": "err",
  "bg-mark-select": "bg-info",
  "fg-mark-select": "info",
  "bg-mark-other": "bg-warning",
  "fg-mark-other": "warning",
  "fg-search-current": "fg-main",
  "fg-search-lazy": "fg-main",
  "fg-search-static": "fg-main",
  "fg-search-replace": "fg-main",
  "fg-search-rx-group-0": "fg-main",
  "fg-search-rx-group-1": "fg-main",
  "fg-search-rx-group-2": "fg-main",
  "fg-search-rx-group-3": "fg-main",
  "fg-completion-match-0": "accent-0",
  "fg-completion-match-1": "accent-1",
  "fg-completion-match-2": "accent-2",
  "fg-completion-match-3": "accent-3",
  "fg-heading-0": "rainbow-0",
  "fg-heading-1": "rainbow-1",
  "fg-heading-2": "rainbow-2",
  "fg-heading-3": "rainbow-3",
  "fg-heading-4": "rainbow-4",
  "fg-heading-5": "rainbow-5",
  "fg-heading-6": "rainbow-6",
  "fg-heading-7": "rainbow-7",
  "fg-heading-8": "rainbow-8",
};

export const efDeuteranopiaDark: ThemeDoc = {
  meta: {
    name: "ef-deuteranopia-dark",
    description: "Legible dark theme, optimized for red-green color deficiency.",
    mode: "dark",
  },
  palette,
  mappings,
};
