// ef-elea-light (light) — bundled preset, both layers.
//
// The ef-themes are built on top of the modus-themes (since ef-themes 2.0.0):
// they use the same `modus-themes-theme` macro and palette structure. This seed
// is a faithful port so it can be edited and exported as a self-contained
// modus-themes derivative (no ef-themes dependency at load time).
//
// Transcribed verbatim from ef-elea-light-theme.el + ef-themes.el upstream:
//   - ef-elea-light-palette-partial            (named colors)
//   - ef-elea-light-palette-mappings-partial   (theme-specific mappings)
//   - ef-themes-palette-common            (shared mappings, appended)
// To refresh: re-transcribe from https://github.com/protesilaos/ef-themes
//
// A few shared entries (mode-line, tab-bar, bg-diff-context) are layer-1 colors
// in this model but defined upstream as mappings to other named colors; they are
// resolved to hex and placed in the palette block. All other mappings are kept
// symbolic, so resolve.ts follows the indirection as the modus engine does.

import { UNSPECIFIED as UNSPEC } from "./resolve.ts";
import type { Mapping, Palette, ThemeDoc } from "./types.ts";

const palette: Palette = {
  cursor: "#770080",
  "bg-main": "#edf5e2",
  "bg-dim": "#e3e9d6",
  "bg-alt": "#d0d7ca",
  "fg-main": "#221321",
  "fg-dim": "#676470",
  "fg-alt": "#5f5f1f",
  "bg-active": "#b0b7aa",
  "bg-inactive": "#e0e2d0",
  border: "#a5aaaf",
  red: "#c3303a",
  "red-warmer": "#d00000",
  "red-cooler": "#b02440",
  "red-faint": "#894852",
  green: "#00601f",
  "green-warmer": "#355500",
  "green-cooler": "#007047",
  "green-faint": "#306630",
  yellow: "#9a501f",
  "yellow-warmer": "#b04300",
  "yellow-cooler": "#88541f",
  "yellow-faint": "#7f4f4a",
  blue: "#375cc6",
  "blue-warmer": "#444fcf",
  "blue-cooler": "#162f8f",
  "blue-faint": "#3a5099",
  magenta: "#80308f",
  "magenta-warmer": "#9f356a",
  "magenta-cooler": "#5032aa",
  "magenta-faint": "#6a4a9f",
  cyan: "#1f70af",
  "cyan-warmer": "#3f6faf",
  "cyan-cooler": "#00677f",
  "cyan-faint": "#4f677f",
  "bg-red-intense": "#ff8f88",
  "bg-green-intense": "#a6df80",
  "bg-yellow-intense": "#efbf00",
  "bg-blue-intense": "#cfceff",
  "bg-magenta-intense": "#df9fff",
  "bg-cyan-intense": "#88cbdc",
  "bg-red-subtle": "#f0c6bf",
  "bg-green-subtle": "#c0e8a7",
  "bg-yellow-subtle": "#e4e48f",
  "bg-blue-subtle": "#c9d8f3",
  "bg-magenta-subtle": "#edd2f0",
  "bg-cyan-subtle": "#b7e4f0",
  "bg-added": "#c7e8ba",
  "bg-added-faint": "#def0cb",
  "bg-added-refine": "#bed9b0",
  "fg-added": "#005000",
  "bg-changed": "#f5e8b0",
  "bg-changed-faint": "#f5f2bf",
  "bg-changed-refine": "#f0db9a",
  "fg-changed": "#553d00",
  "bg-removed": "#f2d0c6",
  "bg-removed-faint": "#f0e0c0",
  "bg-removed-refine": "#efbfbd",
  "fg-removed": "#8f1313",
  "bg-mode-line-active": "#a5c67f",
  "fg-mode-line-active": "#142810",
  "bg-completion": "#c2e4ba",
  "bg-popup": "#e9efd1",
  "bg-hover": "#dfbac0",
  "bg-hover-secondary": "#b5dfbf",
  "bg-hl-line": "#d0e7c4",
  "bg-paren-match": "#8ad3a2",
  "bg-err": "#f2d5b5",
  "bg-warning": "#e8e8aa",
  "bg-info": "#b4efc6",
  "bg-region": "#d9d2ef",
  "bg-diff-context": "#e3e9d6", // ef-common mapping resolved
  "bg-tab-bar": "#d0d7ca", // ef-common mapping resolved
  "bg-tab-current": "#edf5e2", // ef-common mapping resolved
  "bg-tab-other": "#b0b7aa", // ef-common mapping resolved
  "border-mode-line-active": "#a5aaaf", // ef-common mapping resolved
  "bg-mode-line-inactive": "#d0d7ca", // ef-common mapping resolved
  "fg-mode-line-inactive": "#676470", // ef-common mapping resolved
  "border-mode-line-inactive": "#a5aaaf", // ef-common mapping resolved
};

const mappings: Mapping = {
  // --- ef-elea-light-palette-mappings-partial ---
  err: "red-warmer",
  warning: "yellow-warmer",
  info: "green-cooler",
  "fg-link": "green",
  "fg-link-visited": "magenta",
  name: "green-warmer",
  keybind: "magenta",
  identifier: "magenta-faint",
  "fg-prompt": "magenta-warmer",
  builtin: "magenta-faint",
  comment: "yellow-faint",
  constant: "magenta-cooler",
  fnname: "green-warmer",
  "fnname-call": "green-faint",
  keyword: "red-faint",
  preprocessor: "magenta-warmer",
  docstring: "cyan-faint",
  string: "green-cooler",
  type: "blue-cooler",
  variable: "magenta",
  "variable-use": "magenta-faint",
  "rx-backslash": "magenta-cooler",
  "rx-construct": "red",
  "accent-0": "green-cooler",
  "accent-1": "magenta-warmer",
  "accent-2": "magenta-cooler",
  "accent-3": "cyan",
  "date-common": "green-cooler",
  "date-deadline": "red",
  "date-deadline-subtle": "red-faint",
  "date-event": "fg-alt",
  "date-holiday": "magenta-warmer",
  "date-now": "fg-main",
  "date-range": "fg-alt",
  "date-scheduled": "yellow",
  "date-scheduled-subtle": "yellow-faint",
  "date-weekday": "cyan-cooler",
  "date-weekend": "red-faint",
  "fg-prose-code": "magenta",
  "prose-done": "green-cooler",
  "fg-prose-macro": "magenta-cooler",
  "prose-metadata": "fg-dim",
  "prose-metadata-value": "fg-alt",
  "prose-table": "fg-alt",
  "prose-table-formula": "err",
  "prose-tag": "cyan-faint",
  "prose-todo": "red",
  "fg-prose-verbatim": "cyan-cooler",
  "mail-cite-0": "cyan-cooler",
  "mail-cite-1": "magenta",
  "mail-cite-2": "green-warmer",
  "mail-cite-3": "magenta-cooler",
  "mail-part": "yellow-cooler",
  "mail-recipient": "red-faint",
  "mail-subject": "green-cooler",
  "mail-other": "green",
  "bg-search-static": "bg-warning",
  "bg-search-current": "bg-yellow-intense",
  "bg-search-lazy": "bg-blue-intense",
  "bg-search-replace": "bg-red-intense",
  "bg-search-rx-group-0": "bg-magenta-intense",
  "bg-search-rx-group-1": "bg-green-intense",
  "bg-search-rx-group-2": "bg-red-subtle",
  "bg-search-rx-group-3": "bg-cyan-subtle",
  "bg-space-err": "bg-yellow-intense",
  "rainbow-0": "green-warmer",
  "rainbow-1": "red-faint",
  "rainbow-2": "green-faint",
  "rainbow-3": "cyan-cooler",
  "rainbow-4": "magenta-cooler",
  "rainbow-5": "magenta-warmer",
  "rainbow-6": "green",
  "rainbow-7": "yellow",
  "rainbow-8": "magenta-faint",

  // --- ef-themes-palette-common (shared across all ef-themes) ---
  fringe: UNSPEC,
  property: "variable",
  "fg-region": UNSPEC,
  "fg-link-symbolic": "fg-alt",
  "underline-link": "border",
  "underline-link-visited": "border",
  "underline-link-symbolic": "border",
  "bg-line-number-active": UNSPEC,
  "fg-line-number-active": "accent-0",
  "bg-line-number-inactive": UNSPEC,
  "bg-prominent-err": "bg-err",
  "bg-prominent-warning": "bg-warning",
  "bg-prominent-note": "bg-info",
  "fg-prominent-err": "err",
  "fg-prominent-warning": "warning",
  "fg-prominent-note": "info",
  "bg-space": UNSPEC,
  "fg-space": "border",
  "bg-active-argument": "bg-warning",
  "fg-active-argument": "warning",
  "bg-active-value": "bg-info",
  "fg-active-value": "info",
  "bg-mark-delete": "bg-err",
  "fg-mark-delete": "err",
  "bg-mark-select": "bg-info",
  "fg-mark-select": "info",
  "bg-mark-other": "bg-warning",
  "fg-mark-other": "warning",
  "fg-search-current": "fg-main",
  "fg-search-lazy": "fg-main",
  "fg-search-static": "fg-main",
  "fg-search-replace": "fg-main",
  "fg-search-rx-group-0": "fg-main",
  "fg-search-rx-group-1": "fg-main",
  "fg-search-rx-group-2": "fg-main",
  "fg-search-rx-group-3": "fg-main",
  "fg-completion-match-0": "accent-0",
  "fg-completion-match-1": "accent-1",
  "fg-completion-match-2": "accent-2",
  "fg-completion-match-3": "accent-3",
  "fg-heading-0": "rainbow-0",
  "fg-heading-1": "rainbow-1",
  "fg-heading-2": "rainbow-2",
  "fg-heading-3": "rainbow-3",
  "fg-heading-4": "rainbow-4",
  "fg-heading-5": "rainbow-5",
  "fg-heading-6": "rainbow-6",
  "fg-heading-7": "rainbow-7",
  "fg-heading-8": "rainbow-8",
};

export const efEleaLight: ThemeDoc = {
  meta: {
    name: "ef-elea-light",
    description: "Legible light green theme with brown, magenta, and green colors.",
    mode: "light",
  },
  palette,
  mappings,
};
