// ef-eagle (light) — bundled preset, both layers.
//
// The ef-themes are built on top of the modus-themes (since ef-themes 2.0.0):
// they use the same `modus-themes-theme` macro and palette structure. This seed
// is a faithful port so it can be edited and exported as a self-contained
// modus-themes derivative (no ef-themes dependency at load time).
//
// Transcribed verbatim from ef-eagle-theme.el + ef-themes.el upstream:
//   - ef-eagle-palette-partial            (named colors)
//   - ef-eagle-palette-mappings-partial   (theme-specific mappings)
//   - ef-themes-palette-common            (shared mappings, appended)
// To refresh: re-transcribe from https://github.com/protesilaos/ef-themes
//
// A few shared entries (mode-line, tab-bar, bg-diff-context) are layer-1 colors
// in this model but defined upstream as mappings to other named colors; they are
// resolved to hex and placed in the palette block. All other mappings are kept
// symbolic, so resolve.ts follows the indirection as the modus engine does.

import { UNSPECIFIED as UNSPEC } from "./resolve.ts";
import type { Mapping, Palette, ThemeDoc } from "./types.ts";

const palette: Palette = {
  cursor: "#774400",
  "bg-main": "#f1ecd0",
  "bg-dim": "#e4dbc0",
  "bg-alt": "#cec8ae",
  "fg-main": "#231a1f",
  "fg-dim": "#685f53",
  "fg-alt": "#524874",
  "bg-active": "#aea88e",
  "bg-inactive": "#e0d8c3",
  border: "#7f785f",
  red: "#882000",
  "red-warmer": "#9a0000",
  "red-cooler": "#8f0038",
  "red-faint": "#702f1f",
  green: "#226022",
  "green-warmer": "#3a7800",
  "green-cooler": "#006e50",
  "green-faint": "#42573f",
  yellow: "#6b4500",
  "yellow-warmer": "#843300",
  "yellow-cooler": "#775228",
  "yellow-faint": "#6a5937",
  blue: "#113384",
  "blue-warmer": "#3a3da0",
  "blue-cooler": "#000080",
  "blue-faint": "#2f3460",
  magenta: "#822478",
  "magenta-warmer": "#960f4f",
  "magenta-cooler": "#50119f",
  "magenta-faint": "#603a6f",
  cyan: "#125a7f",
  "cyan-warmer": "#4a5d90",
  "cyan-cooler": "#00676f",
  "cyan-faint": "#304f60",
  "bg-red-intense": "#f08f88",
  "bg-green-intense": "#96df8f",
  "bg-yellow-intense": "#efbf00",
  "bg-blue-intense": "#cfceff",
  "bg-magenta-intense": "#dfafff",
  "bg-cyan-intense": "#a0ddd0",
  "bg-red-subtle": "#efcabf",
  "bg-green-subtle": "#c3e6a0",
  "bg-yellow-subtle": "#efe07f",
  "bg-blue-subtle": "#c7dbe8",
  "bg-magenta-subtle": "#e3d0e7",
  "bg-cyan-subtle": "#bfe0d0",
  "bg-added": "#b0e7b0",
  "bg-added-faint": "#d0e7c2",
  "bg-added-refine": "#9ad590",
  "fg-added": "#005200",
  "bg-changed": "#f5e690",
  "bg-changed-faint": "#f5edaf",
  "bg-changed-refine": "#edd482",
  "fg-changed": "#553d00",
  "bg-removed": "#f8c8a6",
  "bg-removed-faint": "#f0d9bc",
  "bg-removed-refine": "#f0aa90",
  "fg-removed": "#8f1013",
  "bg-mode-line-active": "#cfab80",
  "fg-mode-line-active": "#2f1005",
  "bg-completion": "#dfc8af",
  "bg-popup": "#ece5bf",
  "bg-hover": "#c0cbd7",
  "bg-hover-secondary": "#c5d8a2",
  "bg-hl-line": "#ecdfba",
  "bg-paren-match": "#9fd0cc",
  "bg-err": "#f2d4b5",
  "bg-warning": "#e7de80",
  "bg-info": "#cdeeb0",
  "bg-region": "#ddc5af",
  "bg-diff-context": "#e4dbc0", // ef-common mapping resolved
  "bg-tab-bar": "#cec8ae", // ef-common mapping resolved
  "bg-tab-current": "#f1ecd0", // ef-common mapping resolved
  "bg-tab-other": "#aea88e", // ef-common mapping resolved
  "border-mode-line-active": "#7f785f", // ef-common mapping resolved
  "bg-mode-line-inactive": "#cec8ae", // ef-common mapping resolved
  "fg-mode-line-inactive": "#685f53", // ef-common mapping resolved
  "border-mode-line-inactive": "#7f785f", // ef-common mapping resolved
};

const mappings: Mapping = {
  // --- ef-eagle-palette-mappings-partial ---
  err: "red-warmer",
  warning: "yellow-warmer",
  info: "green",
  "fg-link": "yellow-cooler",
  "fg-link-visited": "cyan-faint",
  name: "green",
  keybind: "red-warmer",
  identifier: "cyan-faint",
  "fg-prompt": "yellow-warmer",
  builtin: "yellow-cooler",
  comment: "yellow-faint",
  constant: "green-cooler",
  fnname: "red",
  "fnname-call": "red-faint",
  keyword: "red-faint",
  preprocessor: "red-warmer",
  docstring: "green-faint",
  string: "green-warmer",
  type: "green",
  variable: "cyan",
  "variable-use": "cyan-faint",
  "rx-backslash": "magenta-warmer",
  "rx-construct": "blue-cooler",
  "accent-0": "red",
  "accent-1": "green-cooler",
  "accent-2": "blue",
  "accent-3": "red-warmer",
  "date-common": "red-faint",
  "date-deadline": "red-cooler",
  "date-deadline-subtle": "red",
  "date-event": "fg-alt",
  "date-holiday": "red-warmer",
  "date-now": "fg-main",
  "date-range": "fg-alt",
  "date-scheduled": "yellow-cooler",
  "date-scheduled-subtle": "yellow-faint",
  "date-weekday": "red",
  "date-weekend": "cyan",
  "fg-prose-code": "green-cooler",
  "prose-done": "green-warmer",
  "fg-prose-macro": "blue",
  "prose-metadata": "fg-dim",
  "prose-metadata-value": "fg-alt",
  "prose-table": "fg-alt",
  "prose-table-formula": "warning",
  "prose-tag": "yellow-faint",
  "prose-todo": "red-warmer",
  "fg-prose-verbatim": "red-cooler",
  "mail-cite-0": "red",
  "mail-cite-1": "yellow",
  "mail-cite-2": "green",
  "mail-cite-3": "blue-faint",
  "mail-part": "green-cooler",
  "mail-recipient": "yellow",
  "mail-subject": "red-warmer",
  "mail-other": "yellow-warmer",
  "bg-search-static": "bg-warning",
  "bg-search-current": "bg-yellow-intense",
  "bg-search-lazy": "bg-cyan-intense",
  "bg-search-replace": "bg-red-intense",
  "bg-search-rx-group-0": "bg-magenta-intense",
  "bg-search-rx-group-1": "bg-green-intense",
  "bg-search-rx-group-2": "bg-red-subtle",
  "bg-search-rx-group-3": "bg-cyan-subtle",
  "bg-space-err": "bg-yellow-intense",
  "rainbow-0": "red",
  "rainbow-1": "cyan-faint",
  "rainbow-2": "red-faint",
  "rainbow-3": "green-cooler",
  "rainbow-4": "yellow",
  "rainbow-5": "red-cooler",
  "rainbow-6": "blue-faint",
  "rainbow-7": "yellow-warmer",
  "rainbow-8": "green",

  // --- ef-themes-palette-common (shared across all ef-themes) ---
  fringe: UNSPEC,
  property: "variable",
  "fg-region": UNSPEC,
  "fg-link-symbolic": "fg-alt",
  "underline-link": "border",
  "underline-link-visited": "border",
  "underline-link-symbolic": "border",
  "bg-line-number-active": UNSPEC,
  "fg-line-number-active": "accent-0",
  "bg-line-number-inactive": UNSPEC,
  "bg-prominent-err": "bg-err",
  "bg-prominent-warning": "bg-warning",
  "bg-prominent-note": "bg-info",
  "fg-prominent-err": "err",
  "fg-prominent-warning": "warning",
  "fg-prominent-note": "info",
  "bg-space": UNSPEC,
  "fg-space": "border",
  "bg-active-argument": "bg-warning",
  "fg-active-argument": "warning",
  "bg-active-value": "bg-info",
  "fg-active-value": "info",
  "bg-mark-delete": "bg-err",
  "fg-mark-delete": "err",
  "bg-mark-select": "bg-info",
  "fg-mark-select": "info",
  "bg-mark-other": "bg-warning",
  "fg-mark-other": "warning",
  "fg-search-current": "fg-main",
  "fg-search-lazy": "fg-main",
  "fg-search-static": "fg-main",
  "fg-search-replace": "fg-main",
  "fg-search-rx-group-0": "fg-main",
  "fg-search-rx-group-1": "fg-main",
  "fg-search-rx-group-2": "fg-main",
  "fg-search-rx-group-3": "fg-main",
  "fg-completion-match-0": "accent-0",
  "fg-completion-match-1": "accent-1",
  "fg-completion-match-2": "accent-2",
  "fg-completion-match-3": "accent-3",
  "fg-heading-0": "rainbow-0",
  "fg-heading-1": "rainbow-1",
  "fg-heading-2": "rainbow-2",
  "fg-heading-3": "rainbow-3",
  "fg-heading-4": "rainbow-4",
  "fg-heading-5": "rainbow-5",
  "fg-heading-6": "rainbow-6",
  "fg-heading-7": "rainbow-7",
  "fg-heading-8": "rainbow-8",
};

export const efEagle: ThemeDoc = {
  meta: {
    name: "ef-eagle",
    description: "Legible light beige theme with brown, red, and desatured colors.",
    mode: "light",
  },
  palette,
  mappings,
};
