// ef-elea-dark (dark) — bundled preset, both layers.
//
// The ef-themes are built on top of the modus-themes (since ef-themes 2.0.0):
// they use the same `modus-themes-theme` macro and palette structure. This seed
// is a faithful port so it can be edited and exported as a self-contained
// modus-themes derivative (no ef-themes dependency at load time).
//
// Transcribed verbatim from ef-elea-dark-theme.el + ef-themes.el upstream:
//   - ef-elea-dark-palette-partial            (named colors)
//   - ef-elea-dark-palette-mappings-partial   (theme-specific mappings)
//   - ef-themes-palette-common            (shared mappings, appended)
// To refresh: re-transcribe from https://github.com/protesilaos/ef-themes
//
// A few shared entries (mode-line, tab-bar, bg-diff-context) are layer-1 colors
// in this model but defined upstream as mappings to other named colors; they are
// resolved to hex and placed in the palette block. All other mappings are kept
// symbolic, so resolve.ts follows the indirection as the modus engine does.

import { UNSPECIFIED as UNSPEC } from "./resolve.ts";
import type { Mapping, Palette, ThemeDoc } from "./types.ts";

const palette: Palette = {
  cursor: "#ef7fa8",
  "bg-main": "#222524",
  "bg-dim": "#303332",
  "bg-alt": "#3e4140",
  "fg-main": "#eaf2ef",
  "fg-dim": "#969faf",
  "fg-alt": "#8fcfbb",
  "bg-active": "#5e6160",
  "bg-inactive": "#3b3e3d",
  border: "#5d5f63",
  red: "#ff656a",
  "red-warmer": "#ff7a5f",
  "red-cooler": "#fa7f88",
  "red-faint": "#eba8a8",
  green: "#7fc87f",
  "green-warmer": "#7fca5a",
  "green-cooler": "#50cf89",
  "green-faint": "#a9c99f",
  yellow: "#cac85f",
  "yellow-warmer": "#e0b02f",
  "yellow-cooler": "#cfb27f",
  "yellow-faint": "#cac89f",
  blue: "#57aff6",
  "blue-warmer": "#78afff",
  "blue-cooler": "#62cfef",
  "blue-faint": "#6ab4ef",
  magenta: "#f59acf",
  "magenta-warmer": "#fa90ea",
  "magenta-cooler": "#cfaaff",
  "magenta-faint": "#d0b9f0",
  cyan: "#6fcfd2",
  "cyan-warmer": "#7fcfdf",
  "cyan-cooler": "#60d5c2",
  "cyan-faint": "#99bfcf",
  "bg-red-intense": "#bd1f30",
  "bg-green-intense": "#408420",
  "bg-yellow-intense": "#847020",
  "bg-blue-intense": "#2f5f9f",
  "bg-magenta-intense": "#b05fcf",
  "bg-cyan-intense": "#028099",
  "bg-red-subtle": "#6c2a2a",
  "bg-green-subtle": "#2f532a",
  "bg-yellow-subtle": "#62432a",
  "bg-blue-subtle": "#26486c",
  "bg-magenta-subtle": "#59335b",
  "bg-cyan-subtle": "#204c60",
  "bg-added": "#20493f",
  "bg-added-faint": "#203a2f",
  "bg-added-refine": "#136244",
  "fg-added": "#a0e0a0",
  "bg-changed": "#51512f",
  "bg-changed-faint": "#40332f",
  "bg-changed-refine": "#61621f",
  "fg-changed": "#dada90",
  "bg-removed": "#5e242f",
  "bg-removed-faint": "#4a242a",
  "bg-removed-refine": "#772a35",
  "fg-removed": "#ffbfbf",
  "bg-mode-line-active": "#35605d",
  "fg-mode-line-active": "#ecf0ff",
  "bg-completion": "#37493f",
  "bg-popup": "#2c302f",
  "bg-hover": "#894f7a",
  "bg-hover-secondary": "#425d4a",
  "bg-hl-line": "#2f413f",
  "bg-paren-match": "#3f6f5f",
  "bg-err": "#551525",
  "bg-warning": "#424223",
  "bg-info": "#104420",
  "bg-region": "#543040",
  "bg-diff-context": "#303332", // ef-common mapping resolved
  "bg-tab-bar": "#3e4140", // ef-common mapping resolved
  "bg-tab-current": "#222524", // ef-common mapping resolved
  "bg-tab-other": "#5e6160", // ef-common mapping resolved
  "border-mode-line-active": "#5d5f63", // ef-common mapping resolved
  "bg-mode-line-inactive": "#3e4140", // ef-common mapping resolved
  "fg-mode-line-inactive": "#969faf", // ef-common mapping resolved
  "border-mode-line-inactive": "#5d5f63", // ef-common mapping resolved
};

const mappings: Mapping = {
  // --- ef-elea-dark-palette-mappings-partial ---
  err: "red-warmer",
  warning: "yellow-warmer",
  info: "green-cooler",
  "fg-link": "green-warmer",
  "fg-link-visited": "magenta",
  name: "green",
  keybind: "magenta",
  identifier: "magenta-faint",
  "fg-prompt": "magenta-cooler",
  builtin: "magenta-faint",
  comment: "yellow-faint",
  constant: "magenta-cooler",
  fnname: "green-warmer",
  "fnname-call": "green-faint",
  keyword: "red-faint",
  preprocessor: "magenta-warmer",
  docstring: "cyan-faint",
  string: "green-cooler",
  type: "cyan",
  variable: "magenta",
  "variable-use": "magenta-faint",
  "rx-backslash": "magenta-cooler",
  "rx-construct": "red",
  "accent-0": "green-cooler",
  "accent-1": "magenta",
  "accent-2": "magenta-cooler",
  "accent-3": "blue-warmer",
  "date-common": "green-cooler",
  "date-deadline": "red",
  "date-deadline-subtle": "red-faint",
  "date-event": "fg-alt",
  "date-holiday": "magenta-warmer",
  "date-now": "fg-main",
  "date-range": "fg-alt",
  "date-scheduled": "yellow",
  "date-scheduled-subtle": "yellow-faint",
  "date-weekday": "cyan-cooler",
  "date-weekend": "red-faint",
  "fg-prose-code": "magenta",
  "prose-done": "green-warmer",
  "fg-prose-macro": "magenta-cooler",
  "prose-metadata": "fg-dim",
  "prose-metadata-value": "fg-alt",
  "prose-table": "fg-alt",
  "prose-table-formula": "err",
  "prose-tag": "cyan-faint",
  "prose-todo": "red-warmer",
  "fg-prose-verbatim": "cyan-cooler",
  "mail-cite-0": "cyan-cooler",
  "mail-cite-1": "magenta",
  "mail-cite-2": "green-warmer",
  "mail-cite-3": "magenta-cooler",
  "mail-part": "yellow-cooler",
  "mail-recipient": "red-faint",
  "mail-subject": "green-cooler",
  "mail-other": "green",
  "bg-search-static": "bg-warning",
  "bg-search-current": "bg-yellow-intense",
  "bg-search-lazy": "bg-blue-intense",
  "bg-search-replace": "bg-red-intense",
  "bg-search-rx-group-0": "bg-magenta-intense",
  "bg-search-rx-group-1": "bg-green-intense",
  "bg-search-rx-group-2": "bg-red-subtle",
  "bg-search-rx-group-3": "bg-cyan-subtle",
  "bg-space-err": "bg-yellow-intense",
  "rainbow-0": "green-warmer",
  "rainbow-1": "red-faint",
  "rainbow-2": "green-faint",
  "rainbow-3": "cyan-cooler",
  "rainbow-4": "magenta-cooler",
  "rainbow-5": "magenta",
  "rainbow-6": "green",
  "rainbow-7": "yellow-cooler",
  "rainbow-8": "blue-faint",

  // --- ef-themes-palette-common (shared across all ef-themes) ---
  fringe: UNSPEC,
  property: "variable",
  "fg-region": UNSPEC,
  "fg-link-symbolic": "fg-alt",
  "underline-link": "border",
  "underline-link-visited": "border",
  "underline-link-symbolic": "border",
  "bg-line-number-active": UNSPEC,
  "fg-line-number-active": "accent-0",
  "bg-line-number-inactive": UNSPEC,
  "bg-prominent-err": "bg-err",
  "bg-prominent-warning": "bg-warning",
  "bg-prominent-note": "bg-info",
  "fg-prominent-err": "err",
  "fg-prominent-warning": "warning",
  "fg-prominent-note": "info",
  "bg-space": UNSPEC,
  "fg-space": "border",
  "bg-active-argument": "bg-warning",
  "fg-active-argument": "warning",
  "bg-active-value": "bg-info",
  "fg-active-value": "info",
  "bg-mark-delete": "bg-err",
  "fg-mark-delete": "err",
  "bg-mark-select": "bg-info",
  "fg-mark-select": "info",
  "bg-mark-other": "bg-warning",
  "fg-mark-other": "warning",
  "fg-search-current": "fg-main",
  "fg-search-lazy": "fg-main",
  "fg-search-static": "fg-main",
  "fg-search-replace": "fg-main",
  "fg-search-rx-group-0": "fg-main",
  "fg-search-rx-group-1": "fg-main",
  "fg-search-rx-group-2": "fg-main",
  "fg-search-rx-group-3": "fg-main",
  "fg-completion-match-0": "accent-0",
  "fg-completion-match-1": "accent-1",
  "fg-completion-match-2": "accent-2",
  "fg-completion-match-3": "accent-3",
  "fg-heading-0": "rainbow-0",
  "fg-heading-1": "rainbow-1",
  "fg-heading-2": "rainbow-2",
  "fg-heading-3": "rainbow-3",
  "fg-heading-4": "rainbow-4",
  "fg-heading-5": "rainbow-5",
  "fg-heading-6": "rainbow-6",
  "fg-heading-7": "rainbow-7",
  "fg-heading-8": "rainbow-8",
};

export const efEleaDark: ThemeDoc = {
  meta: {
    name: "ef-elea-dark",
    description: "Legible dark green theme with brown, magenta, and green colors.",
    mode: "dark",
  },
  palette,
  mappings,
};
