// ef-fig (dark) — bundled preset, both layers.
//
// The ef-themes are built on top of the modus-themes (since ef-themes 2.0.0):
// they use the same `modus-themes-theme` macro and palette structure. This seed
// is a faithful port so it can be edited and exported as a self-contained
// modus-themes derivative (no ef-themes dependency at load time).
//
// Transcribed verbatim from ef-fig-theme.el + ef-themes.el upstream:
//   - ef-fig-palette-partial            (named colors)
//   - ef-fig-palette-mappings-partial   (theme-specific mappings)
//   - ef-themes-palette-common            (shared mappings, appended)
// To refresh: re-transcribe from https://github.com/protesilaos/ef-themes
//
// A few shared entries (mode-line, tab-bar, bg-diff-context) are layer-1 colors
// in this model but defined upstream as mappings to other named colors; they are
// resolved to hex and placed in the palette block. All other mappings are kept
// symbolic, so resolve.ts follows the indirection as the modus engine does.

import { UNSPECIFIED as UNSPEC } from "./resolve.ts";
import type { Mapping, Palette, ThemeDoc } from "./types.ts";

const palette: Palette = {
  cursor: "#e0646a",
  "bg-main": "#3b2043",
  "bg-dim": "#432e4e",
  "bg-alt": "#4a385e",
  "fg-main": "#e4d3e1",
  "fg-dim": "#9d9d9d",
  "fg-alt": "#c6a4cf",
  "bg-active": "#6a586e",
  "bg-inactive": "#4a384e",
  border: "#796f6e",
  red: "#ef797f",
  "red-warmer": "#ff7f5f",
  "red-cooler": "#e088af",
  "red-faint": "#e89f84",
  green: "#7fbb3f",
  "green-warmer": "#aad05a",
  "green-cooler": "#79d081",
  "green-faint": "#a2b799",
  yellow: "#e4c53f",
  "yellow-warmer": "#f2a85f",
  "yellow-cooler": "#eec27f",
  "yellow-faint": "#d8c09f",
  blue: "#57aff6",
  "blue-warmer": "#78b2ff",
  "blue-cooler": "#62cff7",
  "blue-faint": "#9fbfdf",
  magenta: "#ffb2d6",
  "magenta-warmer": "#f28fdf",
  "magenta-cooler": "#afb1ff",
  "magenta-faint": "#c59fcf",
  cyan: "#5fc0dc",
  "cyan-warmer": "#7fc5df",
  "cyan-cooler": "#80dfbf",
  "cyan-faint": "#99bfcf",
  "bg-red-intense": "#b23f30",
  "bg-green-intense": "#506430",
  "bg-yellow-intense": "#847020",
  "bg-blue-intense": "#2f5f9f",
  "bg-magenta-intense": "#704fbf",
  "bg-cyan-intense": "#028099",
  "bg-red-subtle": "#772c2a",
  "bg-green-subtle": "#3f512f",
  "bg-yellow-subtle": "#634627",
  "bg-blue-subtle": "#424075",
  "bg-magenta-subtle": "#6b3c52",
  "bg-cyan-subtle": "#3f4e72",
  "bg-added": "#3a472f",
  "bg-added-faint": "#37382f",
  "bg-added-refine": "#3d6034",
  "fg-added": "#a0e0a0",
  "bg-changed": "#51512f",
  "bg-changed-faint": "#40332f",
  "bg-changed-refine": "#65641f",
  "fg-changed": "#dada90",
  "bg-removed": "#5f2f2f",
  "bg-removed-faint": "#4f283a",
  "bg-removed-refine": "#7e3635",
  "fg-removed": "#ffbfbf",
  "bg-mode-line-active": "#57602e",
  "fg-mode-line-active": "#c8c597",
  "bg-completion": "#52436f",
  "bg-popup": "#472651",
  "bg-hover": "#7f5a60",
  "bg-hover-secondary": "#6a4f6f",
  "bg-hl-line": "#47275f",
  "bg-paren-match": "#3e592f",
  "bg-err": "#552407",
  "bg-warning": "#55421e",
  "bg-info": "#3e4200",
  "bg-region": "#643270",
  "bg-diff-context": "#432e4e", // ef-common mapping resolved
  "bg-tab-bar": "#4a385e", // ef-common mapping resolved
  "bg-tab-current": "#3b2043", // ef-common mapping resolved
  "bg-tab-other": "#6a586e", // ef-common mapping resolved
  "border-mode-line-active": "#796f6e", // ef-common mapping resolved
  "bg-mode-line-inactive": "#4a385e", // ef-common mapping resolved
  "fg-mode-line-inactive": "#9d9d9d", // ef-common mapping resolved
  "border-mode-line-inactive": "#796f6e", // ef-common mapping resolved
};

const mappings: Mapping = {
  // --- ef-fig-palette-mappings-partial ---
  err: "red",
  warning: "yellow",
  info: "green",
  "fg-link": "magenta",
  "fg-link-visited": "magenta-cooler",
  name: "green-warmer",
  keybind: "green",
  identifier: "red-faint",
  "fg-prompt": "green-cooler",
  builtin: "magenta",
  comment: "fg-dim",
  constant: "magenta-cooler",
  fnname: "yellow-cooler",
  "fnname-call": "red-faint",
  keyword: "green-warmer",
  preprocessor: "red-warmer",
  docstring: "magenta-faint",
  string: "red-cooler",
  type: "green-cooler",
  variable: "yellow-warmer",
  "variable-use": "yellow-faint",
  "rx-backslash": "yellow-cooler",
  "rx-construct": "red-warmer",
  "accent-0": "green-warmer",
  "accent-1": "magenta-warmer",
  "accent-2": "yellow-warmer",
  "accent-3": "red",
  "date-common": "yellow-faint",
  "date-deadline": "magenta-warmer",
  "date-deadline-subtle": "red-faint",
  "date-event": "fg-alt",
  "date-holiday": "red-warmer",
  "date-now": "fg-main",
  "date-range": "fg-alt",
  "date-scheduled": "yellow-warmer",
  "date-scheduled-subtle": "yellow-faint",
  "date-weekday": "yellow-cooler",
  "date-weekend": "red",
  "fg-prose-code": "green-cooler",
  "prose-done": "green",
  "fg-prose-macro": "red-cooler",
  "prose-metadata": "fg-dim",
  "prose-metadata-value": "fg-alt",
  "prose-table": "fg-alt",
  "prose-table-formula": "info",
  "prose-tag": "green-faint",
  "prose-todo": "red",
  "fg-prose-verbatim": "yellow-warmer",
  "mail-cite-0": "green-warmer",
  "mail-cite-1": "yellow-cooler",
  "mail-cite-2": "cyan-faint",
  "mail-cite-3": "magenta-warmer",
  "mail-part": "yellow-faint",
  "mail-recipient": "red-cooler",
  "mail-subject": "green",
  "mail-other": "magenta-cooler",
  "bg-search-static": "bg-warning",
  "bg-search-current": "bg-yellow-intense",
  "bg-search-lazy": "bg-magenta-intense",
  "bg-search-replace": "bg-red-intense",
  "bg-search-rx-group-0": "bg-green-intense",
  "bg-search-rx-group-1": "bg-yellow-intense",
  "bg-search-rx-group-2": "bg-magenta-subtle",
  "bg-search-rx-group-3": "bg-cyan-subtle",
  "bg-space-err": "bg-red-intense",
  "rainbow-0": "magenta",
  "rainbow-1": "green-warmer",
  "rainbow-2": "yellow-cooler",
  "rainbow-3": "magenta-cooler",
  "rainbow-4": "green-cooler",
  "rainbow-5": "red-cooler",
  "rainbow-6": "cyan-cooler",
  "rainbow-7": "yellow-warmer",
  "rainbow-8": "magenta-warmer",

  // --- ef-themes-palette-common (shared across all ef-themes) ---
  fringe: UNSPEC,
  property: "variable",
  "fg-region": UNSPEC,
  "fg-link-symbolic": "fg-alt",
  "underline-link": "border",
  "underline-link-visited": "border",
  "underline-link-symbolic": "border",
  "bg-line-number-active": UNSPEC,
  "fg-line-number-active": "accent-0",
  "bg-line-number-inactive": UNSPEC,
  "bg-prominent-err": "bg-err",
  "bg-prominent-warning": "bg-warning",
  "bg-prominent-note": "bg-info",
  "fg-prominent-err": "err",
  "fg-prominent-warning": "warning",
  "fg-prominent-note": "info",
  "bg-space": UNSPEC,
  "fg-space": "border",
  "bg-active-argument": "bg-warning",
  "fg-active-argument": "warning",
  "bg-active-value": "bg-info",
  "fg-active-value": "info",
  "bg-mark-delete": "bg-err",
  "fg-mark-delete": "err",
  "bg-mark-select": "bg-info",
  "fg-mark-select": "info",
  "bg-mark-other": "bg-warning",
  "fg-mark-other": "warning",
  "fg-search-current": "fg-main",
  "fg-search-lazy": "fg-main",
  "fg-search-static": "fg-main",
  "fg-search-replace": "fg-main",
  "fg-search-rx-group-0": "fg-main",
  "fg-search-rx-group-1": "fg-main",
  "fg-search-rx-group-2": "fg-main",
  "fg-search-rx-group-3": "fg-main",
  "fg-completion-match-0": "accent-0",
  "fg-completion-match-1": "accent-1",
  "fg-completion-match-2": "accent-2",
  "fg-completion-match-3": "accent-3",
  "fg-heading-0": "rainbow-0",
  "fg-heading-1": "rainbow-1",
  "fg-heading-2": "rainbow-2",
  "fg-heading-3": "rainbow-3",
  "fg-heading-4": "rainbow-4",
  "fg-heading-5": "rainbow-5",
  "fg-heading-6": "rainbow-6",
  "fg-heading-7": "rainbow-7",
  "fg-heading-8": "rainbow-8",
};

export const efFig: ThemeDoc = {
  meta: {
    name: "ef-fig",
    description: "Legible dark theme with warm green, yellow, and magenta colors.",
    mode: "dark",
  },
  palette,
  mappings,
};
