// ef-frost (light) — bundled preset, both layers.
//
// The ef-themes are built on top of the modus-themes (since ef-themes 2.0.0):
// they use the same `modus-themes-theme` macro and palette structure. This seed
// is a faithful port so it can be edited and exported as a self-contained
// modus-themes derivative (no ef-themes dependency at load time).
//
// Transcribed verbatim from ef-frost-theme.el + ef-themes.el upstream:
//   - ef-frost-palette-partial            (named colors)
//   - ef-frost-palette-mappings-partial   (theme-specific mappings)
//   - ef-themes-palette-common            (shared mappings, appended)
// To refresh: re-transcribe from https://github.com/protesilaos/ef-themes
//
// A few shared entries (mode-line, tab-bar, bg-diff-context) are layer-1 colors
// in this model but defined upstream as mappings to other named colors; they are
// resolved to hex and placed in the palette block. All other mappings are kept
// symbolic, so resolve.ts follows the indirection as the modus engine does.

import { UNSPECIFIED as UNSPEC } from "./resolve.ts";
import type { Mapping, Palette, ThemeDoc } from "./types.ts";

const palette: Palette = {
  cursor: "#0055bb",
  "bg-main": "#fcffff",
  "bg-dim": "#eaefef",
  "bg-alt": "#d7dbdb",
  "fg-main": "#232323",
  "fg-dim": "#66657f",
  "fg-alt": "#204f9a",
  "bg-active": "#b5b8b8",
  "bg-inactive": "#ecf0f0",
  border: "#b0b7c0",
  red: "#c42d2f",
  "red-warmer": "#d03003",
  "red-cooler": "#cf2f4f",
  "red-faint": "#9a4366",
  green: "#008a00",
  "green-warmer": "#468400",
  "green-cooler": "#00845f",
  "green-faint": "#517f3c",
  yellow: "#aa6100",
  "yellow-warmer": "#b6532f",
  "yellow-cooler": "#996c4f",
  "yellow-faint": "#7a5f2f",
  blue: "#004fc0",
  "blue-warmer": "#4244ef",
  "blue-cooler": "#065fff",
  "blue-faint": "#375cc8",
  magenta: "#aa44c5",
  "magenta-warmer": "#c0469a",
  "magenta-cooler": "#7f5ae0",
  "magenta-faint": "#605f9f",
  cyan: "#1f6fbf",
  "cyan-warmer": "#3a6dd2",
  "cyan-cooler": "#007a85",
  "cyan-faint": "#305f9f",
  "bg-red-intense": "#ff8f88",
  "bg-green-intense": "#8adf90",
  "bg-yellow-intense": "#fac200",
  "bg-blue-intense": "#cbcfff",
  "bg-magenta-intense": "#df8fff",
  "bg-cyan-intense": "#88c8ff",
  "bg-red-subtle": "#ffcbdf",
  "bg-green-subtle": "#b3f6d0",
  "bg-yellow-subtle": "#f0f48f",
  "bg-blue-subtle": "#baeeff",
  "bg-magenta-subtle": "#f0ddff",
  "bg-cyan-subtle": "#c2eff2",
  "bg-added": "#c9ffea",
  "bg-added-faint": "#d7fff5",
  "bg-added-refine": "#b3efdf",
  "fg-added": "#004840",
  "bg-changed": "#f4e8bd",
  "bg-changed-faint": "#f9efcb",
  "bg-changed-refine": "#efd299",
  "fg-changed": "#553d00",
  "bg-removed": "#ffd6e0",
  "bg-removed-faint": "#ffe9e6",
  "bg-removed-refine": "#f5bfc8",
  "fg-removed": "#8f1313",
  "bg-mode-line-active": "#9ad0ff",
  "fg-mode-line-active": "#051524",
  "bg-completion": "#cce7f5",
  "bg-popup": "#eff3f3",
  "bg-hover": "#eab5ff",
  "bg-hover-secondary": "#aae0bf",
  "bg-hl-line": "#dff6e4",
  "bg-paren-match": "#cab0ef",
  "bg-err": "#ffdfda",
  "bg-warning": "#ffe9bf",
  "bg-info": "#ccefcf",
  "bg-region": "#d4eaf3",
  "bg-diff-context": "#eaefef", // ef-common mapping resolved
  "bg-tab-bar": "#d7dbdb", // ef-common mapping resolved
  "bg-tab-current": "#fcffff", // ef-common mapping resolved
  "bg-tab-other": "#b5b8b8", // ef-common mapping resolved
  "border-mode-line-active": "#b0b7c0", // ef-common mapping resolved
  "bg-mode-line-inactive": "#d7dbdb", // ef-common mapping resolved
  "fg-mode-line-inactive": "#66657f", // ef-common mapping resolved
  "border-mode-line-inactive": "#b0b7c0", // ef-common mapping resolved
};

const mappings: Mapping = {
  // --- ef-frost-palette-mappings-partial ---
  err: "red",
  warning: "yellow-cooler",
  info: "green",
  "fg-link": "cyan",
  "fg-link-visited": "magenta",
  name: "cyan-warmer",
  keybind: "blue-cooler",
  identifier: "magenta-faint",
  "fg-prompt": "cyan",
  builtin: "cyan",
  comment: "yellow-faint",
  constant: "blue-cooler",
  fnname: "green-cooler",
  "fnname-call": "green-faint",
  keyword: "blue",
  preprocessor: "magenta",
  docstring: "magenta-faint",
  string: "blue-warmer",
  type: "magenta-cooler",
  variable: "cyan-warmer",
  "variable-use": "cyan-faint",
  "rx-backslash": "yellow-cooler",
  "rx-construct": "red-cooler",
  "accent-0": "blue-warmer",
  "accent-1": "green-cooler",
  "accent-2": "magenta-warmer",
  "accent-3": "blue-cooler",
  "date-common": "cyan-cooler",
  "date-deadline": "red",
  "date-deadline-subtle": "red-faint",
  "date-event": "fg-alt",
  "date-holiday": "magenta-warmer",
  "date-now": "fg-main",
  "date-range": "fg-alt",
  "date-scheduled": "yellow-cooler",
  "date-scheduled-subtle": "yellow-faint",
  "date-weekday": "cyan",
  "date-weekend": "red-faint",
  "fg-prose-code": "green-cooler",
  "prose-done": "green",
  "fg-prose-macro": "magenta-warmer",
  "prose-metadata": "fg-dim",
  "prose-metadata-value": "fg-alt",
  "prose-table": "fg-alt",
  "prose-table-formula": "warning",
  "prose-tag": "yellow-faint",
  "prose-todo": "red",
  "fg-prose-verbatim": "blue-warmer",
  "mail-cite-0": "blue",
  "mail-cite-1": "cyan-cooler",
  "mail-cite-2": "yellow-cooler",
  "mail-cite-3": "magenta-cooler",
  "mail-part": "cyan",
  "mail-recipient": "cyan-warmer",
  "mail-subject": "blue-cooler",
  "mail-other": "cyan",
  "bg-search-static": "bg-warning",
  "bg-search-current": "bg-yellow-intense",
  "bg-search-lazy": "bg-blue-intense",
  "bg-search-replace": "bg-red-intense",
  "bg-search-rx-group-0": "bg-magenta-intense",
  "bg-search-rx-group-1": "bg-green-intense",
  "bg-search-rx-group-2": "bg-red-subtle",
  "bg-search-rx-group-3": "bg-cyan-subtle",
  "bg-space-err": "bg-yellow-intense",
  "rainbow-0": "cyan-cooler",
  "rainbow-1": "blue",
  "rainbow-2": "green-cooler",
  "rainbow-3": "magenta-cooler",
  "rainbow-4": "cyan",
  "rainbow-5": "blue-cooler",
  "rainbow-6": "green-warmer",
  "rainbow-7": "magenta",
  "rainbow-8": "cyan-warmer",

  // --- ef-themes-palette-common (shared across all ef-themes) ---
  fringe: UNSPEC,
  property: "variable",
  "fg-region": UNSPEC,
  "fg-link-symbolic": "fg-alt",
  "underline-link": "border",
  "underline-link-visited": "border",
  "underline-link-symbolic": "border",
  "bg-line-number-active": UNSPEC,
  "fg-line-number-active": "accent-0",
  "bg-line-number-inactive": UNSPEC,
  "bg-prominent-err": "bg-err",
  "bg-prominent-warning": "bg-warning",
  "bg-prominent-note": "bg-info",
  "fg-prominent-err": "err",
  "fg-prominent-warning": "warning",
  "fg-prominent-note": "info",
  "bg-space": UNSPEC,
  "fg-space": "border",
  "bg-active-argument": "bg-warning",
  "fg-active-argument": "warning",
  "bg-active-value": "bg-info",
  "fg-active-value": "info",
  "bg-mark-delete": "bg-err",
  "fg-mark-delete": "err",
  "bg-mark-select": "bg-info",
  "fg-mark-select": "info",
  "bg-mark-other": "bg-warning",
  "fg-mark-other": "warning",
  "fg-search-current": "fg-main",
  "fg-search-lazy": "fg-main",
  "fg-search-static": "fg-main",
  "fg-search-replace": "fg-main",
  "fg-search-rx-group-0": "fg-main",
  "fg-search-rx-group-1": "fg-main",
  "fg-search-rx-group-2": "fg-main",
  "fg-search-rx-group-3": "fg-main",
  "fg-completion-match-0": "accent-0",
  "fg-completion-match-1": "accent-1",
  "fg-completion-match-2": "accent-2",
  "fg-completion-match-3": "accent-3",
  "fg-heading-0": "rainbow-0",
  "fg-heading-1": "rainbow-1",
  "fg-heading-2": "rainbow-2",
  "fg-heading-3": "rainbow-3",
  "fg-heading-4": "rainbow-4",
  "fg-heading-5": "rainbow-5",
  "fg-heading-6": "rainbow-6",
  "fg-heading-7": "rainbow-7",
  "fg-heading-8": "rainbow-8",
};

export const efFrost: ThemeDoc = {
  meta: {
    name: "ef-frost",
    description: "Legible light cool theme with blue, cyan, teal, purple colors.",
    mode: "light",
  },
  palette,
  mappings,
};
