// ef-light (light) — bundled preset, both layers.
//
// The ef-themes are built on top of the modus-themes (since ef-themes 2.0.0):
// they use the same `modus-themes-theme` macro and palette structure. This seed
// is a faithful port so it can be edited and exported as a self-contained
// modus-themes derivative (no ef-themes dependency at load time).
//
// Transcribed verbatim from ef-light-theme.el + ef-themes.el upstream:
//   - ef-light-palette-partial            (named colors)
//   - ef-light-palette-mappings-partial   (theme-specific mappings)
//   - ef-themes-palette-common            (shared mappings, appended)
// To refresh: re-transcribe from https://github.com/protesilaos/ef-themes
//
// A few shared entries (mode-line, tab-bar, bg-diff-context) are layer-1 colors
// in this model but defined upstream as mappings to other named colors; they are
// resolved to hex and placed in the palette block. All other mappings are kept
// symbolic, so resolve.ts follows the indirection as the modus engine does.

import { UNSPECIFIED as UNSPEC } from "./resolve.ts";
import type { Mapping, Palette, ThemeDoc } from "./types.ts";

const palette: Palette = {
  cursor: "#0033cc",
  "bg-main": "#ffffff",
  "bg-dim": "#efefef",
  "bg-alt": "#dbdbdb",
  "fg-main": "#202020",
  "fg-dim": "#68759f",
  "fg-alt": "#397a70",
  "bg-active": "#b3b3b3",
  "bg-inactive": "#f0f0f0",
  border: "#bfc4da",
  red: "#d3303a",
  "red-warmer": "#e00033",
  "red-cooler": "#d51272",
  "red-faint": "#c24552",
  green: "#217a3c",
  "green-warmer": "#4a7d00",
  "green-cooler": "#008858",
  "green-faint": "#61756c",
  yellow: "#a45f22",
  "yellow-warmer": "#b6532f",
  "yellow-cooler": "#b65050",
  "yellow-faint": "#a65f6a",
  blue: "#3740cf",
  "blue-warmer": "#4250ef",
  "blue-cooler": "#065fff",
  "blue-faint": "#4f54aa",
  magenta: "#ba35af",
  "magenta-warmer": "#cf25aa",
  "magenta-cooler": "#6052cf",
  "magenta-faint": "#af5a80",
  cyan: "#1f6fbf",
  "cyan-warmer": "#3f6faf",
  "cyan-cooler": "#1f77bb",
  "cyan-faint": "#506fa0",
  "bg-red-intense": "#ff8f88",
  "bg-green-intense": "#9adf90",
  "bg-yellow-intense": "#fac200",
  "bg-blue-intense": "#cbcfff",
  "bg-magenta-intense": "#df8fff",
  "bg-cyan-intense": "#88c8ff",
  "bg-red-subtle": "#ffcfbf",
  "bg-green-subtle": "#b3fabf",
  "bg-yellow-subtle": "#fff576",
  "bg-blue-subtle": "#ccdfff",
  "bg-magenta-subtle": "#ffddff",
  "bg-cyan-subtle": "#bfefff",
  "bg-added": "#d0f0d0",
  "bg-added-faint": "#e5ffe5",
  "bg-added-refine": "#b2e8be",
  "fg-added": "#005000",
  "bg-changed": "#f4e8bd",
  "bg-changed-faint": "#f9efcb",
  "bg-changed-refine": "#efd299",
  "fg-changed": "#553d00",
  "bg-removed": "#ffd8d5",
  "bg-removed-faint": "#ffe9e9",
  "bg-removed-refine": "#f3b5af",
  "fg-removed": "#8f1313",
  "bg-mode-line-active": "#b7c7ff",
  "fg-mode-line-active": "#151515",
  "bg-completion": "#bfe8ff",
  "bg-popup": "#f3f3f3",
  "bg-hover": "#aaeccf",
  "bg-hover-secondary": "#ccbfff",
  "bg-hl-line": "#e4efd8",
  "bg-paren-match": "#dfa0f3",
  "bg-err": "#ffd5ea",
  "bg-warning": "#ffeabb",
  "bg-info": "#d0efda",
  "bg-region": "#bfefff",
  "bg-diff-context": "#efefef", // ef-common mapping resolved
  "bg-tab-bar": "#dbdbdb", // ef-common mapping resolved
  "bg-tab-current": "#ffffff", // ef-common mapping resolved
  "bg-tab-other": "#b3b3b3", // ef-common mapping resolved
  "border-mode-line-active": "#bfc4da", // ef-common mapping resolved
  "bg-mode-line-inactive": "#dbdbdb", // ef-common mapping resolved
  "fg-mode-line-inactive": "#68759f", // ef-common mapping resolved
  "border-mode-line-inactive": "#bfc4da", // ef-common mapping resolved
};

const mappings: Mapping = {
  // --- ef-light-palette-mappings-partial ---
  err: "red-warmer",
  warning: "yellow-warmer",
  info: "green",
  "fg-link": "blue-warmer",
  "fg-link-visited": "magenta",
  name: "magenta-cooler",
  keybind: "blue-cooler",
  identifier: "magenta-faint",
  "fg-prompt": "green-cooler",
  builtin: "magenta",
  comment: "yellow-faint",
  constant: "blue-cooler",
  fnname: "magenta-warmer",
  "fnname-call": "magenta-faint",
  keyword: "magenta-cooler",
  preprocessor: "red",
  docstring: "cyan-faint",
  string: "blue-warmer",
  type: "green-cooler",
  variable: "cyan-cooler",
  "variable-use": "cyan-faint",
  "rx-backslash": "green-cooler",
  "rx-construct": "magenta",
  "accent-0": "blue-warmer",
  "accent-1": "magenta-warmer",
  "accent-2": "green-cooler",
  "accent-3": "yellow-warmer",
  "date-common": "cyan-cooler",
  "date-deadline": "red",
  "date-deadline-subtle": "red-cooler",
  "date-event": "fg-alt",
  "date-holiday": "magenta-warmer",
  "date-now": "fg-main",
  "date-range": "fg-alt",
  "date-scheduled": "yellow",
  "date-scheduled-subtle": "yellow-faint",
  "date-weekday": "cyan",
  "date-weekend": "red-faint",
  "fg-prose-code": "magenta-warmer",
  "prose-done": "green",
  "fg-prose-macro": "green-cooler",
  "prose-metadata": "fg-dim",
  "prose-metadata-value": "fg-alt",
  "prose-table": "fg-alt",
  "prose-table-formula": "err",
  "prose-tag": "green-faint",
  "prose-todo": "red-warmer",
  "fg-prose-verbatim": "blue-warmer",
  "mail-cite-0": "blue-warmer",
  "mail-cite-1": "magenta",
  "mail-cite-2": "cyan-cooler",
  "mail-cite-3": "yellow-cooler",
  "mail-part": "cyan-warmer",
  "mail-recipient": "magenta-cooler",
  "mail-subject": "blue-cooler",
  "mail-other": "cyan",
  "bg-search-static": "bg-warning",
  "bg-search-current": "bg-yellow-intense",
  "bg-search-lazy": "bg-blue-intense",
  "bg-search-replace": "bg-red-intense",
  "bg-search-rx-group-0": "bg-magenta-intense",
  "bg-search-rx-group-1": "bg-green-intense",
  "bg-search-rx-group-2": "bg-red-subtle",
  "bg-search-rx-group-3": "bg-cyan-subtle",
  "bg-space-err": "bg-yellow-intense",
  "rainbow-0": "green-cooler",
  "rainbow-1": "blue-faint",
  "rainbow-2": "magenta",
  "rainbow-3": "cyan-cooler",
  "rainbow-4": "yellow-cooler",
  "rainbow-5": "blue-warmer",
  "rainbow-6": "green-cooler",
  "rainbow-7": "magenta-cooler",
  "rainbow-8": "yellow",

  // --- ef-themes-palette-common (shared across all ef-themes) ---
  fringe: UNSPEC,
  property: "variable",
  "fg-region": UNSPEC,
  "fg-link-symbolic": "fg-alt",
  "underline-link": "border",
  "underline-link-visited": "border",
  "underline-link-symbolic": "border",
  "bg-line-number-active": UNSPEC,
  "fg-line-number-active": "accent-0",
  "bg-line-number-inactive": UNSPEC,
  "bg-prominent-err": "bg-err",
  "bg-prominent-warning": "bg-warning",
  "bg-prominent-note": "bg-info",
  "fg-prominent-err": "err",
  "fg-prominent-warning": "warning",
  "fg-prominent-note": "info",
  "bg-space": UNSPEC,
  "fg-space": "border",
  "bg-active-argument": "bg-warning",
  "fg-active-argument": "warning",
  "bg-active-value": "bg-info",
  "fg-active-value": "info",
  "bg-mark-delete": "bg-err",
  "fg-mark-delete": "err",
  "bg-mark-select": "bg-info",
  "fg-mark-select": "info",
  "bg-mark-other": "bg-warning",
  "fg-mark-other": "warning",
  "fg-search-current": "fg-main",
  "fg-search-lazy": "fg-main",
  "fg-search-static": "fg-main",
  "fg-search-replace": "fg-main",
  "fg-search-rx-group-0": "fg-main",
  "fg-search-rx-group-1": "fg-main",
  "fg-search-rx-group-2": "fg-main",
  "fg-search-rx-group-3": "fg-main",
  "fg-completion-match-0": "accent-0",
  "fg-completion-match-1": "accent-1",
  "fg-completion-match-2": "accent-2",
  "fg-completion-match-3": "accent-3",
  "fg-heading-0": "rainbow-0",
  "fg-heading-1": "rainbow-1",
  "fg-heading-2": "rainbow-2",
  "fg-heading-3": "rainbow-3",
  "fg-heading-4": "rainbow-4",
  "fg-heading-5": "rainbow-5",
  "fg-heading-6": "rainbow-6",
  "fg-heading-7": "rainbow-7",
  "fg-heading-8": "rainbow-8",
};

export const efLight: ThemeDoc = {
  meta: {
    name: "ef-light",
    description: "Legible light theme with blue, magenta, cyan, purple colors.",
    mode: "light",
  },
  palette,
  mappings,
};
