// ef-maris-dark (dark) — bundled preset, both layers.
//
// The ef-themes are built on top of the modus-themes (since ef-themes 2.0.0):
// they use the same `modus-themes-theme` macro and palette structure. This seed
// is a faithful port so it can be edited and exported as a self-contained
// modus-themes derivative (no ef-themes dependency at load time).
//
// Transcribed verbatim from ef-maris-dark-theme.el + ef-themes.el upstream:
//   - ef-maris-dark-palette-partial            (named colors)
//   - ef-maris-dark-palette-mappings-partial   (theme-specific mappings)
//   - ef-themes-palette-common            (shared mappings, appended)
// To refresh: re-transcribe from https://github.com/protesilaos/ef-themes
//
// A few shared entries (mode-line, tab-bar, bg-diff-context) are layer-1 colors
// in this model but defined upstream as mappings to other named colors; they are
// resolved to hex and placed in the palette block. All other mappings are kept
// symbolic, so resolve.ts follows the indirection as the modus engine does.

import { UNSPECIFIED as UNSPEC } from "./resolve.ts";
import type { Mapping, Palette, ThemeDoc } from "./types.ts";

const palette: Palette = {
  cursor: "#8fdfff",
  "bg-main": "#131c2b",
  "bg-dim": "#1d2c39",
  "bg-alt": "#2a3644",
  "fg-main": "#eaedef",
  "fg-dim": "#969faf",
  "fg-alt": "#90a0dc",
  "bg-active": "#4a5664",
  "bg-inactive": "#2a3341",
  border: "#595a63",
  red: "#ff6f6f",
  "red-warmer": "#ff7a5f",
  "red-cooler": "#ff7788",
  "red-faint": "#eaa4a4",
  green: "#41bf4f",
  "green-warmer": "#7fce5f",
  "green-cooler": "#30c489",
  "green-faint": "#a9c99f",
  yellow: "#d0d24f",
  "yellow-warmer": "#f0c060",
  "yellow-cooler": "#cab27f",
  "yellow-faint": "#cac89f",
  blue: "#57b0ff",
  "blue-warmer": "#70a0ff",
  "blue-cooler": "#12b4ff",
  "blue-faint": "#9acfff",
  magenta: "#f59acf",
  "magenta-warmer": "#fa90ea",
  "magenta-cooler": "#cf90ff",
  "magenta-faint": "#d4aaf0",
  cyan: "#2fd0db",
  "cyan-warmer": "#7fcfdf",
  "cyan-cooler": "#65d5a8",
  "cyan-faint": "#99bfcf",
  "bg-red-intense": "#bd1f30",
  "bg-green-intense": "#107840",
  "bg-yellow-intense": "#847020",
  "bg-blue-intense": "#2f5f9f",
  "bg-magenta-intense": "#b05fcf",
  "bg-cyan-intense": "#0280b9",
  "bg-red-subtle": "#6f293a",
  "bg-green-subtle": "#1f523a",
  "bg-yellow-subtle": "#604233",
  "bg-blue-subtle": "#284477",
  "bg-magenta-subtle": "#52336b",
  "bg-cyan-subtle": "#204c68",
  "bg-added": "#20493f",
  "bg-added-faint": "#163530",
  "bg-added-refine": "#136244",
  "fg-added": "#a0e0a0",
  "bg-changed": "#51512f",
  "bg-changed-faint": "#40332f",
  "bg-changed-refine": "#61621f",
  "fg-changed": "#dada90",
  "bg-removed": "#5e242f",
  "bg-removed-faint": "#4a202d",
  "bg-removed-refine": "#772a35",
  "fg-removed": "#ffbfbf",
  "bg-mode-line-active": "#2f527b",
  "fg-mode-line-active": "#ecf0ff",
  "bg-completion": "#204358",
  "bg-popup": "#19263a",
  "bg-hover": "#684d54",
  "bg-hover-secondary": "#49516a",
  "bg-hl-line": "#243242",
  "bg-paren-match": "#6c5d54",
  "bg-err": "#551327",
  "bg-warning": "#403f22",
  "bg-info": "#104324",
  "bg-region": "#183c65",
  "bg-diff-context": "#1d2c39", // ef-common mapping resolved
  "bg-tab-bar": "#2a3644", // ef-common mapping resolved
  "bg-tab-current": "#131c2b", // ef-common mapping resolved
  "bg-tab-other": "#4a5664", // ef-common mapping resolved
  "border-mode-line-active": "#595a63", // ef-common mapping resolved
  "bg-mode-line-inactive": "#2a3644", // ef-common mapping resolved
  "fg-mode-line-inactive": "#969faf", // ef-common mapping resolved
  "border-mode-line-inactive": "#595a63", // ef-common mapping resolved
};

const mappings: Mapping = {
  // --- ef-maris-dark-palette-mappings-partial ---
  err: "red-warmer",
  warning: "yellow-warmer",
  info: "green-cooler",
  "fg-link": "blue",
  "fg-link-visited": "magenta-cooler",
  name: "blue",
  keybind: "blue-cooler",
  identifier: "magenta-faint",
  "fg-prompt": "blue-warmer",
  builtin: "magenta-faint",
  comment: "red-faint",
  constant: "blue-cooler",
  fnname: "green-warmer",
  "fnname-call": "green-faint",
  keyword: "blue-warmer",
  preprocessor: "magenta-cooler",
  docstring: "cyan-faint",
  string: "cyan-cooler",
  type: "green",
  variable: "cyan",
  "variable-use": "cyan-faint",
  "rx-backslash": "yellow",
  "rx-construct": "red",
  "accent-0": "blue-cooler",
  "accent-1": "green-warmer",
  "accent-2": "cyan",
  "accent-3": "red-cooler",
  "date-common": "cyan-cooler",
  "date-deadline": "red",
  "date-deadline-subtle": "red-faint",
  "date-event": "fg-alt",
  "date-holiday": "blue-warmer",
  "date-now": "fg-main",
  "date-range": "fg-alt",
  "date-scheduled": "yellow-cooler",
  "date-scheduled-subtle": "yellow-faint",
  "date-weekday": "cyan-warmer",
  "date-weekend": "red-faint",
  "fg-prose-code": "cyan",
  "prose-done": "green-cooler",
  "fg-prose-macro": "magenta-cooler",
  "prose-metadata": "fg-dim",
  "prose-metadata-value": "fg-alt",
  "prose-table": "fg-alt",
  "prose-table-formula": "warning",
  "prose-tag": "cyan-faint",
  "prose-todo": "red-cooler",
  "fg-prose-verbatim": "green-warmer",
  "mail-cite-0": "cyan-cooler",
  "mail-cite-1": "magenta",
  "mail-cite-2": "blue-faint",
  "mail-cite-3": "yellow-cooler",
  "mail-part": "cyan",
  "mail-recipient": "blue-warmer",
  "mail-subject": "green-warmer",
  "mail-other": "blue",
  "bg-search-static": "bg-warning",
  "bg-search-current": "bg-yellow-intense",
  "bg-search-lazy": "bg-blue-intense",
  "bg-search-replace": "bg-red-intense",
  "bg-search-rx-group-0": "bg-magenta-intense",
  "bg-search-rx-group-1": "bg-green-intense",
  "bg-search-rx-group-2": "bg-red-subtle",
  "bg-search-rx-group-3": "bg-cyan-subtle",
  "bg-space-err": "bg-yellow-intense",
  "rainbow-0": "green-cooler",
  "rainbow-1": "blue-warmer",
  "rainbow-2": "green-warmer",
  "rainbow-3": "cyan",
  "rainbow-4": "magenta-cooler",
  "rainbow-5": "blue-cooler",
  "rainbow-6": "magenta",
  "rainbow-7": "cyan-cooler",
  "rainbow-8": "yellow-cooler",

  // --- ef-themes-palette-common (shared across all ef-themes) ---
  fringe: UNSPEC,
  property: "variable",
  "fg-region": UNSPEC,
  "fg-link-symbolic": "fg-alt",
  "underline-link": "border",
  "underline-link-visited": "border",
  "underline-link-symbolic": "border",
  "bg-line-number-active": UNSPEC,
  "fg-line-number-active": "accent-0",
  "bg-line-number-inactive": UNSPEC,
  "bg-prominent-err": "bg-err",
  "bg-prominent-warning": "bg-warning",
  "bg-prominent-note": "bg-info",
  "fg-prominent-err": "err",
  "fg-prominent-warning": "warning",
  "fg-prominent-note": "info",
  "bg-space": UNSPEC,
  "fg-space": "border",
  "bg-active-argument": "bg-warning",
  "fg-active-argument": "warning",
  "bg-active-value": "bg-info",
  "fg-active-value": "info",
  "bg-mark-delete": "bg-err",
  "fg-mark-delete": "err",
  "bg-mark-select": "bg-info",
  "fg-mark-select": "info",
  "bg-mark-other": "bg-warning",
  "fg-mark-other": "warning",
  "fg-search-current": "fg-main",
  "fg-search-lazy": "fg-main",
  "fg-search-static": "fg-main",
  "fg-search-replace": "fg-main",
  "fg-search-rx-group-0": "fg-main",
  "fg-search-rx-group-1": "fg-main",
  "fg-search-rx-group-2": "fg-main",
  "fg-search-rx-group-3": "fg-main",
  "fg-completion-match-0": "accent-0",
  "fg-completion-match-1": "accent-1",
  "fg-completion-match-2": "accent-2",
  "fg-completion-match-3": "accent-3",
  "fg-heading-0": "rainbow-0",
  "fg-heading-1": "rainbow-1",
  "fg-heading-2": "rainbow-2",
  "fg-heading-3": "rainbow-3",
  "fg-heading-4": "rainbow-4",
  "fg-heading-5": "rainbow-5",
  "fg-heading-6": "rainbow-6",
  "fg-heading-7": "rainbow-7",
  "fg-heading-8": "rainbow-8",
};

export const efMarisDark: ThemeDoc = {
  meta: {
    name: "ef-maris-dark",
    description: "Legible dark marine theme with blue, cyan, and green colors.",
    mode: "dark",
  },
  palette,
  mappings,
};
