// ef-melissa-dark (dark) — bundled preset, both layers.
//
// The ef-themes are built on top of the modus-themes (since ef-themes 2.0.0):
// they use the same `modus-themes-theme` macro and palette structure. This seed
// is a faithful port so it can be edited and exported as a self-contained
// modus-themes derivative (no ef-themes dependency at load time).
//
// Transcribed verbatim from ef-melissa-dark-theme.el + ef-themes.el upstream:
//   - ef-melissa-dark-palette-partial            (named colors)
//   - ef-melissa-dark-palette-mappings-partial   (theme-specific mappings)
//   - ef-themes-palette-common            (shared mappings, appended)
// To refresh: re-transcribe from https://github.com/protesilaos/ef-themes
//
// A few shared entries (mode-line, tab-bar, bg-diff-context) are layer-1 colors
// in this model but defined upstream as mappings to other named colors; they are
// resolved to hex and placed in the palette block. All other mappings are kept
// symbolic, so resolve.ts follows the indirection as the modus engine does.

import { UNSPECIFIED as UNSPEC } from "./resolve.ts";
import type { Mapping, Palette, ThemeDoc } from "./types.ts";

const palette: Palette = {
  cursor: "#f9cf7a",
  "bg-main": "#352718",
  "bg-dim": "#483426",
  "bg-alt": "#59463f",
  "fg-main": "#e8e4b1",
  "fg-dim": "#90918a",
  "fg-alt": "#ccaa70",
  "bg-active": "#79665f",
  "bg-inactive": "#4d3e2f",
  border: "#6f5f58",
  red: "#ff7f7f",
  "red-warmer": "#ff7f4f",
  "red-cooler": "#ff8f98",
  "red-faint": "#e89a88",
  green: "#6fd560",
  "green-warmer": "#a0d13a",
  "green-cooler": "#65d590",
  "green-faint": "#a0d26f",
  yellow: "#e4b53f",
  "yellow-warmer": "#ffa21f",
  "yellow-cooler": "#e7a06f",
  "yellow-faint": "#eab780",
  blue: "#57aff6",
  "blue-warmer": "#98bfff",
  "blue-cooler": "#62cfef",
  "blue-faint": "#6ab4ef",
  magenta: "#f0aac5",
  "magenta-warmer": "#fa90aa",
  "magenta-cooler": "#c6a2fe",
  "magenta-faint": "#dfcfe0",
  cyan: "#6fcad0",
  "cyan-warmer": "#7fc5df",
  "cyan-cooler": "#70e0cf",
  "cyan-faint": "#99bfcf",
  "bg-red-intense": "#b02930",
  "bg-green-intense": "#4a7100",
  "bg-yellow-intense": "#8f5040",
  "bg-blue-intense": "#4648d0",
  "bg-magenta-intense": "#a04fc5",
  "bg-cyan-intense": "#2270cf",
  "bg-red-subtle": "#72292a",
  "bg-green-subtle": "#3f521a",
  "bg-yellow-subtle": "#604b13",
  "bg-blue-subtle": "#384862",
  "bg-magenta-subtle": "#613a50",
  "bg-cyan-subtle": "#2f4f4f",
  "bg-added": "#2f491f",
  "bg-added-faint": "#2f3b0f",
  "bg-added-refine": "#3f6234",
  "fg-added": "#a0e0a0",
  "bg-changed": "#544a0f",
  "bg-changed-faint": "#43350f",
  "bg-changed-refine": "#615f1f",
  "fg-changed": "#dada90",
  "bg-removed": "#622a1f",
  "bg-removed-faint": "#4b240a",
  "bg-removed-refine": "#7f3325",
  "fg-removed": "#ffbfbf",
  "bg-mode-line-active": "#704f00",
  "fg-mode-line-active": "#f8efd8",
  "bg-completion": "#66421f",
  "bg-popup": "#44321e",
  "bg-hover": "#60518f",
  "bg-hover-secondary": "#5a661f",
  "bg-hl-line": "#4f311f",
  "bg-paren-match": "#5f6f1f",
  "bg-err": "#571a05",
  "bg-warning": "#4e4310",
  "bg-info": "#2f4302",
  "bg-region": "#443a4f",
  "bg-diff-context": "#483426", // ef-common mapping resolved
  "bg-tab-bar": "#59463f", // ef-common mapping resolved
  "bg-tab-current": "#352718", // ef-common mapping resolved
  "bg-tab-other": "#79665f", // ef-common mapping resolved
  "border-mode-line-active": "#6f5f58", // ef-common mapping resolved
  "bg-mode-line-inactive": "#59463f", // ef-common mapping resolved
  "fg-mode-line-inactive": "#90918a", // ef-common mapping resolved
  "border-mode-line-inactive": "#6f5f58", // ef-common mapping resolved
};

const mappings: Mapping = {
  // --- ef-melissa-dark-palette-mappings-partial ---
  err: "red-warmer",
  warning: "yellow-warmer",
  info: "green",
  "fg-link": "yellow",
  "fg-link-visited": "magenta-cooler",
  name: "yellow-cooler",
  keybind: "yellow-warmer",
  identifier: "red-faint",
  "fg-prompt": "green-warmer",
  builtin: "yellow-cooler",
  comment: "yellow-faint",
  constant: "blue-warmer",
  fnname: "green",
  "fnname-call": "green-faint",
  keyword: "yellow",
  preprocessor: "red-warmer",
  docstring: "red-faint",
  string: "yellow-warmer",
  type: "green-cooler",
  variable: "cyan",
  "variable-use": "cyan-faint",
  "rx-backslash": "green",
  "rx-construct": "magenta-cooler",
  "accent-0": "yellow-warmer",
  "accent-1": "green-cooler",
  "accent-2": "red",
  "accent-3": "magenta-cooler",
  "date-common": "green-warmer",
  "date-deadline": "red",
  "date-deadline-subtle": "red-faint",
  "date-event": "fg-alt",
  "date-holiday": "magenta-warmer",
  "date-now": "fg-main",
  "date-range": "fg-alt",
  "date-scheduled": "yellow",
  "date-scheduled-subtle": "yellow-faint",
  "date-weekday": "green-warmer",
  "date-weekend": "red-cooler",
  "fg-prose-code": "yellow-warmer",
  "prose-done": "green",
  "fg-prose-macro": "green-warmer",
  "prose-metadata": "fg-dim",
  "prose-metadata-value": "fg-alt",
  "prose-table": "fg-alt",
  "prose-table-formula": "err",
  "prose-tag": "yellow-faint",
  "prose-todo": "red-warmer",
  "fg-prose-verbatim": "red",
  "mail-cite-0": "yellow-warmer",
  "mail-cite-1": "blue-warmer",
  "mail-cite-2": "red-cooler",
  "mail-cite-3": "green-cooler",
  "mail-part": "cyan",
  "mail-recipient": "yellow",
  "mail-subject": "green",
  "mail-other": "yellow-cooler",
  "bg-search-static": "bg-warning",
  "bg-search-current": "bg-yellow-intense",
  "bg-search-lazy": "bg-blue-intense",
  "bg-search-replace": "bg-red-intense",
  "bg-search-rx-group-0": "bg-magenta-intense",
  "bg-search-rx-group-1": "bg-green-intense",
  "bg-search-rx-group-2": "bg-red-subtle",
  "bg-search-rx-group-3": "bg-cyan-subtle",
  "bg-space-err": "bg-yellow-intense",
  "rainbow-0": "yellow-warmer",
  "rainbow-1": "yellow",
  "rainbow-2": "green-warmer",
  "rainbow-3": "red-cooler",
  "rainbow-4": "cyan-warmer",
  "rainbow-5": "magenta",
  "rainbow-6": "green-cooler",
  "rainbow-7": "magenta-warmer",
  "rainbow-8": "cyan-cooler",

  // --- ef-themes-palette-common (shared across all ef-themes) ---
  fringe: UNSPEC,
  property: "variable",
  "fg-region": UNSPEC,
  "fg-link-symbolic": "fg-alt",
  "underline-link": "border",
  "underline-link-visited": "border",
  "underline-link-symbolic": "border",
  "bg-line-number-active": UNSPEC,
  "fg-line-number-active": "accent-0",
  "bg-line-number-inactive": UNSPEC,
  "bg-prominent-err": "bg-err",
  "bg-prominent-warning": "bg-warning",
  "bg-prominent-note": "bg-info",
  "fg-prominent-err": "err",
  "fg-prominent-warning": "warning",
  "fg-prominent-note": "info",
  "bg-space": UNSPEC,
  "fg-space": "border",
  "bg-active-argument": "bg-warning",
  "fg-active-argument": "warning",
  "bg-active-value": "bg-info",
  "fg-active-value": "info",
  "bg-mark-delete": "bg-err",
  "fg-mark-delete": "err",
  "bg-mark-select": "bg-info",
  "fg-mark-select": "info",
  "bg-mark-other": "bg-warning",
  "fg-mark-other": "warning",
  "fg-search-current": "fg-main",
  "fg-search-lazy": "fg-main",
  "fg-search-static": "fg-main",
  "fg-search-replace": "fg-main",
  "fg-search-rx-group-0": "fg-main",
  "fg-search-rx-group-1": "fg-main",
  "fg-search-rx-group-2": "fg-main",
  "fg-search-rx-group-3": "fg-main",
  "fg-completion-match-0": "accent-0",
  "fg-completion-match-1": "accent-1",
  "fg-completion-match-2": "accent-2",
  "fg-completion-match-3": "accent-3",
  "fg-heading-0": "rainbow-0",
  "fg-heading-1": "rainbow-1",
  "fg-heading-2": "rainbow-2",
  "fg-heading-3": "rainbow-3",
  "fg-heading-4": "rainbow-4",
  "fg-heading-5": "rainbow-5",
  "fg-heading-6": "rainbow-6",
  "fg-heading-7": "rainbow-7",
  "fg-heading-8": "rainbow-8",
};

export const efMelissaDark: ThemeDoc = {
  meta: {
    name: "ef-melissa-dark",
    description: "Legible dark honeybee theme with warm colors (yellow, red, green, cyan).",
    mode: "dark",
  },
  palette,
  mappings,
};
