// ef-melissa-light (light) — bundled preset, both layers.
//
// The ef-themes are built on top of the modus-themes (since ef-themes 2.0.0):
// they use the same `modus-themes-theme` macro and palette structure. This seed
// is a faithful port so it can be edited and exported as a self-contained
// modus-themes derivative (no ef-themes dependency at load time).
//
// Transcribed verbatim from ef-melissa-light-theme.el + ef-themes.el upstream:
//   - ef-melissa-light-palette-partial            (named colors)
//   - ef-melissa-light-palette-mappings-partial   (theme-specific mappings)
//   - ef-themes-palette-common            (shared mappings, appended)
// To refresh: re-transcribe from https://github.com/protesilaos/ef-themes
//
// A few shared entries (mode-line, tab-bar, bg-diff-context) are layer-1 colors
// in this model but defined upstream as mappings to other named colors; they are
// resolved to hex and placed in the palette block. All other mappings are kept
// symbolic, so resolve.ts follows the indirection as the modus engine does.

import { UNSPECIFIED as UNSPEC } from "./resolve.ts";
import type { Mapping, Palette, ThemeDoc } from "./types.ts";

const palette: Palette = {
  cursor: "#a07f00",
  "bg-main": "#fff6d8",
  "bg-dim": "#f5e9cb",
  "bg-alt": "#e7d7c6",
  "fg-main": "#484431",
  "fg-dim": "#68708a",
  "fg-alt": "#80431a",
  "bg-active": "#c7b7a6",
  "bg-inactive": "#f0e3cd",
  border: "#c5baa6",
  red: "#ba2d2f",
  "red-warmer": "#c74400",
  "red-cooler": "#c02945",
  "red-faint": "#b05350",
  green: "#007a0a",
  "green-warmer": "#5a7400",
  "green-cooler": "#008250",
  "green-faint": "#61756c",
  yellow: "#a26310",
  "yellow-warmer": "#ba5205",
  "yellow-cooler": "#946830",
  "yellow-faint": "#7f6f1a",
  blue: "#375cc6",
  "blue-warmer": "#5f5fdf",
  "blue-cooler": "#265fbf",
  "blue-faint": "#4a659f",
  magenta: "#aa3e74",
  "magenta-warmer": "#b02f80",
  "magenta-cooler": "#6448ca",
  "magenta-faint": "#905ea0",
  cyan: "#3f60af",
  "cyan-warmer": "#4060a0",
  "cyan-cooler": "#0f708a",
  "cyan-faint": "#4f6f8f",
  "bg-red-intense": "#ff8f88",
  "bg-green-intense": "#96df80",
  "bg-yellow-intense": "#efbf00",
  "bg-blue-intense": "#cfceff",
  "bg-magenta-intense": "#df9fff",
  "bg-cyan-intense": "#88cfd0",
  "bg-red-subtle": "#ffceb0",
  "bg-green-subtle": "#cbf09f",
  "bg-yellow-subtle": "#f4ed7e",
  "bg-blue-subtle": "#cce4f2",
  "bg-magenta-subtle": "#fad6ef",
  "bg-cyan-subtle": "#bfefef",
  "bg-added": "#d7ecb0",
  "bg-added-faint": "#eef3c2",
  "bg-added-refine": "#c9dda0",
  "fg-added": "#005000",
  "bg-changed": "#f5e690",
  "bg-changed-faint": "#f5edaf",
  "bg-changed-refine": "#edd482",
  "fg-changed": "#553d00",
  "bg-removed": "#f8d0b6",
  "bg-removed-faint": "#f5deb0",
  "bg-removed-refine": "#f0bba9",
  "fg-removed": "#8f1313",
  "bg-mode-line-active": "#f3cf72",
  "fg-mode-line-active": "#403328",
  "bg-completion": "#f9dfa8",
  "bg-popup": "#ffeed0",
  "bg-hover": "#deb4f0",
  "bg-hover-secondary": "#c4d47a",
  "bg-hl-line": "#fae7b0",
  "bg-paren-match": "#afcf8f",
  "bg-err": "#ffd4b5",
  "bg-warning": "#ffe89f",
  "bg-info": "#ddf5ac",
  "bg-region": "#f0d4d8",
  "bg-diff-context": "#f5e9cb", // ef-common mapping resolved
  "bg-tab-bar": "#e7d7c6", // ef-common mapping resolved
  "bg-tab-current": "#fff6d8", // ef-common mapping resolved
  "bg-tab-other": "#c7b7a6", // ef-common mapping resolved
  "border-mode-line-active": "#c5baa6", // ef-common mapping resolved
  "bg-mode-line-inactive": "#e7d7c6", // ef-common mapping resolved
  "fg-mode-line-inactive": "#68708a", // ef-common mapping resolved
  "border-mode-line-inactive": "#c5baa6", // ef-common mapping resolved
};

const mappings: Mapping = {
  // --- ef-melissa-light-palette-mappings-partial ---
  err: "red-warmer",
  warning: "yellow-warmer",
  info: "green",
  "fg-link": "yellow",
  "fg-link-visited": "magenta-cooler",
  name: "yellow-cooler",
  keybind: "yellow-warmer",
  identifier: "red-faint",
  "fg-prompt": "green-warmer",
  builtin: "yellow-cooler",
  comment: "yellow-faint",
  constant: "cyan",
  fnname: "green-warmer",
  "fnname-call": "green-faint",
  keyword: "yellow",
  preprocessor: "yellow-warmer",
  docstring: "red-faint",
  string: "red-warmer",
  type: "green-cooler",
  variable: "cyan-cooler",
  "variable-use": "cyan-faint",
  "rx-backslash": "green",
  "rx-construct": "magenta-cooler",
  "accent-0": "yellow-warmer",
  "accent-1": "green-cooler",
  "accent-2": "red",
  "accent-3": "magenta-cooler",
  "date-common": "green-warmer",
  "date-deadline": "red",
  "date-deadline-subtle": "red-faint",
  "date-event": "fg-alt",
  "date-holiday": "magenta-warmer",
  "date-now": "fg-main",
  "date-range": "fg-alt",
  "date-scheduled": "yellow",
  "date-scheduled-subtle": "yellow-faint",
  "date-weekday": "green-warmer",
  "date-weekend": "red-faint",
  "fg-prose-code": "yellow-warmer",
  "prose-done": "green",
  "fg-prose-macro": "green-warmer",
  "prose-metadata": "fg-dim",
  "prose-metadata-value": "fg-alt",
  "prose-table": "fg-alt",
  "prose-table-formula": "warning",
  "prose-tag": "yellow-faint",
  "prose-todo": "red-warmer",
  "fg-prose-verbatim": "red",
  "mail-cite-0": "yellow-warmer",
  "mail-cite-1": "cyan-warmer",
  "mail-cite-2": "red-cooler",
  "mail-cite-3": "green-cooler",
  "mail-part": "cyan-cooler",
  "mail-recipient": "yellow",
  "mail-subject": "green-warmer",
  "mail-other": "yellow-cooler",
  "bg-search-static": "bg-warning",
  "bg-search-current": "bg-yellow-intense",
  "bg-search-lazy": "bg-blue-intense",
  "bg-search-replace": "bg-red-intense",
  "bg-search-rx-group-0": "bg-magenta-intense",
  "bg-search-rx-group-1": "bg-green-intense",
  "bg-search-rx-group-2": "bg-red-subtle",
  "bg-search-rx-group-3": "bg-cyan-subtle",
  "bg-space-err": "bg-yellow-intense",
  "rainbow-0": "yellow-warmer",
  "rainbow-1": "yellow",
  "rainbow-2": "green-warmer",
  "rainbow-3": "red-cooler",
  "rainbow-4": "cyan-warmer",
  "rainbow-5": "magenta",
  "rainbow-6": "green-cooler",
  "rainbow-7": "magenta-warmer",
  "rainbow-8": "cyan-cooler",

  // --- ef-themes-palette-common (shared across all ef-themes) ---
  fringe: UNSPEC,
  property: "variable",
  "fg-region": UNSPEC,
  "fg-link-symbolic": "fg-alt",
  "underline-link": "border",
  "underline-link-visited": "border",
  "underline-link-symbolic": "border",
  "bg-line-number-active": UNSPEC,
  "fg-line-number-active": "accent-0",
  "bg-line-number-inactive": UNSPEC,
  "bg-prominent-err": "bg-err",
  "bg-prominent-warning": "bg-warning",
  "bg-prominent-note": "bg-info",
  "fg-prominent-err": "err",
  "fg-prominent-warning": "warning",
  "fg-prominent-note": "info",
  "bg-space": UNSPEC,
  "fg-space": "border",
  "bg-active-argument": "bg-warning",
  "fg-active-argument": "warning",
  "bg-active-value": "bg-info",
  "fg-active-value": "info",
  "bg-mark-delete": "bg-err",
  "fg-mark-delete": "err",
  "bg-mark-select": "bg-info",
  "fg-mark-select": "info",
  "bg-mark-other": "bg-warning",
  "fg-mark-other": "warning",
  "fg-search-current": "fg-main",
  "fg-search-lazy": "fg-main",
  "fg-search-static": "fg-main",
  "fg-search-replace": "fg-main",
  "fg-search-rx-group-0": "fg-main",
  "fg-search-rx-group-1": "fg-main",
  "fg-search-rx-group-2": "fg-main",
  "fg-search-rx-group-3": "fg-main",
  "fg-completion-match-0": "accent-0",
  "fg-completion-match-1": "accent-1",
  "fg-completion-match-2": "accent-2",
  "fg-completion-match-3": "accent-3",
  "fg-heading-0": "rainbow-0",
  "fg-heading-1": "rainbow-1",
  "fg-heading-2": "rainbow-2",
  "fg-heading-3": "rainbow-3",
  "fg-heading-4": "rainbow-4",
  "fg-heading-5": "rainbow-5",
  "fg-heading-6": "rainbow-6",
  "fg-heading-7": "rainbow-7",
  "fg-heading-8": "rainbow-8",
};

export const efMelissaLight: ThemeDoc = {
  meta: {
    name: "ef-melissa-light",
    description: "Legible light honeybee theme with warm colors (yellow, red, green, cyan).",
    mode: "light",
  },
  palette,
  mappings,
};
