// ef-maris-light (light) — bundled preset, both layers.
//
// The ef-themes are built on top of the modus-themes (since ef-themes 2.0.0):
// they use the same `modus-themes-theme` macro and palette structure. This seed
// is a faithful port so it can be edited and exported as a self-contained
// modus-themes derivative (no ef-themes dependency at load time).
//
// Transcribed verbatim from ef-maris-light-theme.el + ef-themes.el upstream:
//   - ef-maris-light-palette-partial            (named colors)
//   - ef-maris-light-palette-mappings-partial   (theme-specific mappings)
//   - ef-themes-palette-common            (shared mappings, appended)
// To refresh: re-transcribe from https://github.com/protesilaos/ef-themes
//
// A few shared entries (mode-line, tab-bar, bg-diff-context) are layer-1 colors
// in this model but defined upstream as mappings to other named colors; they are
// resolved to hex and placed in the palette block. All other mappings are kept
// symbolic, so resolve.ts follows the indirection as the modus engine does.

import { UNSPECIFIED as UNSPEC } from "./resolve.ts";
import type { Mapping, Palette, ThemeDoc } from "./types.ts";

const palette: Palette = {
  cursor: "#036f99",
  "bg-main": "#edf4f8",
  "bg-dim": "#e0e7ef",
  "bg-alt": "#cfd8e3",
  "fg-main": "#151a27",
  "fg-dim": "#676470",
  "fg-alt": "#3f4f99",
  "bg-active": "#afb8c3",
  "bg-inactive": "#dbe4e6",
  border: "#a2a6af",
  red: "#c3303a",
  "red-warmer": "#d00000",
  "red-cooler": "#b02440",
  "red-faint": "#8b4052",
  green: "#007010",
  "green-warmer": "#3a6f00",
  "green-cooler": "#007047",
  "green-faint": "#4a763f",
  yellow: "#805a1f",
  "yellow-warmer": "#8b4400",
  "yellow-cooler": "#78542f",
  "yellow-faint": "#7f4f4a",
  blue: "#375cc6",
  "blue-warmer": "#444fcf",
  "blue-cooler": "#003faf",
  "blue-faint": "#3a5099",
  magenta: "#80308f",
  "magenta-warmer": "#9a3a6a",
  "magenta-cooler": "#5f2fba",
  "magenta-faint": "#6a4a9f",
  cyan: "#1f66af",
  "cyan-warmer": "#305675",
  "cyan-cooler": "#006f70",
  "cyan-faint": "#3f627f",
  "bg-red-intense": "#ff8f88",
  "bg-green-intense": "#96df80",
  "bg-yellow-intense": "#efbf00",
  "bg-blue-intense": "#cfceff",
  "bg-magenta-intense": "#df9fff",
  "bg-cyan-intense": "#88cfd0",
  "bg-red-subtle": "#f0c6cf",
  "bg-green-subtle": "#b0ebca",
  "bg-yellow-subtle": "#e4e498",
  "bg-blue-subtle": "#ccd5f7",
  "bg-magenta-subtle": "#edd3f2",
  "bg-cyan-subtle": "#b2e6f0",
  "bg-added": "#b0e8ca",
  "bg-added-faint": "#c5f0e0",
  "bg-added-refine": "#a0d4b9",
  "fg-added": "#005000",
  "bg-changed": "#f5e8b0",
  "bg-changed-faint": "#f5f2bf",
  "bg-changed-refine": "#f0db9a",
  "fg-changed": "#553d00",
  "bg-removed": "#f5c7d6",
  "bg-removed-faint": "#f0d6d6",
  "bg-removed-refine": "#efb1cd",
  "fg-removed": "#8f1313",
  "bg-mode-line-active": "#a0c2ef",
  "fg-mode-line-active": "#142810",
  "bg-completion": "#cdd5f7",
  "bg-popup": "#e4eaf0",
  "bg-hover": "#d2b4cf",
  "bg-hover-secondary": "#b7bbea",
  "bg-hl-line": "#dae5f0",
  "bg-paren-match": "#cab3b2",
  "bg-err": "#f2c2b5",
  "bg-warning": "#e8df9a",
  "bg-info": "#a4e2cf",
  "bg-region": "#c8dcff",
  "bg-diff-context": "#e0e7ef", // ef-common mapping resolved
  "bg-tab-bar": "#cfd8e3", // ef-common mapping resolved
  "bg-tab-current": "#edf4f8", // ef-common mapping resolved
  "bg-tab-other": "#afb8c3", // ef-common mapping resolved
  "border-mode-line-active": "#a2a6af", // ef-common mapping resolved
  "bg-mode-line-inactive": "#cfd8e3", // ef-common mapping resolved
  "fg-mode-line-inactive": "#676470", // ef-common mapping resolved
  "border-mode-line-inactive": "#a2a6af", // ef-common mapping resolved
};

const mappings: Mapping = {
  // --- ef-maris-light-palette-mappings-partial ---
  err: "red-warmer",
  warning: "yellow-warmer",
  info: "green-cooler",
  "fg-link": "blue",
  "fg-link-visited": "magenta-cooler",
  name: "blue",
  keybind: "blue-cooler",
  identifier: "magenta-faint",
  "fg-prompt": "blue-warmer",
  builtin: "magenta-faint",
  comment: "red-faint",
  constant: "blue-cooler",
  fnname: "green-warmer",
  "fnname-call": "green-faint",
  keyword: "blue-warmer",
  preprocessor: "magenta-cooler",
  docstring: "cyan-faint",
  string: "cyan-cooler",
  type: "green",
  variable: "cyan",
  "variable-use": "cyan-faint",
  "rx-backslash": "yellow",
  "rx-construct": "red",
  "accent-0": "blue-cooler",
  "accent-1": "green",
  "accent-2": "cyan",
  "accent-3": "red-cooler",
  "date-common": "cyan-cooler",
  "date-deadline": "red",
  "date-deadline-subtle": "red-cooler",
  "date-event": "fg-alt",
  "date-holiday": "blue-warmer",
  "date-now": "fg-main",
  "date-range": "fg-alt",
  "date-scheduled": "yellow",
  "date-scheduled-subtle": "yellow-faint",
  "date-weekday": "cyan-warmer",
  "date-weekend": "red-faint",
  "fg-prose-code": "cyan",
  "prose-done": "green-cooler",
  "fg-prose-macro": "magenta-cooler",
  "prose-metadata": "fg-dim",
  "prose-metadata-value": "fg-alt",
  "prose-table": "fg-alt",
  "prose-table-formula": "warning",
  "prose-tag": "cyan-faint",
  "prose-todo": "red-cooler",
  "fg-prose-verbatim": "green-warmer",
  "mail-cite-0": "cyan",
  "mail-cite-1": "magenta",
  "mail-cite-2": "blue-faint",
  "mail-cite-3": "yellow-cooler",
  "mail-part": "green-cooler",
  "mail-recipient": "blue-warmer",
  "mail-subject": "green-warmer",
  "mail-other": "blue",
  "bg-search-static": "bg-warning",
  "bg-search-current": "bg-yellow-intense",
  "bg-search-lazy": "bg-blue-intense",
  "bg-search-replace": "bg-red-intense",
  "bg-search-rx-group-0": "bg-magenta-intense",
  "bg-search-rx-group-1": "bg-green-intense",
  "bg-search-rx-group-2": "bg-red-subtle",
  "bg-search-rx-group-3": "bg-cyan-subtle",
  "bg-space-err": "bg-yellow-intense",
  "rainbow-0": "green-cooler",
  "rainbow-1": "blue-warmer",
  "rainbow-2": "green-warmer",
  "rainbow-3": "cyan",
  "rainbow-4": "magenta-cooler",
  "rainbow-5": "blue-cooler",
  "rainbow-6": "magenta",
  "rainbow-7": "cyan-cooler",
  "rainbow-8": "yellow-cooler",

  // --- ef-themes-palette-common (shared across all ef-themes) ---
  fringe: UNSPEC,
  property: "variable",
  "fg-region": UNSPEC,
  "fg-link-symbolic": "fg-alt",
  "underline-link": "border",
  "underline-link-visited": "border",
  "underline-link-symbolic": "border",
  "bg-line-number-active": UNSPEC,
  "fg-line-number-active": "accent-0",
  "bg-line-number-inactive": UNSPEC,
  "bg-prominent-err": "bg-err",
  "bg-prominent-warning": "bg-warning",
  "bg-prominent-note": "bg-info",
  "fg-prominent-err": "err",
  "fg-prominent-warning": "warning",
  "fg-prominent-note": "info",
  "bg-space": UNSPEC,
  "fg-space": "border",
  "bg-active-argument": "bg-warning",
  "fg-active-argument": "warning",
  "bg-active-value": "bg-info",
  "fg-active-value": "info",
  "bg-mark-delete": "bg-err",
  "fg-mark-delete": "err",
  "bg-mark-select": "bg-info",
  "fg-mark-select": "info",
  "bg-mark-other": "bg-warning",
  "fg-mark-other": "warning",
  "fg-search-current": "fg-main",
  "fg-search-lazy": "fg-main",
  "fg-search-static": "fg-main",
  "fg-search-replace": "fg-main",
  "fg-search-rx-group-0": "fg-main",
  "fg-search-rx-group-1": "fg-main",
  "fg-search-rx-group-2": "fg-main",
  "fg-search-rx-group-3": "fg-main",
  "fg-completion-match-0": "accent-0",
  "fg-completion-match-1": "accent-1",
  "fg-completion-match-2": "accent-2",
  "fg-completion-match-3": "accent-3",
  "fg-heading-0": "rainbow-0",
  "fg-heading-1": "rainbow-1",
  "fg-heading-2": "rainbow-2",
  "fg-heading-3": "rainbow-3",
  "fg-heading-4": "rainbow-4",
  "fg-heading-5": "rainbow-5",
  "fg-heading-6": "rainbow-6",
  "fg-heading-7": "rainbow-7",
  "fg-heading-8": "rainbow-8",
};

export const efMarisLight: ThemeDoc = {
  meta: {
    name: "ef-maris-light",
    description: "Legible light marine theme with blue, cyan, and green colors.",
    mode: "light",
  },
  palette,
  mappings,
};
