// ef-night (dark) — bundled preset, both layers.
//
// The ef-themes are built on top of the modus-themes (since ef-themes 2.0.0):
// they use the same `modus-themes-theme` macro and palette structure. This seed
// is a faithful port so it can be edited and exported as a self-contained
// modus-themes derivative (no ef-themes dependency at load time).
//
// Transcribed verbatim from ef-night-theme.el + ef-themes.el upstream:
//   - ef-night-palette-partial            (named colors)
//   - ef-night-palette-mappings-partial   (theme-specific mappings)
//   - ef-themes-palette-common            (shared mappings, appended)
// To refresh: re-transcribe from https://github.com/protesilaos/ef-themes
//
// A few shared entries (mode-line, tab-bar, bg-diff-context) are layer-1 colors
// in this model but defined upstream as mappings to other named colors; they are
// resolved to hex and placed in the palette block. All other mappings are kept
// symbolic, so resolve.ts follows the indirection as the modus engine does.

import { UNSPECIFIED as UNSPEC } from "./resolve.ts";
import type { Mapping, Palette, ThemeDoc } from "./types.ts";

const palette: Palette = {
  cursor: "#00ccff",
  "bg-main": "#000e17",
  "bg-dim": "#1a202b",
  "bg-alt": "#242e39",
  "fg-main": "#afbcbf",
  "fg-dim": "#70819f",
  "fg-alt": "#b0a0a0",
  "bg-active": "#444e59",
  "bg-inactive": "#21242f",
  border: "#3a4a66",
  red: "#ef656a",
  "red-warmer": "#f47360",
  "red-cooler": "#ef798f",
  "red-faint": "#d56f72",
  green: "#1fa526",
  "green-warmer": "#50a22f",
  "green-cooler": "#00a972",
  "green-faint": "#61a06c",
  yellow: "#c48502",
  "yellow-warmer": "#e6832f",
  "yellow-cooler": "#df8f6f",
  "yellow-faint": "#cf9f7f",
  blue: "#379cf6",
  "blue-warmer": "#6a88ff",
  "blue-cooler": "#029fff",
  "blue-faint": "#7a94df",
  magenta: "#d570af",
  "magenta-warmer": "#e580ea",
  "magenta-cooler": "#af8aff",
  "magenta-faint": "#c59fcf",
  cyan: "#4fb0cf",
  "cyan-warmer": "#6fafff",
  "cyan-cooler": "#3dc0b0",
  "cyan-faint": "#92b4df",
  "bg-red-intense": "#bd1f30",
  "bg-green-intense": "#107440",
  "bg-yellow-intense": "#847020",
  "bg-blue-intense": "#2f5f9f",
  "bg-magenta-intense": "#804fd5",
  "bg-cyan-intense": "#0280b9",
  "bg-red-subtle": "#6a1b2f",
  "bg-green-subtle": "#0a432f",
  "bg-yellow-subtle": "#533420",
  "bg-blue-subtle": "#1f3665",
  "bg-magenta-subtle": "#502555",
  "bg-cyan-subtle": "#113b5e",
  "bg-added": "#00371f",
  "bg-added-faint": "#002918",
  "bg-added-refine": "#004c2f",
  "fg-added": "#a0e0a0",
  "bg-changed": "#363300",
  "bg-changed-faint": "#2a1f00",
  "bg-changed-refine": "#4a4a00",
  "fg-changed": "#efef80",
  "bg-removed": "#450f1f",
  "bg-removed-faint": "#2f060f",
  "bg-removed-refine": "#641426",
  "fg-removed": "#ffbfbf",
  "bg-mode-line-active": "#003a7f",
  "fg-mode-line-active": "#ceeeff",
  "bg-completion": "#043957",
  "bg-popup": "#001c2f",
  "bg-hover": "#6f345a",
  "bg-hover-secondary": "#493737",
  "bg-hl-line": "#002255",
  "bg-paren-match": "#664950",
  "bg-err": "#471014",
  "bg-warning": "#3b2f04",
  "bg-info": "#103512",
  "bg-region": "#253146",
  "bg-diff-context": "#1a202b", // ef-common mapping resolved
  "bg-tab-bar": "#242e39", // ef-common mapping resolved
  "bg-tab-current": "#000e17", // ef-common mapping resolved
  "bg-tab-other": "#444e59", // ef-common mapping resolved
  "border-mode-line-active": "#3a4a66", // ef-common mapping resolved
  "bg-mode-line-inactive": "#242e39", // ef-common mapping resolved
  "fg-mode-line-inactive": "#70819f", // ef-common mapping resolved
  "border-mode-line-inactive": "#3a4a66", // ef-common mapping resolved
};

const mappings: Mapping = {
  // --- ef-night-palette-mappings-partial ---
  err: "red",
  warning: "yellow-warmer",
  info: "green-cooler",
  "fg-link": "cyan-warmer",
  "fg-link-visited": "magenta",
  name: "blue-warmer",
  keybind: "green-cooler",
  identifier: "magenta-faint",
  "fg-prompt": "cyan-warmer",
  builtin: "green-cooler",
  comment: "yellow-faint",
  constant: "magenta-cooler",
  fnname: "cyan-cooler",
  "fnname-call": "cyan-faint",
  keyword: "blue-warmer",
  preprocessor: "red-faint",
  docstring: "cyan-faint",
  string: "blue-cooler",
  type: "magenta-faint",
  variable: "cyan-warmer",
  "variable-use": "cyan-faint",
  "rx-backslash": "green",
  "rx-construct": "magenta-warmer",
  "accent-0": "blue-cooler",
  "accent-1": "magenta-warmer",
  "accent-2": "cyan-cooler",
  "accent-3": "red-cooler",
  "date-common": "cyan",
  "date-deadline": "red",
  "date-deadline-subtle": "red-faint",
  "date-event": "fg-alt",
  "date-holiday": "magenta-warmer",
  "date-now": "fg-main",
  "date-range": "fg-alt",
  "date-scheduled": "yellow",
  "date-scheduled-subtle": "yellow-faint",
  "date-weekday": "cyan",
  "date-weekend": "red-faint",
  "fg-prose-code": "magenta-warmer",
  "prose-done": "green-cooler",
  "fg-prose-macro": "cyan-cooler",
  "prose-metadata": "fg-dim",
  "prose-metadata-value": "fg-alt",
  "prose-table": "fg-alt",
  "prose-table-formula": "info",
  "prose-tag": "fg-alt",
  "prose-todo": "red",
  "fg-prose-verbatim": "blue-cooler",
  "mail-cite-0": "blue",
  "mail-cite-1": "magenta-warmer",
  "mail-cite-2": "green-cooler",
  "mail-cite-3": "yellow-cooler",
  "mail-part": "cyan",
  "mail-recipient": "blue-warmer",
  "mail-subject": "cyan-cooler",
  "mail-other": "cyan-warmer",
  "bg-search-static": "bg-warning",
  "bg-search-current": "bg-yellow-intense",
  "bg-search-lazy": "bg-blue-intense",
  "bg-search-replace": "bg-red-intense",
  "bg-search-rx-group-0": "bg-magenta-intense",
  "bg-search-rx-group-1": "bg-green-intense",
  "bg-search-rx-group-2": "bg-red-subtle",
  "bg-search-rx-group-3": "bg-cyan-subtle",
  "bg-space-err": "bg-yellow-intense",
  "rainbow-0": "cyan-warmer",
  "rainbow-1": "magenta-cooler",
  "rainbow-2": "yellow-cooler",
  "rainbow-3": "blue-warmer",
  "rainbow-4": "magenta",
  "rainbow-5": "cyan",
  "rainbow-6": "yellow",
  "rainbow-7": "red-cooler",
  "rainbow-8": "green-warmer",

  // --- ef-themes-palette-common (shared across all ef-themes) ---
  fringe: UNSPEC,
  property: "variable",
  "fg-region": UNSPEC,
  "fg-link-symbolic": "fg-alt",
  "underline-link": "border",
  "underline-link-visited": "border",
  "underline-link-symbolic": "border",
  "bg-line-number-active": UNSPEC,
  "fg-line-number-active": "accent-0",
  "bg-line-number-inactive": UNSPEC,
  "bg-prominent-err": "bg-err",
  "bg-prominent-warning": "bg-warning",
  "bg-prominent-note": "bg-info",
  "fg-prominent-err": "err",
  "fg-prominent-warning": "warning",
  "fg-prominent-note": "info",
  "bg-space": UNSPEC,
  "fg-space": "border",
  "bg-active-argument": "bg-warning",
  "fg-active-argument": "warning",
  "bg-active-value": "bg-info",
  "fg-active-value": "info",
  "bg-mark-delete": "bg-err",
  "fg-mark-delete": "err",
  "bg-mark-select": "bg-info",
  "fg-mark-select": "info",
  "bg-mark-other": "bg-warning",
  "fg-mark-other": "warning",
  "fg-search-current": "fg-main",
  "fg-search-lazy": "fg-main",
  "fg-search-static": "fg-main",
  "fg-search-replace": "fg-main",
  "fg-search-rx-group-0": "fg-main",
  "fg-search-rx-group-1": "fg-main",
  "fg-search-rx-group-2": "fg-main",
  "fg-search-rx-group-3": "fg-main",
  "fg-completion-match-0": "accent-0",
  "fg-completion-match-1": "accent-1",
  "fg-completion-match-2": "accent-2",
  "fg-completion-match-3": "accent-3",
  "fg-heading-0": "rainbow-0",
  "fg-heading-1": "rainbow-1",
  "fg-heading-2": "rainbow-2",
  "fg-heading-3": "rainbow-3",
  "fg-heading-4": "rainbow-4",
  "fg-heading-5": "rainbow-5",
  "fg-heading-6": "rainbow-6",
  "fg-heading-7": "rainbow-7",
  "fg-heading-8": "rainbow-8",
};

export const efNight: ThemeDoc = {
  meta: {
    name: "ef-night",
    description: "Legible dark sky blue theme with mostly green, blue, purple colors.",
    mode: "dark",
  },
  palette,
  mappings,
};
