// ef-orange (light) — bundled preset, both layers.
//
// The ef-themes are built on top of the modus-themes (since ef-themes 2.0.0):
// they use the same `modus-themes-theme` macro and palette structure. This seed
// is a faithful port so it can be edited and exported as a self-contained
// modus-themes derivative (no ef-themes dependency at load time).
//
// Transcribed verbatim from ef-orange-theme.el + ef-themes.el upstream:
//   - ef-orange-palette-partial            (named colors)
//   - ef-orange-palette-mappings-partial   (theme-specific mappings)
//   - ef-themes-palette-common            (shared mappings, appended)
// To refresh: re-transcribe from https://github.com/protesilaos/ef-themes
//
// A few shared entries (mode-line, tab-bar, bg-diff-context) are layer-1 colors
// in this model but defined upstream as mappings to other named colors; they are
// resolved to hex and placed in the palette block. All other mappings are kept
// symbolic, so resolve.ts follows the indirection as the modus engine does.

import { UNSPECIFIED as UNSPEC } from "./resolve.ts";
import type { Mapping, Palette, ThemeDoc } from "./types.ts";

const palette: Palette = {
  cursor: "#cf5f00",
  "bg-main": "#ffedc9",
  "bg-dim": "#f7e5b6",
  "bg-alt": "#e9d0a8",
  "fg-main": "#6c4631",
  "fg-dim": "#6f6a70",
  "fg-alt": "#8f5f4a",
  "bg-active": "#c9b088",
  "bg-inactive": "#efdbac",
  border: "#cfbe9b",
  red: "#ba2d2f",
  "red-warmer": "#c13f00",
  "red-cooler": "#cf2030",
  "red-faint": "#b04340",
  green: "#007a0a",
  "green-warmer": "#5f7200",
  "green-cooler": "#2f783f",
  "green-faint": "#527545",
  yellow: "#a05a22",
  "yellow-warmer": "#b05115",
  "yellow-cooler": "#aa4f30",
  "yellow-faint": "#93604a",
  blue: "#375cc6",
  "blue-warmer": "#5f50df",
  "blue-cooler": "#265fbf",
  "blue-faint": "#4a659f",
  magenta: "#ba3e54",
  "magenta-warmer": "#c32f80",
  "magenta-cooler": "#8448aa",
  "magenta-faint": "#a04450",
  cyan: "#467080",
  "cyan-warmer": "#3f6fa2",
  "cyan-cooler": "#0f738f",
  "cyan-faint": "#4f6f8f",
  "bg-red-intense": "#f3a058",
  "bg-green-intense": "#a6df70",
  "bg-yellow-intense": "#efcf00",
  "bg-blue-intense": "#90b5e0",
  "bg-magenta-intense": "#ef9fbf",
  "bg-cyan-intense": "#98cfc0",
  "bg-red-subtle": "#f2c3b0",
  "bg-green-subtle": "#cbe08f",
  "bg-yellow-subtle": "#f0e76e",
  "bg-blue-subtle": "#c6deeb",
  "bg-magenta-subtle": "#eac7cf",
  "bg-cyan-subtle": "#bfe2d0",
  "bg-added": "#d7e890",
  "bg-added-faint": "#e2eba6",
  "bg-added-refine": "#c2d580",
  "fg-added": "#2f6500",
  "bg-changed": "#f5e690",
  "bg-changed-faint": "#f5edaf",
  "bg-changed-refine": "#edd482",
  "fg-changed": "#553d00",
  "bg-removed": "#ffd090",
  "bg-removed-faint": "#f5de9f",
  "bg-removed-refine": "#f0b972",
  "fg-removed": "#9f2f00",
  "bg-mode-line-active": "#ffc255",
  "fg-mode-line-active": "#742f18",
  "bg-completion": "#f3d0aa",
  "bg-popup": "#ffe5c9",
  "bg-hover": "#c0e47f",
  "bg-hover-secondary": "#ebdc8f",
  "bg-hl-line": "#ffdaa6",
  "bg-paren-match": "#8fcf7f",
  "bg-err": "#ffcc95",
  "bg-warning": "#ecdc7a",
  "bg-info": "#dde58c",
  "bg-region": "#eeb48f",
  "bg-diff-context": "#f7e5b6", // ef-common mapping resolved
  "bg-tab-bar": "#e9d0a8", // ef-common mapping resolved
  "bg-tab-current": "#ffedc9", // ef-common mapping resolved
  "bg-tab-other": "#c9b088", // ef-common mapping resolved
  "border-mode-line-active": "#cfbe9b", // ef-common mapping resolved
  "bg-mode-line-inactive": "#e9d0a8", // ef-common mapping resolved
  "fg-mode-line-inactive": "#6f6a70", // ef-common mapping resolved
  "border-mode-line-inactive": "#cfbe9b", // ef-common mapping resolved
};

const mappings: Mapping = {
  // --- ef-orange-palette-mappings-partial ---
  err: "red-warmer",
  warning: "yellow",
  info: "green-warmer",
  "fg-link": "green-warmer",
  "fg-link-visited": "red-faint",
  name: "yellow",
  keybind: "red-warmer",
  identifier: "yellow-faint",
  "fg-prompt": "green",
  builtin: "red",
  comment: "fg-dim",
  constant: "yellow",
  fnname: "red-cooler",
  "fnname-call": "magenta-faint",
  keyword: "red-warmer",
  preprocessor: "cyan-warmer",
  docstring: "green-faint",
  string: "green-warmer",
  type: "yellow-cooler",
  variable: "green-cooler",
  "variable-use": "cyan-faint",
  "rx-backslash": "green-cooler",
  "rx-construct": "red-warmer",
  "accent-0": "red-warmer",
  "accent-1": "green-cooler",
  "accent-2": "yellow",
  "accent-3": "green-warmer",
  "date-common": "green-faint",
  "date-deadline": "red",
  "date-deadline-subtle": "red-faint",
  "date-event": "fg-alt",
  "date-holiday": "red-warmer",
  "date-now": "fg-main",
  "date-range": "fg-alt",
  "date-scheduled": "yellow",
  "date-scheduled-subtle": "yellow-faint",
  "date-weekday": "green-warmer",
  "date-weekend": "red-faint",
  "fg-prose-code": "green-cooler",
  "prose-done": "green",
  "fg-prose-macro": "yellow",
  "prose-metadata": "fg-dim",
  "prose-metadata-value": "fg-alt",
  "prose-table": "fg-alt",
  "prose-table-formula": "info",
  "prose-tag": "yellow-faint",
  "prose-todo": "red-warmer",
  "fg-prose-verbatim": "red",
  "mail-cite-0": "yellow-cooler",
  "mail-cite-1": "green-faint",
  "mail-cite-2": "red-cooler",
  "mail-cite-3": "fg-alt",
  "mail-part": "red-faint",
  "mail-recipient": "yellow",
  "mail-subject": "red-warmer",
  "mail-other": "green-cooler",
  "bg-search-static": "bg-warning",
  "bg-search-current": "bg-yellow-intense",
  "bg-search-lazy": "bg-green-intense",
  "bg-search-replace": "bg-red-intense",
  "bg-search-rx-group-0": "bg-yellow-intense",
  "bg-search-rx-group-1": "bg-magenta-intense",
  "bg-search-rx-group-2": "bg-green-subtle",
  "bg-search-rx-group-3": "bg-blue-subtle",
  "bg-space-err": "bg-yellow-intense",
  "rainbow-0": "red-warmer",
  "rainbow-1": "yellow-warmer",
  "rainbow-2": "green-warmer",
  "rainbow-3": "yellow-cooler",
  "rainbow-4": "green-cooler",
  "rainbow-5": "yellow",
  "rainbow-6": "red-faint",
  "rainbow-7": "green-faint",
  "rainbow-8": "red-faint",

  // --- ef-themes-palette-common (shared across all ef-themes) ---
  fringe: UNSPEC,
  property: "variable",
  "fg-region": UNSPEC,
  "fg-link-symbolic": "fg-alt",
  "underline-link": "border",
  "underline-link-visited": "border",
  "underline-link-symbolic": "border",
  "bg-line-number-active": UNSPEC,
  "fg-line-number-active": "accent-0",
  "bg-line-number-inactive": UNSPEC,
  "bg-prominent-err": "bg-err",
  "bg-prominent-warning": "bg-warning",
  "bg-prominent-note": "bg-info",
  "fg-prominent-err": "err",
  "fg-prominent-warning": "warning",
  "fg-prominent-note": "info",
  "bg-space": UNSPEC,
  "fg-space": "border",
  "bg-active-argument": "bg-warning",
  "fg-active-argument": "warning",
  "bg-active-value": "bg-info",
  "fg-active-value": "info",
  "bg-mark-delete": "bg-err",
  "fg-mark-delete": "err",
  "bg-mark-select": "bg-info",
  "fg-mark-select": "info",
  "bg-mark-other": "bg-warning",
  "fg-mark-other": "warning",
  "fg-search-current": "fg-main",
  "fg-search-lazy": "fg-main",
  "fg-search-static": "fg-main",
  "fg-search-replace": "fg-main",
  "fg-search-rx-group-0": "fg-main",
  "fg-search-rx-group-1": "fg-main",
  "fg-search-rx-group-2": "fg-main",
  "fg-search-rx-group-3": "fg-main",
  "fg-completion-match-0": "accent-0",
  "fg-completion-match-1": "accent-1",
  "fg-completion-match-2": "accent-2",
  "fg-completion-match-3": "accent-3",
  "fg-heading-0": "rainbow-0",
  "fg-heading-1": "rainbow-1",
  "fg-heading-2": "rainbow-2",
  "fg-heading-3": "rainbow-3",
  "fg-heading-4": "rainbow-4",
  "fg-heading-5": "rainbow-5",
  "fg-heading-6": "rainbow-6",
  "fg-heading-7": "rainbow-7",
  "fg-heading-8": "rainbow-8",
};

export const efOrange: ThemeDoc = {
  meta: {
    name: "ef-orange",
    description: "Legible light theme with orange, yellow, and green colors.",
    mode: "light",
  },
  palette,
  mappings,
};
