// Ef Summer (light) — bundled preset, both layers.
//
// The ef-themes are built on top of the modus-themes (since ef-themes 2.0.0):
// they use the same `modus-themes-theme` macro and palette structure. This seed
// is a faithful port of ef-summer so it can be edited and exported as a
// self-contained modus-themes derivative (no ef-themes dependency at load time).
//
// Transcribed verbatim from ef-summer-theme.el + ef-themes.el upstream:
//   - ef-summer-palette-partial            (named colors)
//   - ef-summer-palette-mappings-partial   (theme-specific mappings)
//   - ef-themes-palette-common             (shared mappings, appended)
// To refresh: re-transcribe from
//   https://github.com/protesilaos/ef-themes
//
// Some shared mappings point one role at another (e.g. fg-heading-0 -> rainbow-0,
// fg-completion-match-0 -> accent-0). That role->role indirection is resolved by
// resolve.ts and by the modus-themes engine, so it is preserved here verbatim.

import { UNSPECIFIED as UNSPEC } from "./resolve.ts";
import type { Mapping, Palette, ThemeDoc } from "./types.ts";

const palette: Palette = {
  cursor: "#cf0090",
  "bg-main": "#fff2f3",
  "bg-dim": "#f2e4ea",
  "bg-alt": "#efd3e4",
  "fg-main": "#4f4073",
  "fg-dim": "#786e74",
  "fg-alt": "#af4988",
  "bg-active": "#cfb3c4",
  "bg-inactive": "#efe2e5",
  border: "#c6bbc6",
  red: "#d3303a",
  "red-warmer": "#e00033",
  "red-cooler": "#d50f7f",
  "red-faint": "#c24552",
  "red-intense": "#d63a44",
  green: "#217a3c",
  "green-warmer": "#4a7d00",
  "green-cooler": "#007f68",
  "green-faint": "#61756c",
  "green-intense": "#22803f",
  yellow: "#a45f22",
  "yellow-warmer": "#b6532f",
  "yellow-cooler": "#b65050",
  "yellow-faint": "#9a5f6a",
  "yellow-intense": "#ac6423",
  blue: "#375ce6",
  "blue-warmer": "#5250ef",
  "blue-cooler": "#065fff",
  "blue-faint": "#6060d0",
  "blue-intense": "#4366e8",
  magenta: "#ba35af",
  "magenta-warmer": "#cb1aaa",
  "magenta-cooler": "#8e44f3",
  "magenta-faint": "#a45392",
  "magenta-intense": "#c437b8",
  cyan: "#1f6fbf",
  "cyan-warmer": "#3f6faf",
  "cyan-cooler": "#0f7b8f",
  "cyan-faint": "#5f60bf",
  "cyan-intense": "#2075c9",
  rust: "#8a290f",
  gold: "#6c501c",
  olive: "#425d00",
  slate: "#2f3f83",
  indigo: "#4a3a8a",
  maroon: "#731c52",
  pink: "#7b435c",
  "bg-red-intense": "#ff7f88",
  "bg-green-intense": "#86df80",
  "bg-yellow-intense": "#ffc200",
  "bg-blue-intense": "#cbcfff",
  "bg-magenta-intense": "#df8fff",
  "bg-cyan-intense": "#88ccff",
  "bg-red-subtle": "#fbc3cf",
  "bg-green-subtle": "#b9edca",
  "bg-yellow-subtle": "#f7e78f",
  "bg-blue-subtle": "#ccdfff",
  "bg-magenta-subtle": "#facdf5",
  "bg-cyan-subtle": "#c2ecf0",
  "bg-red-nuanced": "#f8dbdd",
  "bg-green-nuanced": "#49ce71",
  "bg-yellow-nuanced": "#e5af80",
  "bg-blue-nuanced": "#ffffff",
  "bg-magenta-nuanced": "#eec1ea",
  "bg-cyan-nuanced": "#a0c8f0",
  "bg-clay": "#f1c8b5",
  "fg-clay": "#63192a",
  "bg-ochre": "#f0e3c0",
  "fg-ochre": "#573a30",
  "bg-lavender": "#dfcdfa",
  "fg-lavender": "#443379",
  "bg-sage": "#c0e7d4",
  "fg-sage": "#124b41",
  "bg-graph-red-0": "#ef7969",
  "bg-graph-red-1": "#ffaab4",
  "bg-graph-green-0": "#45c050",
  "bg-graph-green-1": "#75ef30",
  "bg-graph-yellow-0": "#ffcf00",
  "bg-graph-yellow-1": "#f9ff00",
  "bg-graph-blue-0": "#7f90ff",
  "bg-graph-blue-1": "#a6c0ff",
  "bg-graph-magenta-0": "#e07fff",
  "bg-graph-magenta-1": "#fad0ff",
  "bg-graph-cyan-0": "#70d3f0",
  "bg-graph-cyan-1": "#afefff",
  "bg-completion": "#f4cfef",
  "bg-popup": "#ffe3ec",
  "bg-hover": "#b4cfff",
  "bg-hover-secondary": "#aaeccf",
  "bg-hl-line": "#ffd6e5",
  "bg-region": "#eecfff",
  "bg-err": "#ffd0e6",
  "bg-warning": "#ffe5ba",
  "bg-info": "#bbefda",
  "bg-mode-line-active": "#ffa4dc",
  "fg-mode-line-active": "#341f58",
  "bg-mode-line-inactive": "#efd3e4", // ef-common mapping resolved
  "fg-mode-line-inactive": "#786e74", // ef-common mapping resolved
  "border-mode-line-active": "#c6bbc6", // ef-common mapping resolved
  "border-mode-line-inactive": "#c6bbc6", // ef-common mapping resolved
  "bg-tab-bar": "#efd3e4", // ef-common mapping resolved
  "bg-tab-current": "#fff2f3", // ef-common mapping resolved
  "bg-tab-other": "#cfb3c4", // ef-common mapping resolved
  "bg-added": "#caf4da",
  "bg-added-faint": "#dff6ea",
  "bg-added-refine": "#bae9cf",
  "bg-added-fringe": "#6cc06c",
  "fg-added": "#005000",
  "bg-changed": "#ffdfb9",
  "bg-changed-faint": "#ffefcb",
  "bg-changed-refine": "#ffcfa0",
  "bg-changed-fringe": "#c0b200",
  "fg-changed": "#553d00",
  "bg-removed": "#ffcee0",
  "bg-removed-faint": "#ffdfe6",
  "bg-removed-refine": "#f5b6c8",
  "bg-removed-fringe": "#d84a4f",
  "fg-removed": "#8f1313",
  "bg-diff-context": "#efe9df",
  "bg-paren-match": "#9fc0ef",
};

const mappings: Mapping = {
  // --- ef-summer-palette-mappings-partial ---
  err: "red-warmer",
  warning: "yellow",
  info: "green-cooler",
  "fg-link": "blue",
  "fg-link-visited": "green-cooler",
  name: "magenta-warmer",
  keybind: "red-cooler",
  identifier: "magenta-faint",
  "fg-prompt": "magenta-warmer",
  builtin: "magenta",
  comment: "yellow-faint",
  constant: "red-cooler",
  fnname: "magenta-warmer",
  "fnname-call": "magenta-faint",
  keyword: "magenta-cooler",
  preprocessor: "green-cooler",
  docstring: "cyan-faint",
  string: "yellow-warmer",
  type: "cyan-warmer",
  variable: "blue-warmer",
  "variable-use": "blue-faint",
  "rx-backslash": "cyan-cooler",
  "rx-construct": "red-cooler",

  "accent-0": "magenta-cooler",
  "accent-1": "yellow",
  "accent-2": "cyan-cooler",
  "accent-3": "red",

  "date-common": "cyan-cooler",
  "date-deadline": "red-warmer",
  "date-deadline-subtle": "red-faint",
  "date-event": "fg-alt",
  "date-holiday": "magenta-warmer",
  "date-now": "fg-main",
  "date-range": "fg-alt",
  "date-scheduled": "yellow",
  "date-scheduled-subtle": "yellow-faint",
  "date-weekday": "cyan",
  "date-weekend": "red-faint",

  "fg-prose-code": "yellow",
  "prose-done": "green-cooler",
  "fg-prose-macro": "cyan-cooler",
  "prose-metadata": "fg-dim",
  "prose-metadata-value": "fg-alt",
  "prose-table": "fg-alt",
  "prose-table-formula": "info",
  "prose-tag": "yellow-faint",
  "prose-todo": "red-warmer",
  "fg-prose-verbatim": "magenta-cooler",

  "mail-cite-0": "yellow-cooler",
  "mail-cite-1": "magenta",
  "mail-cite-2": "blue-warmer",
  "mail-cite-3": "cyan-warmer",
  "mail-part": "magenta-faint",
  "mail-recipient": "magenta-warmer",
  "mail-subject": "magenta-cooler",
  "mail-other": "magenta",

  "bg-search-static": "bg-warning",
  "bg-search-current": "bg-yellow-intense",
  "bg-search-lazy": "bg-blue-intense",
  "bg-search-replace": "bg-red-intense",
  "bg-search-rx-group-0": "bg-magenta-intense",
  "bg-search-rx-group-1": "bg-green-intense",
  "bg-search-rx-group-2": "bg-red-subtle",
  "bg-search-rx-group-3": "bg-cyan-subtle",

  "rainbow-0": "magenta-warmer",
  "rainbow-1": "magenta-cooler",
  "rainbow-2": "yellow",
  "rainbow-3": "cyan",
  "rainbow-4": "magenta",
  "rainbow-5": "blue-warmer",
  "rainbow-6": "red-cooler",
  "rainbow-7": "cyan-cooler",
  "rainbow-8": "yellow-cooler",

  // --- ef-themes-palette-common (shared across all ef-themes) ---
  fringe: UNSPEC,
  property: "variable",
  "fg-region": UNSPEC,
  "fg-link-symbolic": "fg-alt",
  "underline-link": "border",
  "underline-link-visited": "border",
  "underline-link-symbolic": "border",
  "fg-mode-line-active": "fg-main",
  "bg-line-number-active": UNSPEC,
  "fg-line-number-active": "accent-0",
  "bg-line-number-inactive": UNSPEC,
  "fg-line-number-inactive": "fg-dim",
  "bg-prominent-err": "bg-err",
  "bg-prominent-warning": "bg-warning",
  "bg-prominent-note": "bg-info",
  "fg-prominent-err": "err",
  "fg-prominent-warning": "warning",
  "fg-prominent-note": "info",
  "bg-space": UNSPEC,
  "fg-space": "border",
  "bg-active-argument": "bg-warning",
  "fg-active-argument": "warning",
  "bg-active-value": "bg-info",
  "fg-active-value": "info",
  "bg-mark-delete": "bg-err",
  "fg-mark-delete": "err",
  "bg-mark-select": "bg-info",
  "fg-mark-select": "info",
  "bg-mark-other": "bg-warning",
  "fg-mark-other": "warning",
  "fg-search-current": "fg-main",
  "fg-search-lazy": "fg-main",
  "fg-search-static": "fg-main",
  "fg-search-replace": "fg-main",
  "fg-search-rx-group-0": "fg-main",
  "fg-search-rx-group-1": "fg-main",
  "fg-search-rx-group-2": "fg-main",
  "fg-search-rx-group-3": "fg-main",
  "fg-completion-match-0": "accent-0",
  "fg-completion-match-1": "accent-1",
  "fg-completion-match-2": "accent-2",
  "fg-completion-match-3": "accent-3",
  "fg-heading-0": "rainbow-0",
  "fg-heading-1": "rainbow-1",
  "fg-heading-2": "rainbow-2",
  "fg-heading-3": "rainbow-3",
  "fg-heading-4": "rainbow-4",
  "fg-heading-5": "rainbow-5",
  "fg-heading-6": "rainbow-6",
  "fg-heading-7": "rainbow-7",
  "fg-heading-8": "rainbow-8",
};

export const efSummer: ThemeDoc = {
  meta: {
    name: "ef-summer",
    description: "Legible light warm pink theme with magenta, purple, gold, cyan colors.",
    mode: "light",
  },
  palette,
  mappings,
};
