// ef-spring (light) — bundled preset, both layers.
//
// The ef-themes are built on top of the modus-themes (since ef-themes 2.0.0):
// they use the same `modus-themes-theme` macro and palette structure. This seed
// is a faithful port so it can be edited and exported as a self-contained
// modus-themes derivative (no ef-themes dependency at load time).
//
// Transcribed verbatim from ef-spring-theme.el + ef-themes.el upstream:
//   - ef-spring-palette-partial            (named colors)
//   - ef-spring-palette-mappings-partial   (theme-specific mappings)
//   - ef-themes-palette-common            (shared mappings, appended)
// To refresh: re-transcribe from https://github.com/protesilaos/ef-themes
//
// A few shared entries (mode-line, tab-bar, bg-diff-context) are layer-1 colors
// in this model but defined upstream as mappings to other named colors; they are
// resolved to hex and placed in the palette block. All other mappings are kept
// symbolic, so resolve.ts follows the indirection as the modus engine does.

import { UNSPECIFIED as UNSPEC } from "./resolve.ts";
import type { Mapping, Palette, ThemeDoc } from "./types.ts";

const palette: Palette = {
  cursor: "#bf005f",
  "bg-main": "#f6fff9",
  "bg-dim": "#e8f0f0",
  "bg-alt": "#e0e6e3",
  "fg-main": "#34494a",
  "fg-dim": "#777294",
  "fg-alt": "#9d5e7a",
  "bg-active": "#c0c6c3",
  "bg-inactive": "#eaf0e9",
  border: "#b4c4c0",
  red: "#c42d2f",
  "red-warmer": "#d03003",
  "red-cooler": "#cf2f4f",
  "red-faint": "#b64850",
  green: "#1a870f",
  "green-warmer": "#4a7d00",
  "green-cooler": "#007f68",
  "green-faint": "#61756c",
  yellow: "#a45f22",
  "yellow-warmer": "#b6540f",
  "yellow-cooler": "#ae5a30",
  "yellow-faint": "#876450",
  blue: "#375cc6",
  "blue-warmer": "#5f5fdf",
  "blue-cooler": "#265fbf",
  "blue-faint": "#6a65bf",
  magenta: "#d5206f",
  "magenta-warmer": "#cb26a0",
  "magenta-cooler": "#9435b4",
  "magenta-faint": "#a04360",
  cyan: "#1f6fbf",
  "cyan-warmer": "#3f6faf",
  "cyan-cooler": "#0f7b8f",
  "cyan-faint": "#5f6abf",
  "bg-red-intense": "#ff8f88",
  "bg-green-intense": "#7fdda0",
  "bg-yellow-intense": "#efcf00",
  "bg-blue-intense": "#afdfff",
  "bg-magenta-intense": "#df8fff",
  "bg-cyan-intense": "#80caf0",
  "bg-red-subtle": "#ffcfbf",
  "bg-green-subtle": "#b2faa5",
  "bg-yellow-subtle": "#f0f37f",
  "bg-blue-subtle": "#ccdfff",
  "bg-magenta-subtle": "#ffddff",
  "bg-cyan-subtle": "#bfefff",
  "bg-added": "#c9ffda",
  "bg-added-faint": "#d7ffe5",
  "bg-added-refine": "#b3efcf",
  "fg-added": "#005000",
  "bg-changed": "#f0e8bd",
  "bg-changed-faint": "#f5efcb",
  "bg-changed-refine": "#efd299",
  "fg-changed": "#553d00",
  "bg-removed": "#ffd6e0",
  "bg-removed-faint": "#ffe9e6",
  "bg-removed-refine": "#f5bfc8",
  "fg-removed": "#8f1313",
  "bg-mode-line-active": "#90e8b0",
  "fg-mode-line-active": "#243228",
  "bg-completion": "#d3e4f0",
  "bg-popup": "#edf2e9",
  "bg-hover": "#ffc09f",
  "bg-hover-secondary": "#f0bfff",
  "bg-hl-line": "#f9e0e5",
  "bg-paren-match": "#7fddd0",
  "bg-err": "#ffe8e0",
  "bg-warning": "#ffecba",
  "bg-info": "#ccf5dd",
  "bg-region": "#d0e6ff",
  "bg-diff-context": "#e8f0f0", // ef-common mapping resolved
  "bg-tab-bar": "#e0e6e3", // ef-common mapping resolved
  "bg-tab-current": "#f6fff9", // ef-common mapping resolved
  "bg-tab-other": "#c0c6c3", // ef-common mapping resolved
  "border-mode-line-active": "#b4c4c0", // ef-common mapping resolved
  "bg-mode-line-inactive": "#e0e6e3", // ef-common mapping resolved
  "fg-mode-line-inactive": "#777294", // ef-common mapping resolved
  "border-mode-line-inactive": "#b4c4c0", // ef-common mapping resolved
};

const mappings: Mapping = {
  // --- ef-spring-palette-mappings-partial ---
  err: "red-warmer",
  warning: "yellow",
  info: "green",
  "fg-link": "cyan-cooler",
  "fg-link-visited": "yellow-cooler",
  name: "green-cooler",
  keybind: "magenta-warmer",
  identifier: "magenta-faint",
  "fg-prompt": "green",
  builtin: "green",
  comment: "yellow-faint",
  constant: "red-warmer",
  fnname: "green-warmer",
  "fnname-call": "green-faint",
  keyword: "green-cooler",
  preprocessor: "magenta-warmer",
  docstring: "magenta-faint",
  string: "yellow-warmer",
  type: "magenta-cooler",
  variable: "cyan",
  "variable-use": "cyan-faint",
  "rx-backslash": "cyan",
  "rx-construct": "magenta-warmer",
  "accent-0": "green",
  "accent-1": "red-cooler",
  "accent-2": "blue",
  "accent-3": "yellow-warmer",
  "date-common": "cyan",
  "date-deadline": "red-warmer",
  "date-deadline-subtle": "red-faint",
  "date-event": "fg-alt",
  "date-holiday": "magenta-warmer",
  "date-now": "fg-main",
  "date-range": "fg-alt",
  "date-scheduled": "yellow",
  "date-scheduled-subtle": "yellow-faint",
  "date-weekday": "cyan",
  "date-weekend": "red-faint",
  "fg-prose-code": "red-cooler",
  "prose-done": "green",
  "fg-prose-macro": "blue",
  "prose-metadata": "fg-dim",
  "prose-metadata-value": "fg-alt",
  "prose-table": "fg-alt",
  "prose-table-formula": "info",
  "prose-tag": "magenta-faint",
  "prose-todo": "red-warmer",
  "fg-prose-verbatim": "green",
  "mail-cite-0": "green",
  "mail-cite-1": "yellow-cooler",
  "mail-cite-2": "blue-warmer",
  "mail-cite-3": "magenta-cooler",
  "mail-part": "green-warmer",
  "mail-recipient": "green-cooler",
  "mail-subject": "cyan",
  "mail-other": "cyan-cooler",
  "bg-search-static": "bg-warning",
  "bg-search-current": "bg-yellow-intense",
  "bg-search-lazy": "bg-blue-intense",
  "bg-search-replace": "bg-red-intense",
  "bg-search-rx-group-0": "bg-magenta-intense",
  "bg-search-rx-group-1": "bg-green-intense",
  "bg-search-rx-group-2": "bg-red-subtle",
  "bg-search-rx-group-3": "bg-cyan-subtle",
  "bg-space-err": "bg-yellow-intense",
  "rainbow-0": "red-cooler",
  "rainbow-1": "green-cooler",
  "rainbow-2": "magenta-warmer",
  "rainbow-3": "blue-warmer",
  "rainbow-4": "yellow-warmer",
  "rainbow-5": "cyan",
  "rainbow-6": "magenta",
  "rainbow-7": "magenta-cooler",
  "rainbow-8": "yellow-cooler",

  // --- ef-themes-palette-common (shared across all ef-themes) ---
  fringe: UNSPEC,
  property: "variable",
  "fg-region": UNSPEC,
  "fg-link-symbolic": "fg-alt",
  "underline-link": "border",
  "underline-link-visited": "border",
  "underline-link-symbolic": "border",
  "bg-line-number-active": UNSPEC,
  "fg-line-number-active": "accent-0",
  "bg-line-number-inactive": UNSPEC,
  "bg-prominent-err": "bg-err",
  "bg-prominent-warning": "bg-warning",
  "bg-prominent-note": "bg-info",
  "fg-prominent-err": "err",
  "fg-prominent-warning": "warning",
  "fg-prominent-note": "info",
  "bg-space": UNSPEC,
  "fg-space": "border",
  "bg-active-argument": "bg-warning",
  "fg-active-argument": "warning",
  "bg-active-value": "bg-info",
  "fg-active-value": "info",
  "bg-mark-delete": "bg-err",
  "fg-mark-delete": "err",
  "bg-mark-select": "bg-info",
  "fg-mark-select": "info",
  "bg-mark-other": "bg-warning",
  "fg-mark-other": "warning",
  "fg-search-current": "fg-main",
  "fg-search-lazy": "fg-main",
  "fg-search-static": "fg-main",
  "fg-search-replace": "fg-main",
  "fg-search-rx-group-0": "fg-main",
  "fg-search-rx-group-1": "fg-main",
  "fg-search-rx-group-2": "fg-main",
  "fg-search-rx-group-3": "fg-main",
  "fg-completion-match-0": "accent-0",
  "fg-completion-match-1": "accent-1",
  "fg-completion-match-2": "accent-2",
  "fg-completion-match-3": "accent-3",
  "fg-heading-0": "rainbow-0",
  "fg-heading-1": "rainbow-1",
  "fg-heading-2": "rainbow-2",
  "fg-heading-3": "rainbow-3",
  "fg-heading-4": "rainbow-4",
  "fg-heading-5": "rainbow-5",
  "fg-heading-6": "rainbow-6",
  "fg-heading-7": "rainbow-7",
  "fg-heading-8": "rainbow-8",
};

export const efSpring: ThemeDoc = {
  meta: {
    name: "ef-spring",
    description: "Legible light floral theme with cool, varied colors (green, cyan, red).",
    mode: "light",
  },
  palette,
  mappings,
};
