// ef-symbiosis (dark) — bundled preset, both layers.
//
// The ef-themes are built on top of the modus-themes (since ef-themes 2.0.0):
// they use the same `modus-themes-theme` macro and palette structure. This seed
// is a faithful port so it can be edited and exported as a self-contained
// modus-themes derivative (no ef-themes dependency at load time).
//
// Transcribed verbatim from ef-symbiosis-theme.el + ef-themes.el upstream:
//   - ef-symbiosis-palette-partial            (named colors)
//   - ef-symbiosis-palette-mappings-partial   (theme-specific mappings)
//   - ef-themes-palette-common            (shared mappings, appended)
// To refresh: re-transcribe from https://github.com/protesilaos/ef-themes
//
// A few shared entries (mode-line, tab-bar, bg-diff-context) are layer-1 colors
// in this model but defined upstream as mappings to other named colors; they are
// resolved to hex and placed in the palette block. All other mappings are kept
// symbolic, so resolve.ts follows the indirection as the modus engine does.

import { UNSPECIFIED as UNSPEC } from "./resolve.ts";
import type { Mapping, Palette, ThemeDoc } from "./types.ts";

const palette: Palette = {
  cursor: "#f0af7f",
  "bg-main": "#130911",
  "bg-dim": "#221920",
  "bg-alt": "#372d32",
  "fg-main": "#d0d0d0",
  "fg-dim": "#857f8f",
  "fg-alt": "#89afef",
  "bg-active": "#4b3f47",
  "bg-inactive": "#292327",
  border: "#4d4a4b",
  red: "#ef6360",
  "red-warmer": "#ff7355",
  "red-cooler": "#fe5a7a",
  "red-faint": "#d56f72",
  green: "#0faa26",
  "green-warmer": "#6aad0f",
  "green-cooler": "#00a692",
  "green-faint": "#61a06c",
  yellow: "#bf9032",
  "yellow-warmer": "#d1843f",
  "yellow-cooler": "#df8a5a",
  "yellow-faint": "#cf9f8f",
  blue: "#3f95f6",
  "blue-warmer": "#6a9fff",
  "blue-cooler": "#029fff",
  "blue-faint": "#7a94df",
  magenta: "#d369af",
  "magenta-warmer": "#e580ea",
  "magenta-cooler": "#af85ff",
  "magenta-faint": "#c58faf",
  cyan: "#4fbaef",
  "cyan-warmer": "#6fafff",
  "cyan-cooler": "#1dbfcf",
  "cyan-faint": "#8aa0df",
  "bg-red-intense": "#b02930",
  "bg-green-intense": "#4a7100",
  "bg-yellow-intense": "#8f5040",
  "bg-blue-intense": "#4648d0",
  "bg-magenta-intense": "#804fdf",
  "bg-cyan-intense": "#2270cf",
  "bg-red-subtle": "#6f1f2a",
  "bg-green-subtle": "#1f462f",
  "bg-yellow-subtle": "#5a372f",
  "bg-blue-subtle": "#2f366a",
  "bg-magenta-subtle": "#582650",
  "bg-cyan-subtle": "#1c4256",
  "bg-added": "#233b0f",
  "bg-added-faint": "#102a00",
  "bg-added-refine": "#2f512f",
  "fg-added": "#a0e0a0",
  "bg-changed": "#363300",
  "bg-changed-faint": "#2a1f00",
  "bg-changed-refine": "#4a4a00",
  "fg-changed": "#efef80",
  "bg-removed": "#4e111f",
  "bg-removed-faint": "#380a0f",
  "bg-removed-refine": "#751a1f",
  "fg-removed": "#ffbfbf",
  "bg-mode-line-active": "#583435",
  "fg-mode-line-active": "#ffe5f0",
  "bg-completion": "#213953",
  "bg-popup": "#23101f",
  "bg-hover": "#304477",
  "bg-hover-secondary": "#5f3f3a",
  "bg-hl-line": "#1f2f3f",
  "bg-paren-match": "#005f4a",
  "bg-err": "#461309",
  "bg-warning": "#3a3104",
  "bg-info": "#163505",
  "bg-region": "#3f2f40",
  "bg-diff-context": "#221920", // ef-common mapping resolved
  "bg-tab-bar": "#372d32", // ef-common mapping resolved
  "bg-tab-current": "#130911", // ef-common mapping resolved
  "bg-tab-other": "#4b3f47", // ef-common mapping resolved
  "border-mode-line-active": "#4d4a4b", // ef-common mapping resolved
  "bg-mode-line-inactive": "#372d32", // ef-common mapping resolved
  "fg-mode-line-inactive": "#857f8f", // ef-common mapping resolved
  "border-mode-line-inactive": "#4d4a4b", // ef-common mapping resolved
};

const mappings: Mapping = {
  // --- ef-symbiosis-palette-mappings-partial ---
  err: "red-warmer",
  warning: "yellow",
  info: "green",
  "fg-link": "cyan",
  "fg-link-visited": "magenta-cooler",
  name: "blue",
  keybind: "yellow-cooler",
  identifier: "yellow-faint",
  "fg-prompt": "cyan",
  builtin: "blue",
  comment: "fg-dim",
  constant: "cyan-cooler",
  fnname: "magenta-cooler",
  "fnname-call": "magenta-faint",
  keyword: "green-warmer",
  preprocessor: "red",
  docstring: "yellow-faint",
  string: "yellow-cooler",
  type: "green-cooler",
  variable: "blue-warmer",
  "variable-use": "blue-faint",
  "rx-backslash": "green-cooler",
  "rx-construct": "red",
  "accent-0": "cyan",
  "accent-1": "yellow-warmer",
  "accent-2": "green-warmer",
  "accent-3": "magenta-cooler",
  "date-common": "green-cooler",
  "date-deadline": "red-warmer",
  "date-deadline-subtle": "red-faint",
  "date-event": "fg-alt",
  "date-holiday": "yellow-warmer",
  "date-now": "fg-main",
  "date-range": "fg-alt",
  "date-scheduled": "yellow",
  "date-scheduled-subtle": "yellow-faint",
  "date-weekday": "yellow-cooler",
  "date-weekend": "blue",
  "fg-prose-code": "cyan-cooler",
  "prose-done": "green",
  "fg-prose-macro": "green-warmer",
  "prose-metadata": "fg-dim",
  "prose-metadata-value": "fg-alt",
  "prose-table": "fg-alt",
  "prose-table-formula": "warning",
  "prose-tag": "magenta-faint",
  "prose-todo": "red",
  "fg-prose-verbatim": "blue-warmer",
  "mail-cite-0": "yellow-cooler",
  "mail-cite-1": "blue-faint",
  "mail-cite-2": "green-faint",
  "mail-cite-3": "fg-dim",
  "mail-part": "cyan",
  "mail-recipient": "cyan-warmer",
  "mail-subject": "magenta-cooler",
  "mail-other": "blue-warmer",
  "bg-search-static": "bg-warning",
  "bg-search-current": "bg-yellow-intense",
  "bg-search-lazy": "bg-blue-intense",
  "bg-search-replace": "bg-red-intense",
  "bg-search-rx-group-0": "bg-magenta-intense",
  "bg-search-rx-group-1": "bg-green-intense",
  "bg-search-rx-group-2": "bg-red-subtle",
  "bg-search-rx-group-3": "bg-cyan-subtle",
  "bg-space-err": "bg-yellow-intense",
  "rainbow-0": "yellow-cooler",
  "rainbow-1": "blue-warmer",
  "rainbow-2": "magenta-cooler",
  "rainbow-3": "cyan",
  "rainbow-4": "magenta",
  "rainbow-5": "green-cooler",
  "rainbow-6": "red-faint",
  "rainbow-7": "yellow",
  "rainbow-8": "cyan-warmer",

  // --- ef-themes-palette-common (shared across all ef-themes) ---
  fringe: UNSPEC,
  property: "variable",
  "fg-region": UNSPEC,
  "fg-link-symbolic": "fg-alt",
  "underline-link": "border",
  "underline-link-visited": "border",
  "underline-link-symbolic": "border",
  "bg-line-number-active": UNSPEC,
  "fg-line-number-active": "accent-0",
  "bg-line-number-inactive": UNSPEC,
  "bg-prominent-err": "bg-err",
  "bg-prominent-warning": "bg-warning",
  "bg-prominent-note": "bg-info",
  "fg-prominent-err": "err",
  "fg-prominent-warning": "warning",
  "fg-prominent-note": "info",
  "bg-space": UNSPEC,
  "fg-space": "border",
  "bg-active-argument": "bg-warning",
  "fg-active-argument": "warning",
  "bg-active-value": "bg-info",
  "fg-active-value": "info",
  "bg-mark-delete": "bg-err",
  "fg-mark-delete": "err",
  "bg-mark-select": "bg-info",
  "fg-mark-select": "info",
  "bg-mark-other": "bg-warning",
  "fg-mark-other": "warning",
  "fg-search-current": "fg-main",
  "fg-search-lazy": "fg-main",
  "fg-search-static": "fg-main",
  "fg-search-replace": "fg-main",
  "fg-search-rx-group-0": "fg-main",
  "fg-search-rx-group-1": "fg-main",
  "fg-search-rx-group-2": "fg-main",
  "fg-search-rx-group-3": "fg-main",
  "fg-completion-match-0": "accent-0",
  "fg-completion-match-1": "accent-1",
  "fg-completion-match-2": "accent-2",
  "fg-completion-match-3": "accent-3",
  "fg-heading-0": "rainbow-0",
  "fg-heading-1": "rainbow-1",
  "fg-heading-2": "rainbow-2",
  "fg-heading-3": "rainbow-3",
  "fg-heading-4": "rainbow-4",
  "fg-heading-5": "rainbow-5",
  "fg-heading-6": "rainbow-6",
  "fg-heading-7": "rainbow-7",
  "fg-heading-8": "rainbow-8",
};

export const efSymbiosis: ThemeDoc = {
  meta: {
    name: "ef-symbiosis",
    description: "Legible dark brown-black theme with blue, green, cyan, gold colors.",
    mode: "dark",
  },
  palette,
  mappings,
};
