// ef-tritanopia-dark (dark) — bundled preset, both layers.
//
// The ef-themes are built on top of the modus-themes (since ef-themes 2.0.0):
// they use the same `modus-themes-theme` macro and palette structure. This seed
// is a faithful port so it can be edited and exported as a self-contained
// modus-themes derivative (no ef-themes dependency at load time).
//
// Transcribed verbatim from ef-tritanopia-dark-theme.el + ef-themes.el upstream:
//   - ef-tritanopia-dark-palette-partial            (named colors)
//   - ef-tritanopia-dark-palette-mappings-partial   (theme-specific mappings)
//   - ef-themes-palette-common            (shared mappings, appended)
// To refresh: re-transcribe from https://github.com/protesilaos/ef-themes
//
// A few shared entries (mode-line, tab-bar, bg-diff-context) are layer-1 colors
// in this model but defined upstream as mappings to other named colors; they are
// resolved to hex and placed in the palette block. All other mappings are kept
// symbolic, so resolve.ts follows the indirection as the modus engine does.

import { UNSPECIFIED as UNSPEC } from "./resolve.ts";
import type { Mapping, Palette, ThemeDoc } from "./types.ts";

const palette: Palette = {
  cursor: "#fd3333",
  "bg-main": "#15050f",
  "bg-dim": "#282026",
  "bg-alt": "#352f2f",
  "fg-main": "#dfd0d5",
  "fg-dim": "#908890",
  "fg-alt": "#afdaef",
  "bg-active": "#554f4f",
  "bg-inactive": "#2a2527",
  border: "#555564",
  red: "#cf4f5f",
  "red-warmer": "#df4f4f",
  "red-cooler": "#d24f7f",
  "red-faint": "#b07f7f",
  green: "#2fa526",
  "green-warmer": "#64aa0f",
  "green-cooler": "#00b066",
  "green-faint": "#5f9f6f",
  yellow: "#c48702",
  "yellow-warmer": "#d0730f",
  "yellow-cooler": "#df8f6f",
  "yellow-faint": "#cf9f7f",
  blue: "#379cf6",
  "blue-warmer": "#6a88ff",
  "blue-cooler": "#029fff",
  "blue-faint": "#6a84af",
  magenta: "#b0648f",
  "magenta-warmer": "#c560aa",
  "magenta-cooler": "#a6699f",
  "magenta-faint": "#c590af",
  cyan: "#3fafcf",
  "cyan-warmer": "#3f9aaf",
  "cyan-cooler": "#4fafaf",
  "cyan-faint": "#82a0af",
  "bg-red-intense": "#aa0010",
  "bg-green-intense": "#5f806f",
  "bg-yellow-intense": "#950f4f",
  "bg-blue-intense": "#165f70",
  "bg-magenta-intense": "#a04f9f",
  "bg-cyan-intense": "#007faa",
  "bg-red-subtle": "#6e1b20",
  "bg-green-subtle": "#054c38",
  "bg-yellow-subtle": "#65302f",
  "bg-blue-subtle": "#224360",
  "bg-magenta-subtle": "#603256",
  "bg-cyan-subtle": "#004a57",
  "bg-added": "#002d3f",
  "bg-added-faint": "#001f38",
  "bg-added-refine": "#003b4f",
  "fg-added": "#cbdfff",
  "bg-changed": "#352354",
  "bg-changed-faint": "#351444",
  "bg-changed-refine": "#383964",
  "fg-changed": "#e3cfff",
  "bg-removed": "#4d091f",
  "bg-removed-faint": "#37040f",
  "bg-removed-refine": "#6b0f26",
  "fg-removed": "#ffbfbf",
  "bg-mode-line-active": "#671822",
  "fg-mode-line-active": "#ffffff",
  "bg-completion": "#44272e",
  "bg-popup": "#28091d",
  "bg-hover": "#00405f",
  "bg-hover-secondary": "#5e3e5b",
  "bg-hl-line": "#3f1515",
  "bg-paren-match": "#2f5f7a",
  "bg-err": "#451212",
  "bg-warning": "#40173d",
  "bg-info": "#00354f",
  "bg-region": "#293140",
  "bg-diff-context": "#282026", // ef-common mapping resolved
  "bg-tab-bar": "#352f2f", // ef-common mapping resolved
  "bg-tab-current": "#15050f", // ef-common mapping resolved
  "bg-tab-other": "#554f4f", // ef-common mapping resolved
  "border-mode-line-active": "#555564", // ef-common mapping resolved
  "bg-mode-line-inactive": "#352f2f", // ef-common mapping resolved
  "fg-mode-line-inactive": "#908890", // ef-common mapping resolved
  "border-mode-line-inactive": "#555564", // ef-common mapping resolved
};

const mappings: Mapping = {
  // --- ef-tritanopia-dark-palette-mappings-partial ---
  err: "red-warmer",
  warning: "magenta-warmer",
  info: "cyan",
  "fg-link": "cyan",
  "fg-link-visited": "magenta-cooler",
  name: "magenta",
  keybind: "red-cooler",
  identifier: "magenta-faint",
  "fg-prompt": "cyan",
  builtin: "magenta",
  comment: "red-faint",
  constant: "red-cooler",
  fnname: "magenta-cooler",
  "fnname-call": "magenta-faint",
  keyword: "red",
  preprocessor: "magenta-cooler",
  docstring: "cyan-faint",
  string: "cyan",
  type: "cyan-warmer",
  variable: "cyan-cooler",
  "variable-use": "cyan-faint",
  "rx-backslash": "cyan-cooler",
  "rx-construct": "red",
  "accent-0": "cyan",
  "accent-1": "red",
  "accent-2": "cyan-warmer",
  "accent-3": "magenta",
  "date-common": "cyan-cooler",
  "date-deadline": "red-warmer",
  "date-deadline-subtle": "red-cooler",
  "date-event": "fg-alt",
  "date-holiday": "red-warmer",
  "date-now": "fg-main",
  "date-range": "fg-alt",
  "date-scheduled": "magenta",
  "date-scheduled-subtle": "magenta-cooler",
  "date-weekday": "cyan",
  "date-weekend": "red-faint",
  "fg-prose-code": "red",
  "prose-done": "cyan",
  "fg-prose-macro": "cyan-warmer",
  "prose-metadata": "fg-dim",
  "prose-metadata-value": "fg-alt",
  "prose-table": "fg-alt",
  "prose-table-formula": "err",
  "prose-tag": "fg-alt",
  "prose-todo": "red-warmer",
  "fg-prose-verbatim": "cyan",
  "mail-cite-0": "cyan",
  "mail-cite-1": "red-cooler",
  "mail-cite-2": "cyan-cooler",
  "mail-cite-3": "red-faint",
  "mail-part": "cyan-warmer",
  "mail-recipient": "magenta",
  "mail-subject": "red-warmer",
  "mail-other": "magenta-cooler",
  "bg-search-static": "bg-warning",
  "bg-search-current": "bg-red-intense",
  "bg-search-lazy": "bg-cyan-intense",
  "bg-search-replace": "bg-magenta-intense",
  "bg-search-rx-group-0": "bg-blue-intense",
  "bg-search-rx-group-1": "bg-magenta-intense",
  "bg-search-rx-group-2": "bg-cyan-subtle",
  "bg-search-rx-group-3": "bg-red-subtle",
  "bg-space-err": "bg-red-intense",
  "rainbow-0": "cyan",
  "rainbow-1": "red",
  "rainbow-2": "cyan-warmer",
  "rainbow-3": "red-cooler",
  "rainbow-4": "cyan-cooler",
  "rainbow-5": "magenta",
  "rainbow-6": "cyan-faint",
  "rainbow-7": "magenta-faint",
  "rainbow-8": "red-faint",

  // --- ef-themes-palette-common (shared across all ef-themes) ---
  fringe: UNSPEC,
  property: "variable",
  "fg-region": UNSPEC,
  "fg-link-symbolic": "fg-alt",
  "underline-link": "border",
  "underline-link-visited": "border",
  "underline-link-symbolic": "border",
  "bg-line-number-active": UNSPEC,
  "fg-line-number-active": "accent-0",
  "bg-line-number-inactive": UNSPEC,
  "bg-prominent-err": "bg-err",
  "bg-prominent-warning": "bg-warning",
  "bg-prominent-note": "bg-info",
  "fg-prominent-err": "err",
  "fg-prominent-warning": "warning",
  "fg-prominent-note": "info",
  "bg-space": UNSPEC,
  "fg-space": "border",
  "bg-active-argument": "bg-warning",
  "fg-active-argument": "warning",
  "bg-active-value": "bg-info",
  "fg-active-value": "info",
  "bg-mark-delete": "bg-err",
  "fg-mark-delete": "err",
  "bg-mark-select": "bg-info",
  "fg-mark-select": "info",
  "bg-mark-other": "bg-warning",
  "fg-mark-other": "warning",
  "fg-search-current": "fg-main",
  "fg-search-lazy": "fg-main",
  "fg-search-static": "fg-main",
  "fg-search-replace": "fg-main",
  "fg-search-rx-group-0": "fg-main",
  "fg-search-rx-group-1": "fg-main",
  "fg-search-rx-group-2": "fg-main",
  "fg-search-rx-group-3": "fg-main",
  "fg-completion-match-0": "accent-0",
  "fg-completion-match-1": "accent-1",
  "fg-completion-match-2": "accent-2",
  "fg-completion-match-3": "accent-3",
  "fg-heading-0": "rainbow-0",
  "fg-heading-1": "rainbow-1",
  "fg-heading-2": "rainbow-2",
  "fg-heading-3": "rainbow-3",
  "fg-heading-4": "rainbow-4",
  "fg-heading-5": "rainbow-5",
  "fg-heading-6": "rainbow-6",
  "fg-heading-7": "rainbow-7",
  "fg-heading-8": "rainbow-8",
};

export const efTritanopiaDark: ThemeDoc = {
  meta: {
    name: "ef-tritanopia-dark",
    description: "Legible dark theme, optimized for blue-yellow color deficiency.",
    mode: "dark",
  },
  palette,
  mappings,
};
