// ef-trio-light (light) — bundled preset, both layers.
//
// The ef-themes are built on top of the modus-themes (since ef-themes 2.0.0):
// they use the same `modus-themes-theme` macro and palette structure. This seed
// is a faithful port so it can be edited and exported as a self-contained
// modus-themes derivative (no ef-themes dependency at load time).
//
// Transcribed verbatim from ef-trio-light-theme.el + ef-themes.el upstream:
//   - ef-trio-light-palette-partial            (named colors)
//   - ef-trio-light-palette-mappings-partial   (theme-specific mappings)
//   - ef-themes-palette-common            (shared mappings, appended)
// To refresh: re-transcribe from https://github.com/protesilaos/ef-themes
//
// A few shared entries (mode-line, tab-bar, bg-diff-context) are layer-1 colors
// in this model but defined upstream as mappings to other named colors; they are
// resolved to hex and placed in the palette block. All other mappings are kept
// symbolic, so resolve.ts follows the indirection as the modus engine does.

import { UNSPECIFIED as UNSPEC } from "./resolve.ts";
import type { Mapping, Palette, ThemeDoc } from "./types.ts";

const palette: Palette = {
  cursor: "#4f45ff",
  "bg-main": "#f8f5ff",
  "bg-dim": "#ebe7f1",
  "bg-alt": "#e3e0e9",
  "fg-main": "#4f3363",
  "fg-dim": "#786e74",
  "fg-alt": "#3f7668",
  "bg-active": "#c3c0c9",
  "bg-inactive": "#e7e2eb",
  border: "#c6bac5",
  red: "#c3303a",
  "red-warmer": "#d03033",
  "red-cooler": "#c01f5f",
  "red-faint": "#a24568",
  green: "#057800",
  "green-warmer": "#4f7d0f",
  "green-cooler": "#007f6f",
  "green-faint": "#41754c",
  yellow: "#a45f22",
  "yellow-warmer": "#b8532f",
  "yellow-cooler": "#b65050",
  "yellow-faint": "#a05b5f",
  blue: "#375cd6",
  "blue-warmer": "#5165e4",
  "blue-cooler": "#065fbf",
  "blue-faint": "#6060d0",
  magenta: "#ad45ba",
  "magenta-warmer": "#c035aa",
  "magenta-cooler": "#705ae3",
  "magenta-faint": "#804fb0",
  cyan: "#1f6fbf",
  "cyan-warmer": "#3f6faf",
  "cyan-cooler": "#0f7a9d",
  "cyan-faint": "#5f60bf",
  "bg-red-intense": "#ff7f88",
  "bg-green-intense": "#7fdda0",
  "bg-yellow-intense": "#ffc200",
  "bg-blue-intense": "#cbcfff",
  "bg-magenta-intense": "#df8fff",
  "bg-cyan-intense": "#88ccff",
  "bg-red-subtle": "#ffc3c7",
  "bg-green-subtle": "#beecc2",
  "bg-yellow-subtle": "#f3ea8f",
  "bg-blue-subtle": "#ceddff",
  "bg-magenta-subtle": "#f5cff8",
  "bg-cyan-subtle": "#c0eaf0",
  "bg-added": "#caf4da",
  "bg-added-faint": "#dff6ea",
  "bg-added-refine": "#bae9cf",
  "fg-added": "#005000",
  "bg-changed": "#ffdfb9",
  "bg-changed-faint": "#ffefcb",
  "bg-changed-refine": "#ffcfa0",
  "fg-changed": "#553d00",
  "bg-removed": "#ffcee0",
  "bg-removed-faint": "#ffdfe6",
  "bg-removed-refine": "#f5b6c8",
  "fg-removed": "#8f1313",
  "bg-mode-line-active": "#ddb4ff",
  "fg-mode-line-active": "#241f48",
  "bg-completion": "#f4cfff",
  "bg-popup": "#efecf2",
  "bg-hover": "#aaeccf",
  "bg-hover-secondary": "#b4cfff",
  "bg-hl-line": "#cfe6ff",
  "bg-paren-match": "#dfadaf",
  "bg-err": "#ffdfe6",
  "bg-warning": "#ffe5bf",
  "bg-info": "#d0efdf",
  "bg-region": "#eed0ff",
  "bg-diff-context": "#ebe7f1", // ef-common mapping resolved
  "bg-tab-bar": "#e3e0e9", // ef-common mapping resolved
  "bg-tab-current": "#f8f5ff", // ef-common mapping resolved
  "bg-tab-other": "#c3c0c9", // ef-common mapping resolved
  "border-mode-line-active": "#c6bac5", // ef-common mapping resolved
  "bg-mode-line-inactive": "#e3e0e9", // ef-common mapping resolved
  "fg-mode-line-inactive": "#786e74", // ef-common mapping resolved
  "border-mode-line-inactive": "#c6bac5", // ef-common mapping resolved
};

const mappings: Mapping = {
  // --- ef-trio-light-palette-mappings-partial ---
  err: "red-warmer",
  warning: "yellow-warmer",
  info: "green",
  "fg-link": "cyan",
  "fg-link-visited": "green-warmer",
  name: "blue",
  keybind: "magenta-warmer",
  identifier: "red-faint",
  "fg-prompt": "blue-cooler",
  builtin: "magenta-cooler",
  comment: "yellow-faint",
  constant: "magenta-warmer",
  fnname: "blue-warmer",
  "fnname-call": "blue-faint",
  keyword: "magenta",
  preprocessor: "red-cooler",
  docstring: "magenta-faint",
  string: "green-cooler",
  type: "cyan-cooler",
  variable: "cyan-warmer",
  "variable-use": "cyan-faint",
  "rx-backslash": "blue-warmer",
  "rx-construct": "red",
  "accent-0": "magenta-warmer",
  "accent-1": "green-cooler",
  "accent-2": "blue-warmer",
  "accent-3": "yellow",
  "date-common": "cyan-cooler",
  "date-deadline": "red-warmer",
  "date-deadline-subtle": "red-cooler",
  "date-event": "fg-alt",
  "date-holiday": "magenta-warmer",
  "date-now": "fg-main",
  "date-range": "fg-alt",
  "date-scheduled": "yellow",
  "date-scheduled-subtle": "yellow-faint",
  "date-weekday": "cyan",
  "date-weekend": "red-faint",
  "fg-prose-code": "green-cooler",
  "prose-done": "green",
  "fg-prose-macro": "blue-warmer",
  "prose-metadata": "fg-dim",
  "prose-metadata-value": "fg-alt",
  "prose-table": "fg-alt",
  "prose-table-formula": "err",
  "prose-tag": "magenta-faint",
  "prose-todo": "red-warmer",
  "fg-prose-verbatim": "magenta-warmer",
  "mail-cite-0": "blue-warmer",
  "mail-cite-1": "magenta-warmer",
  "mail-cite-2": "cyan-cooler",
  "mail-cite-3": "magenta-cooler",
  "mail-part": "cyan-warmer",
  "mail-recipient": "blue",
  "mail-subject": "magenta",
  "mail-other": "cyan",
  "bg-search-static": "bg-warning",
  "bg-search-current": "bg-yellow-intense",
  "bg-search-lazy": "bg-blue-intense",
  "bg-search-replace": "bg-red-intense",
  "bg-search-rx-group-0": "bg-magenta-intense",
  "bg-search-rx-group-1": "bg-green-intense",
  "bg-search-rx-group-2": "bg-red-subtle",
  "bg-search-rx-group-3": "bg-cyan-subtle",
  "bg-space-err": "bg-yellow-intense",
  "rainbow-0": "magenta-warmer",
  "rainbow-1": "blue-warmer",
  "rainbow-2": "green-cooler",
  "rainbow-3": "magenta",
  "rainbow-4": "cyan",
  "rainbow-5": "yellow-cooler",
  "rainbow-6": "magenta-cooler",
  "rainbow-7": "cyan-warmer",
  "rainbow-8": "green-warmer",

  // --- ef-themes-palette-common (shared across all ef-themes) ---
  fringe: UNSPEC,
  property: "variable",
  "fg-region": UNSPEC,
  "fg-link-symbolic": "fg-alt",
  "underline-link": "border",
  "underline-link-visited": "border",
  "underline-link-symbolic": "border",
  "bg-line-number-active": UNSPEC,
  "fg-line-number-active": "accent-0",
  "bg-line-number-inactive": UNSPEC,
  "bg-prominent-err": "bg-err",
  "bg-prominent-warning": "bg-warning",
  "bg-prominent-note": "bg-info",
  "fg-prominent-err": "err",
  "fg-prominent-warning": "warning",
  "fg-prominent-note": "info",
  "bg-space": UNSPEC,
  "fg-space": "border",
  "bg-active-argument": "bg-warning",
  "fg-active-argument": "warning",
  "bg-active-value": "bg-info",
  "fg-active-value": "info",
  "bg-mark-delete": "bg-err",
  "fg-mark-delete": "err",
  "bg-mark-select": "bg-info",
  "fg-mark-select": "info",
  "bg-mark-other": "bg-warning",
  "fg-mark-other": "warning",
  "fg-search-current": "fg-main",
  "fg-search-lazy": "fg-main",
  "fg-search-static": "fg-main",
  "fg-search-replace": "fg-main",
  "fg-search-rx-group-0": "fg-main",
  "fg-search-rx-group-1": "fg-main",
  "fg-search-rx-group-2": "fg-main",
  "fg-search-rx-group-3": "fg-main",
  "fg-completion-match-0": "accent-0",
  "fg-completion-match-1": "accent-1",
  "fg-completion-match-2": "accent-2",
  "fg-completion-match-3": "accent-3",
  "fg-heading-0": "rainbow-0",
  "fg-heading-1": "rainbow-1",
  "fg-heading-2": "rainbow-2",
  "fg-heading-3": "rainbow-3",
  "fg-heading-4": "rainbow-4",
  "fg-heading-5": "rainbow-5",
  "fg-heading-6": "rainbow-6",
  "fg-heading-7": "rainbow-7",
  "fg-heading-8": "rainbow-8",
};

export const efTrioLight: ThemeDoc = {
  meta: {
    name: "ef-trio-light",
    description: "Legible light purple grey theme with magenta, blue, and teal colors.",
    mode: "light",
  },
  palette,
  mappings,
};
