// ef-trio-dark (dark) — bundled preset, both layers.
//
// The ef-themes are built on top of the modus-themes (since ef-themes 2.0.0):
// they use the same `modus-themes-theme` macro and palette structure. This seed
// is a faithful port so it can be edited and exported as a self-contained
// modus-themes derivative (no ef-themes dependency at load time).
//
// Transcribed verbatim from ef-trio-dark-theme.el + ef-themes.el upstream:
//   - ef-trio-dark-palette-partial            (named colors)
//   - ef-trio-dark-palette-mappings-partial   (theme-specific mappings)
//   - ef-themes-palette-common            (shared mappings, appended)
// To refresh: re-transcribe from https://github.com/protesilaos/ef-themes
//
// A few shared entries (mode-line, tab-bar, bg-diff-context) are layer-1 colors
// in this model but defined upstream as mappings to other named colors; they are
// resolved to hex and placed in the palette block. All other mappings are kept
// symbolic, so resolve.ts follows the indirection as the modus engine does.

import { UNSPECIFIED as UNSPEC } from "./resolve.ts";
import type { Mapping, Palette, ThemeDoc } from "./types.ts";

const palette: Palette = {
  cursor: "#ff99ff",
  "bg-main": "#160f0f",
  "bg-dim": "#2a2228",
  "bg-alt": "#362f35",
  "fg-main": "#d8cfd5",
  "fg-dim": "#908890",
  "fg-alt": "#afdacf",
  "bg-active": "#564f55",
  "bg-inactive": "#2c2729",
  border: "#605760",
  red: "#f48359",
  "red-warmer": "#ff7560",
  "red-cooler": "#ff85aa",
  "red-faint": "#e07a9a",
  green: "#60b444",
  "green-warmer": "#a0c27f",
  "green-cooler": "#60bf88",
  "green-faint": "#61a06c",
  yellow: "#d4a052",
  "yellow-warmer": "#ef926f",
  "yellow-cooler": "#ef9680",
  "yellow-faint": "#c7a07f",
  blue: "#7fa5f6",
  "blue-warmer": "#8895ff",
  "blue-cooler": "#72afff",
  "blue-faint": "#7a94df",
  magenta: "#d37faf",
  "magenta-warmer": "#e772df",
  "magenta-cooler": "#a698ef",
  "magenta-faint": "#c9addf",
  cyan: "#8fbaff",
  "cyan-warmer": "#9ac2ff",
  "cyan-cooler": "#8fcfdf",
  "cyan-faint": "#8ac0ef",
  "bg-red-intense": "#b02930",
  "bg-green-intense": "#2a7140",
  "bg-yellow-intense": "#8f5040",
  "bg-blue-intense": "#4648d0",
  "bg-magenta-intense": "#804fd5",
  "bg-cyan-intense": "#2270cf",
  "bg-red-subtle": "#651f1a",
  "bg-green-subtle": "#1a421f",
  "bg-yellow-subtle": "#553320",
  "bg-blue-subtle": "#283565",
  "bg-magenta-subtle": "#562654",
  "bg-cyan-subtle": "#133d58",
  "bg-added": "#00371f",
  "bg-added-faint": "#002918",
  "bg-added-refine": "#004c2f",
  "fg-added": "#a0e0a0",
  "bg-changed": "#363300",
  "bg-changed-faint": "#2a1f00",
  "bg-changed-refine": "#4a4a00",
  "fg-changed": "#efef80",
  "bg-removed": "#450f1f",
  "bg-removed-faint": "#2f060f",
  "bg-removed-refine": "#641426",
  "fg-removed": "#ffbfbf",
  "bg-mode-line-active": "#6a294f",
  "fg-mode-line-active": "#ffdfdf",
  "bg-completion": "#2f335a",
  "bg-popup": "#241818",
  "bg-hover": "#004f3f",
  "bg-hover-secondary": "#452f5f",
  "bg-hl-line": "#34223f",
  "bg-paren-match": "#2f605e",
  "bg-err": "#461018",
  "bg-warning": "#3a330f",
  "bg-info": "#103515",
  "bg-region": "#16304f",
  "bg-diff-context": "#2a2228", // ef-common mapping resolved
  "bg-tab-bar": "#362f35", // ef-common mapping resolved
  "bg-tab-current": "#160f0f", // ef-common mapping resolved
  "bg-tab-other": "#564f55", // ef-common mapping resolved
  "border-mode-line-active": "#605760", // ef-common mapping resolved
  "bg-mode-line-inactive": "#362f35", // ef-common mapping resolved
  "fg-mode-line-inactive": "#908890", // ef-common mapping resolved
  "border-mode-line-inactive": "#605760", // ef-common mapping resolved
};

const mappings: Mapping = {
  // --- ef-trio-dark-palette-mappings-partial ---
  err: "red-warmer",
  warning: "yellow",
  info: "green",
  "fg-link": "cyan",
  "fg-link-visited": "green-warmer",
  name: "blue",
  keybind: "magenta-warmer",
  identifier: "red-faint",
  "fg-prompt": "blue-cooler",
  builtin: "magenta-cooler",
  comment: "yellow-faint",
  constant: "magenta-warmer",
  fnname: "blue-warmer",
  "fnname-call": "blue-faint",
  keyword: "magenta",
  preprocessor: "red-cooler",
  docstring: "magenta-faint",
  string: "green-cooler",
  type: "cyan-cooler",
  variable: "cyan-warmer",
  "variable-use": "cyan-faint",
  "rx-backslash": "blue-warmer",
  "rx-construct": "red",
  "accent-0": "magenta-warmer",
  "accent-1": "green-cooler",
  "accent-2": "blue-warmer",
  "accent-3": "yellow",
  "date-common": "cyan-cooler",
  "date-deadline": "red-warmer",
  "date-deadline-subtle": "red-faint",
  "date-event": "fg-alt",
  "date-holiday": "magenta-warmer",
  "date-now": "fg-main",
  "date-range": "fg-alt",
  "date-scheduled": "yellow",
  "date-scheduled-subtle": "yellow-faint",
  "date-weekday": "cyan",
  "date-weekend": "red-faint",
  "fg-prose-code": "green-cooler",
  "prose-done": "green",
  "fg-prose-macro": "blue-warmer",
  "prose-metadata": "fg-dim",
  "prose-metadata-value": "fg-alt",
  "prose-table": "fg-alt",
  "prose-table-formula": "err",
  "prose-tag": "magenta-faint",
  "prose-todo": "red-warmer",
  "fg-prose-verbatim": "magenta-warmer",
  "mail-cite-0": "blue-warmer",
  "mail-cite-1": "magenta-warmer",
  "mail-cite-2": "green-cooler",
  "mail-cite-3": "magenta-cooler",
  "mail-part": "cyan-cooler",
  "mail-recipient": "blue",
  "mail-subject": "magenta",
  "mail-other": "cyan",
  "bg-search-static": "bg-warning",
  "bg-search-current": "bg-yellow-intense",
  "bg-search-lazy": "bg-blue-intense",
  "bg-search-replace": "bg-red-intense",
  "bg-search-rx-group-0": "bg-magenta-intense",
  "bg-search-rx-group-1": "bg-green-intense",
  "bg-search-rx-group-2": "bg-red-subtle",
  "bg-search-rx-group-3": "bg-cyan-subtle",
  "bg-space-err": "bg-yellow-intense",
  "rainbow-0": "magenta-warmer",
  "rainbow-1": "blue-warmer",
  "rainbow-2": "green-cooler",
  "rainbow-3": "magenta",
  "rainbow-4": "cyan",
  "rainbow-5": "yellow-cooler",
  "rainbow-6": "magenta-cooler",
  "rainbow-7": "cyan-warmer",
  "rainbow-8": "green-warmer",

  // --- ef-themes-palette-common (shared across all ef-themes) ---
  fringe: UNSPEC,
  property: "variable",
  "fg-region": UNSPEC,
  "fg-link-symbolic": "fg-alt",
  "underline-link": "border",
  "underline-link-visited": "border",
  "underline-link-symbolic": "border",
  "bg-line-number-active": UNSPEC,
  "fg-line-number-active": "accent-0",
  "bg-line-number-inactive": UNSPEC,
  "bg-prominent-err": "bg-err",
  "bg-prominent-warning": "bg-warning",
  "bg-prominent-note": "bg-info",
  "fg-prominent-err": "err",
  "fg-prominent-warning": "warning",
  "fg-prominent-note": "info",
  "bg-space": UNSPEC,
  "fg-space": "border",
  "bg-active-argument": "bg-warning",
  "fg-active-argument": "warning",
  "bg-active-value": "bg-info",
  "fg-active-value": "info",
  "bg-mark-delete": "bg-err",
  "fg-mark-delete": "err",
  "bg-mark-select": "bg-info",
  "fg-mark-select": "info",
  "bg-mark-other": "bg-warning",
  "fg-mark-other": "warning",
  "fg-search-current": "fg-main",
  "fg-search-lazy": "fg-main",
  "fg-search-static": "fg-main",
  "fg-search-replace": "fg-main",
  "fg-search-rx-group-0": "fg-main",
  "fg-search-rx-group-1": "fg-main",
  "fg-search-rx-group-2": "fg-main",
  "fg-search-rx-group-3": "fg-main",
  "fg-completion-match-0": "accent-0",
  "fg-completion-match-1": "accent-1",
  "fg-completion-match-2": "accent-2",
  "fg-completion-match-3": "accent-3",
  "fg-heading-0": "rainbow-0",
  "fg-heading-1": "rainbow-1",
  "fg-heading-2": "rainbow-2",
  "fg-heading-3": "rainbow-3",
  "fg-heading-4": "rainbow-4",
  "fg-heading-5": "rainbow-5",
  "fg-heading-6": "rainbow-6",
  "fg-heading-7": "rainbow-7",
  "fg-heading-8": "rainbow-8",
};

export const efTrioDark: ThemeDoc = {
  meta: {
    name: "ef-trio-dark",
    description: "Legible dark purple grey theme with magenta, blue, teal colors.",
    mode: "dark",
  },
  palette,
  mappings,
};
