// ef-winter (dark) — bundled preset, both layers.
//
// The ef-themes are built on top of the modus-themes (since ef-themes 2.0.0):
// they use the same `modus-themes-theme` macro and palette structure. This seed
// is a faithful port so it can be edited and exported as a self-contained
// modus-themes derivative (no ef-themes dependency at load time).
//
// Transcribed verbatim from ef-winter-theme.el + ef-themes.el upstream:
//   - ef-winter-palette-partial            (named colors)
//   - ef-winter-palette-mappings-partial   (theme-specific mappings)
//   - ef-themes-palette-common            (shared mappings, appended)
// To refresh: re-transcribe from https://github.com/protesilaos/ef-themes
//
// A few shared entries (mode-line, tab-bar, bg-diff-context) are layer-1 colors
// in this model but defined upstream as mappings to other named colors; they are
// resolved to hex and placed in the palette block. All other mappings are kept
// symbolic, so resolve.ts follows the indirection as the modus engine does.

import { UNSPECIFIED as UNSPEC } from "./resolve.ts";
import type { Mapping, Palette, ThemeDoc } from "./types.ts";

const palette: Palette = {
  cursor: "#ff6ff0",
  "bg-main": "#0f0b15",
  "bg-dim": "#1d202f",
  "bg-alt": "#2a2f42",
  "fg-main": "#b8c6d5",
  "fg-dim": "#807c9f",
  "fg-alt": "#bf8a9f",
  "bg-active": "#4a4f62",
  "bg-inactive": "#29282f",
  border: "#4a4955",
  red: "#f47359",
  "red-warmer": "#ef6560",
  "red-cooler": "#ff6a7a",
  "red-faint": "#d56f72",
  green: "#29a444",
  "green-warmer": "#6aad0f",
  "green-cooler": "#00a392",
  "green-faint": "#61a06c",
  yellow: "#b58a52",
  "yellow-warmer": "#d1803f",
  "yellow-cooler": "#df9080",
  "yellow-faint": "#c0a38a",
  blue: "#3f95f6",
  "blue-warmer": "#6a9fff",
  "blue-cooler": "#029fff",
  "blue-faint": "#7a94df",
  magenta: "#d369af",
  "magenta-warmer": "#e580e0",
  "magenta-cooler": "#af85ea",
  "magenta-faint": "#c57faf",
  cyan: "#4fbaef",
  "cyan-warmer": "#6fafdf",
  "cyan-cooler": "#35afbf",
  "cyan-faint": "#8aa0df",
  "bg-red-intense": "#b02930",
  "bg-green-intense": "#0a7040",
  "bg-yellow-intense": "#8f5040",
  "bg-blue-intense": "#4648d0",
  "bg-magenta-intense": "#a04fc5",
  "bg-cyan-intense": "#2270cf",
  "bg-red-subtle": "#67182f",
  "bg-green-subtle": "#10452f",
  "bg-yellow-subtle": "#54362a",
  "bg-blue-subtle": "#2a346e",
  "bg-magenta-subtle": "#572454",
  "bg-cyan-subtle": "#133d56",
  "bg-added": "#00371f",
  "bg-added-faint": "#002918",
  "bg-added-refine": "#004c2f",
  "fg-added": "#a0e0a0",
  "bg-changed": "#363300",
  "bg-changed-faint": "#2a1f00",
  "bg-changed-refine": "#4a4a00",
  "fg-changed": "#efef80",
  "bg-removed": "#450f1f",
  "bg-removed-faint": "#2f060f",
  "bg-removed-refine": "#641426",
  "fg-removed": "#ffbfbf",
  "bg-mode-line-active": "#5f1f5f",
  "fg-mode-line-active": "#dedeff",
  "bg-completion": "#2f2a7a",
  "bg-popup": "#1a1324",
  "bg-hover": "#00474f",
  "bg-hover-secondary": "#44196f",
  "bg-hl-line": "#003045",
  "bg-paren-match": "#2f608e",
  "bg-err": "#44101a",
  "bg-warning": "#393312",
  "bg-info": "#0f3518",
  "bg-region": "#342464",
  "bg-diff-context": "#1d202f", // ef-common mapping resolved
  "bg-tab-bar": "#2a2f42", // ef-common mapping resolved
  "bg-tab-current": "#0f0b15", // ef-common mapping resolved
  "bg-tab-other": "#4a4f62", // ef-common mapping resolved
  "border-mode-line-active": "#4a4955", // ef-common mapping resolved
  "bg-mode-line-inactive": "#2a2f42", // ef-common mapping resolved
  "fg-mode-line-inactive": "#807c9f", // ef-common mapping resolved
  "border-mode-line-inactive": "#4a4955", // ef-common mapping resolved
};

const mappings: Mapping = {
  // --- ef-winter-palette-mappings-partial ---
  err: "red-warmer",
  warning: "yellow",
  info: "green",
  "fg-link": "magenta",
  "fg-link-visited": "cyan-warmer",
  name: "magenta",
  keybind: "cyan-cooler",
  identifier: "magenta-faint",
  "fg-prompt": "magenta-warmer",
  builtin: "magenta-warmer",
  comment: "yellow-faint",
  constant: "magenta",
  fnname: "cyan-cooler",
  "fnname-call": "cyan-faint",
  keyword: "magenta-cooler",
  preprocessor: "red-cooler",
  docstring: "cyan-faint",
  string: "yellow-cooler",
  type: "cyan",
  variable: "blue-warmer",
  "variable-use": "blue-faint",
  "rx-backslash": "green",
  "rx-construct": "blue",
  "accent-0": "magenta-cooler",
  "accent-1": "yellow",
  "accent-2": "green-cooler",
  "accent-3": "magenta-warmer",
  "date-common": "cyan-cooler",
  "date-deadline": "red-warmer",
  "date-deadline-subtle": "red-faint",
  "date-event": "fg-alt",
  "date-holiday": "magenta",
  "date-now": "fg-main",
  "date-range": "fg-alt",
  "date-scheduled": "yellow",
  "date-scheduled-subtle": "yellow-faint",
  "date-weekday": "cyan",
  "date-weekend": "red-faint",
  "fg-prose-code": "yellow",
  "prose-done": "green",
  "fg-prose-macro": "green-cooler",
  "prose-metadata": "fg-dim",
  "prose-metadata-value": "fg-alt",
  "prose-table": "fg-alt",
  "prose-table-formula": "info",
  "prose-tag": "cyan-faint",
  "prose-todo": "red-warmer",
  "fg-prose-verbatim": "magenta-cooler",
  "mail-cite-0": "magenta-cooler",
  "mail-cite-1": "yellow-cooler",
  "mail-cite-2": "cyan-cooler",
  "mail-cite-3": "magenta",
  "mail-part": "magenta-faint",
  "mail-recipient": "magenta",
  "mail-subject": "blue-warmer",
  "mail-other": "magenta-cooler",
  "bg-search-static": "bg-warning",
  "bg-search-current": "bg-yellow-intense",
  "bg-search-lazy": "bg-blue-intense",
  "bg-search-replace": "bg-red-intense",
  "bg-search-rx-group-0": "bg-magenta-intense",
  "bg-search-rx-group-1": "bg-green-intense",
  "bg-search-rx-group-2": "bg-red-subtle",
  "bg-search-rx-group-3": "bg-cyan-subtle",
  "rainbow-0": "magenta",
  "rainbow-1": "cyan-cooler",
  "rainbow-2": "magenta-cooler",
  "rainbow-3": "yellow",
  "rainbow-4": "blue-warmer",
  "rainbow-5": "magenta-warmer",
  "rainbow-6": "green-cooler",
  "rainbow-7": "yellow-cooler",
  "rainbow-8": "cyan-warmer",

  // --- ef-themes-palette-common (shared across all ef-themes) ---
  fringe: UNSPEC,
  property: "variable",
  "fg-region": UNSPEC,
  "fg-link-symbolic": "fg-alt",
  "underline-link": "border",
  "underline-link-visited": "border",
  "underline-link-symbolic": "border",
  "bg-line-number-active": UNSPEC,
  "fg-line-number-active": "accent-0",
  "bg-line-number-inactive": UNSPEC,
  "bg-prominent-err": "bg-err",
  "bg-prominent-warning": "bg-warning",
  "bg-prominent-note": "bg-info",
  "fg-prominent-err": "err",
  "fg-prominent-warning": "warning",
  "fg-prominent-note": "info",
  "bg-space": UNSPEC,
  "fg-space": "border",
  "bg-active-argument": "bg-warning",
  "fg-active-argument": "warning",
  "bg-active-value": "bg-info",
  "fg-active-value": "info",
  "bg-mark-delete": "bg-err",
  "fg-mark-delete": "err",
  "bg-mark-select": "bg-info",
  "fg-mark-select": "info",
  "bg-mark-other": "bg-warning",
  "fg-mark-other": "warning",
  "fg-search-current": "fg-main",
  "fg-search-lazy": "fg-main",
  "fg-search-static": "fg-main",
  "fg-search-replace": "fg-main",
  "fg-search-rx-group-0": "fg-main",
  "fg-search-rx-group-1": "fg-main",
  "fg-search-rx-group-2": "fg-main",
  "fg-search-rx-group-3": "fg-main",
  "fg-completion-match-0": "accent-0",
  "fg-completion-match-1": "accent-1",
  "fg-completion-match-2": "accent-2",
  "fg-completion-match-3": "accent-3",
  "fg-heading-0": "rainbow-0",
  "fg-heading-1": "rainbow-1",
  "fg-heading-2": "rainbow-2",
  "fg-heading-3": "rainbow-3",
  "fg-heading-4": "rainbow-4",
  "fg-heading-5": "rainbow-5",
  "fg-heading-6": "rainbow-6",
  "fg-heading-7": "rainbow-7",
  "fg-heading-8": "rainbow-8",
};

export const efWinter: ThemeDoc = {
  meta: {
    name: "ef-winter",
    description: "Legible dark purple-black theme with magenta, purple, fawn, teal colors.",
    mode: "dark",
  },
  palette,
  mappings,
};
