// Emit Emacs Lisp from a ThemeDoc:
//   - exportThemeFile: a self-contained derivative theme file built on modus-themes,
//     following the modus-*-theme.el skeleton (defconst palette + modus-themes-theme).
//   - exportOverrides: a (setq <base>-palette-overrides '(...)) snippet containing
//     only the entries that differ from the chosen base preset.

import { modusOperandi } from "./modus-operandi.ts";
import { modusVivendi } from "./modus-vivendi.ts";
import { COLOR_GROUPS, ROLE_GROUPS, type ColorKey } from "./palette-keys.ts";
import { isHex, UNSPECIFIED } from "./resolve.ts";
import type { MappingValue, Palette, ThemeDoc } from "./types.ts";

/**
 * The modus-themes face specs reference the full set of named colors directly
 * (e.g. `modeline-err`, `bg-char-0`, the terminal colors). A preset ported from
 * a leaner palette (such as the ef-themes) may omit some, which would raise a
 * `void-variable` at load time. Backfill any missing named color from the
 * matching Modus base so every exported theme is self-contained and loadable.
 */
function completePalette(doc: ThemeDoc): Palette {
  const base = doc.meta.mode === "dark" ? modusVivendi.palette : modusOperandi.palette;
  return { ...base, ...doc.palette };
}

/**
 * A mapping value is emitted as a bare elisp SYMBOL unless it is a literal hex
 * color (which must be a quoted string). Both palette-color names and other
 * semantic-role names (e.g. `accent-0`, `rainbow-0` — the modus engine chains
 * through these) are symbols, so only a `#hex` value gets quotes.
 */
function formatValue(value: MappingValue): string {
  if (value === UNSPECIFIED) return "unspecified";
  if (isHex(value)) return `"${value}"`; // raw hex string -> quoted
  return value; // a color-name or role-name symbol -> bare
}

function entry(key: string, value: string): string {
  // Pad the key column so the alist lines up, mirroring upstream formatting.
  return `    (${key.padEnd(26)} ${value})`;
}

/** Build the `(...)` body of the palette alist: layer-1 colors then layer-2 mappings. */
function paletteBody(doc: ThemeDoc): string {
  const lines: string[] = [];
  const palette = completePalette(doc);

  for (const group of COLOR_GROUPS) {
    const present = group.keys.filter((k): k is ColorKey => palette[k] != null);
    if (present.length === 0) continue;
    lines.push(`;;; ${group.title}`);
    for (const k of present) lines.push(entry(k, `"${palette[k]!}"`));
    lines.push("");
  }

  lines.push(";;;; Semantic mappings");
  // Emit EVERY mapping key so the modus-themes face specs (which reference the
  // full set of mapping symbols) never hit a `void-variable` at load time.
  //
  // Resolution order per key:
  //   1. an explicit mapping in the doc -> use it
  //   2. else, if the doc's PALETTE defines this name as a color (some themes,
  //      e.g. the ef-themes, define `cursor` as a named color) -> emit that hex,
  //      so the symbol is still bound
  //   3. else -> `unspecified`
  for (const group of ROLE_GROUPS) {
    lines.push(`;;; ${group.title}`);
    for (const k of group.keys) {
      const mapped = doc.mappings[k];
      const paletteColor = palette[k as ColorKey];
      const value = mapped ?? paletteColor ?? UNSPECIFIED;
      lines.push(entry(k, formatValue(value)));
    }
    lines.push("");
  }

  return lines.join("\n").trimEnd();
}

export function exportThemeFile(doc: ThemeDoc): string {
  const { name, description, mode } = doc.meta;
  const safeDesc = description.replace(/"/g, '\\"');

  // Mirrors the structure of a real bundled modus-*-theme.el: everything is
  // wrapped in one `eval-and-compile` form containing the require guard, the
  // `deftheme` declaration, the palette `defconst`, the overrides `defcustom`,
  // and the 3-argument `modus-themes-theme` call (NAME PALETTE OVERRIDES, with
  // UNQUOTED symbols) followed by `provide-theme`. `provide` sits outside.
  const palette = paletteBody(doc)
    .split("\n")
    .map((l) => (l ? `    ${l}` : l))
    .join("\n");

  return `;;; ${name}-theme.el --- ${description} -*- lexical-binding:t -*-

;; Generated by the Modus Theme Generator. Built on top of the modus-themes.
;; Requires the \`modus-themes' package (bundled with Emacs >= 30, or installable
;; from GNU ELPA) to be available.

;;; Code:

(eval-and-compile
  (unless (and (fboundp 'require-theme)
               load-file-name
               (equal (file-name-directory load-file-name)
                      (expand-file-name "themes/" data-directory))
               (require-theme 'modus-themes t))
    (require 'modus-themes))

;;;###theme-autoload
  (deftheme ${name}
    "${safeDesc}"
    :background-mode '${mode}
    :kind 'color-scheme
    :family 'modus)

  (defconst ${name}-palette
    '(
${palette}
)
    "The entire palette of the \`${name}' theme.

Named colors have the form (COLOR-NAME HEX-VALUE) with the former
as a symbol and the latter as a string.

Semantic color mappings have the form (MAPPING-NAME COLOR-NAME)
with both as symbols.  The latter is a named color that already
exists in the palette and is associated with a HEX-VALUE.")

  (defcustom ${name}-palette-overrides nil
    "Overrides for \`${name}-palette'.

Mirror the elements of the aforementioned palette, overriding
their value.  Theme-specific overrides take precedence over the
shared \`modus-themes-common-palette-overrides'."
    :group 'modus-themes
    :type '(repeat (list symbol (choice symbol string)))
    :set #'modus-themes--set-option
    :initialize #'custom-initialize-default)

  (modus-themes-theme ${name}
                      ${name}-palette
                      ${name}-palette-overrides)

  (provide-theme '${name}))

;;; ${name}-theme.el ends here
`;
}

/**
 * Emit a palette-overrides setq snippet containing only entries that differ
 * from `base`. Compares both layer-1 colors and layer-2 mappings.
 */
export function exportOverrides(doc: ThemeDoc, base: ThemeDoc, baseId: string): string {
  const lines: string[] = [];

  for (const group of COLOR_GROUPS) {
    for (const k of group.keys) {
      const cur = doc.palette[k];
      if (cur != null && cur !== base.palette[k]) {
        lines.push(entry(k, `"${cur}"`));
      }
    }
  }
  for (const group of ROLE_GROUPS) {
    for (const k of group.keys) {
      const cur = doc.mappings[k];
      if (cur != null && cur !== base.mappings[k]) {
        lines.push(entry(k, formatValue(cur)));
      }
    }
  }

  if (lines.length === 0) {
    return `;; No changes from ${baseId} yet — edit some colors to populate this snippet.`;
  }

  return `(setq ${baseId}-palette-overrides
  '(
${lines.join("\n")}
  ))`;
}
